GlobalFishingWatch/frontend

- packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
- packages/layer-composer/src/generators/heatmap/heatmap-layers-paint.ts
- packages/layer-composer/src/generators/heatmap/util/time-chunks.ts
- sends value breaks to MGL worker --> see https://github.com/GlobalFishingWatch/mapbox-gl-js/pull/77
- use a `step` expression instead of `interpolate`ing values
- use a `coalesce` expression instead of `to-number`, which more elegantly sets the default value in case of nulls
> Use MGL worker breaks in layer-composer animated heatmap generator 

- applications/amathea/src/features/dataviews/dataviews.selectors.ts
- packages/layer-composer/src/generators/heatmap/config.ts
- packages/layer-composer/src/generators/heatmap/heatmap-layers-paint.ts
- packages/layer-composer/src/generators/heatmap/heatmap.ts
- packages/layer-composer/src/generators/types.ts
- packages/react-hooks/src/use-dataviews-layers/use-dataviews-layers.ts
- packages/ui-components/src/map-legend/MapLegend.tsx
Use stats by `config.id` to allow having different 4wings layers at the same time
Also include param called `steps` to be able to customise steps from the generator instead of the stats (normally saved in the dataview)
> 4wings multiple layers

- .changeset/popular-zebras-tickle.md
- packages/layer-composer/src/generators/heatmap/heatmap.ts
- packages/layer-composer/src/generators/types.ts
Restore use case for carrier portal when pow scale is needed, to keep compatibility with both use cases the exponent by default is 1
> restore pow scale for cvp use case

- applications/fishing-map/src/App.tsx
- applications/fishing-map/src/features/map/Map.tsx
- applications/fishing-map/src/features/map/map.selectors.ts
- applications/fishing-map/src/features/resources/resources.slice.ts
- applications/fishing-map/src/features/search/search.slice.ts
- applications/fishing-map/src/features/user/user.slice.ts
- applications/fishing-map/src/features/workspace/workspace.mock.ts
- applications/fishing-map/src/features/workspace/workspace.selectors.ts
- applications/fishing-map/src/features/workspace/workspace.slice.ts
- applications/fishing-map/src/store.ts
- applications/fishing-map/src/types/index.ts
- packages/dataviews-client/src/index.ts
- packages/dataviews-client/src/resolve-endpoint.ts
- packages/dataviews-client/src/types.ts
Adds a simple Resources slice where resources are indexed by URL.
The URLs of resources are resolved by the `selectDataviewsResourceQueries` selector using the dataview, its dataset and its datasetParams.
Nevertheless, ATM the track URL is still hardcoded because I have no dataset id and no vessel id yet to use.
Also, I have changed AsyncReducerStatus to a TS enum, which I think which should start to use by default rather than loose `'foo' | 'bar'` string types.
> Resources slice

- applications/fishing-map/src/App.tsx
- applications/fishing-map/src/data/config.ts
- applications/fishing-map/src/features/search/Search.tsx
- applications/fishing-map/src/features/sidebar/Sidebar.tsx
- applications/fishing-map/src/features/sidebar/vessels/VesselLayerPanel.tsx
- applications/fishing-map/src/features/sidebar/vessels/VesselsSection.tsx
- applications/fishing-map/src/features/workspace/workspace.slice.ts
- applications/fishing-map/src/routes/routes.hook.ts
- applications/fishing-map/src/routes/routes.selectors.ts
- applications/fishing-map/src/routes/routes.ts
- applications/fishing-map/src/store.ts
- applications/fishing-map/src/types/index.ts
Prepare routes path to support, for example, `/indonesia` using indonesia as workspace id.
Also supports API version path with `/:workspaceId/v1|v2...`
I had to remove the `/search` path as was hard to make it compatible with the workspaceId and version optional params, now is used with the `query` queryParam and also moved the sidebarOpen state to URL too
Something to notice is an easy improvement using [redux-toolkit batch](https://react-redux.js.org/api/batch) [here](https://github.com/GlobalFishingWatch/frontend/compare/workspace-id-path?expand=1#diff-0fc787fc5bdbf9885682179d3112abad8749adc32b96fd9b5f511b878b7c089eR38) to group actions dispatch and avoid multiple re-renders
> Workspace id path

- applications/fishing-map/src/features/app/app.selectors.ts
- applications/fishing-map/src/features/i18n/i18nDate.tsx
- applications/fishing-map/src/features/map/controls/MapInfo.tsx
- applications/fishing-map/src/features/workspace/workspace.slice.ts
- packages/api-types/src/workspaces.ts
from ugly `${userId}-${Date.now()}` to shiny `from_${start}_to_${end}_near_${your-area}` ✨ workspaces names
> use ocean-areas library to create user friendly workspace names

- applications/fishing-map/src/features/workspace/heatmaps/HeatmapFilters.tsx
- applications/fishing-map/src/features/workspace/heatmaps/HeatmapLayerPanel.tsx
- applications/fishing-map/src/features/workspace/heatmaps/heatmaps.utils.ts
Using same logic that https://github.com/GlobalFishingWatch/frontend/pull/251 to include Fleet filter when VMS Peru source is selected.
There is only a small change when any of the sources has the filter available the selector won't appear
> support fleet filters

- applications/vessel-history/src/data/constants.ts
- applications/vessel-history/src/features/vessel-list-item/VesselListItem.test.tsx
- applications/vessel-history/src/features/vessel-list-item/VesselListItem.tsx
- applications/vessel-history/src/features/vessel-list-item/__snapshots__/VesselListItem.test.tsx.snap
- applications/vessel-history/src/types/index.ts
- applications/vessel-history/src/utils/vessel.test.tsx
- applications/vessel-history/src/utils/vessel.ts
JIra: [VH-69](https://globalfishingwatch.atlassian.net/browse/VH-69)
- Display Source on every vessel result only in environments others than production
- Including unit tests for this new feature
> VH-69 Added SourceAPI to display TMT,GFW in development

- .changeset/khaki-planes-reflect.md
- packages/timebar/src/charts/stacked-activity.js
- packages/timebar/src/charts/utils/index.js
Changes the way we allocate space to tracks 
and adds padding to the stacked-activity graph
> Fishingmap tweak timebar visualisation

- applications/vessel-history/package.json
Given that the package.json has not been updated and there's a new version of ui-components, vessel-history continues using the old (cached) version of the component during the build.
- Update vessel-history to use latest ui-components version
> Update vessel-history to use latest ui-components version

- applications/fishing-map/package.json
Setup tests: [To fix issue when running in CI ](https://github.com/GlobalFishingWatch/frontend/pull/343#issuecomment-787495784)
```
SyntaxError: Unexpected token 'export'
Step #1: 
Step #1:       1 | import { AsyncThunkAction, Dispatch } from '@reduxjs/toolkit'
Step #1:     > 2 | import GFWAPI from '@globalfishingwatch/api-client'
Step #1:         | ^
```
> Setup babel-jest for tests

- applications/vessel-history/package.json
- applications/vessel-history/src/features/profile/components/InfoFieldHistory.tsx
- packages/dataviews-client/package.json
- Updated `api-types` version on `vessel-history` and `dataviews-client`
- Cleanup unused import
> Bump api types dependencies

- applications/vessel-history/src/features/profile/Profile.tsx
- applications/vessel-history/src/features/profile/components/InfoField.tsx
- When there is only one value in the history, switch the “+1 …” for the date (e.g. “Since Jan 2018") in the same place and with the same style
> VH-95 Improvements displaying historical TMT Fields

- .changeset/lovely-cows-swim.md
- packages/layer-composer/src/generators/heatmap/config.ts
- packages/layer-composer/src/generators/heatmap/util/get-legends.ts
- packages/layer-composer/src/generators/types.ts
- packages/ui-components/src/map-legend/ColorRamp.tsx
Changes the color scales so that when only one activity sublayer is in the workspace, color scales goes to white beyond fully saturated hue (number of buckets stays the same at 8).
Also fixed a bug that showed slightly wrong colors in legend.
https://user-images.githubusercontent.com/1583415/116089691-650a8380-a6a3-11eb-91dd-0031999e9fcb.mov
> added color scales to white and fixed legend

- .changeset/little-rocks-approve.md
- .changeset/rotten-keys-refuse.md
- .changeset/twelve-shrimps-drum.md
- applications/fishing-map/public/locales/en/translations.json
- applications/fishing-map/public/locales/source/translations.json
- applications/fishing-map/src/data/config.ts
- applications/fishing-map/src/data/default-workspaces/workspace.development.ts
- applications/fishing-map/src/data/default-workspaces/workspace.production.ts
- applications/fishing-map/src/data/workspaces.ts
- applications/fishing-map/src/features/app/app.selectors.ts
- applications/fishing-map/src/features/dataviews/dataviews.mock.ts
- applications/fishing-map/src/features/dataviews/dataviews.selectors.ts
- applications/fishing-map/src/features/map/popups/HeatmapLayers.tsx
- applications/fishing-map/src/features/map/popups/Popup.module.css
- applications/fishing-map/src/features/map/popups/PopupWrapper.tsx
- applications/fishing-map/src/features/workspace/heatmaps/HeatmapsSection.tsx
- applications/fishing-map/src/features/workspace/heatmaps/heatmaps.utils.ts
- applications/fishing-map/src/features/workspace/workspace.slice.ts
- applications/fishing-map/src/routes/routes.selectors.ts
- applications/fishing-map/src/types/index.ts
- packages/api-types/src/dataviews.ts
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
- packages/ui-components/src/choice/Choice.tsx
Using <Choice /> component to toggle between fishing and presence layers with new dataviews categories: `fishing` and `presence`
https://user-images.githubusercontent.com/10500650/117045687-1480cf00-ad10-11eb-8b63-4e15d6fd144c.mp4
Also disables presence layer interaction on vessel click.
Blocked by https://github.com/GlobalFishingWatch/api-datasets/pull/25 to remove dataseis mock before merging
Pending:
> Fishing map/presence choice

- .changeset/long-melons-do.md
- applications/fishing-map/src/features/datasets/DatasetFile.tsx
- applications/fishing-map/src/features/datasets/DatasetTypeSelect.tsx
- applications/fishing-map/src/features/datasets/NewDataset.tsx
- applications/fishing-map/src/features/datasets/datasets.hook.ts
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/heatmap/config.ts
- packages/layer-composer/src/generators/heatmap/util/colors.ts
- packages/layer-composer/src/generators/index.ts
- packages/layer-composer/src/generators/user-context/user-context.ts
- packages/layer-composer/src/index.ts
- packages/layer-composer/src/types/index.ts
Critical fixes:
- fixed an issue where env polygon layers could not be added to workspaces
- fixed an issue where env polygon layers with 'color by value' option would break map style 
- fixed an issue where context poly layers accepted could not be uploaded
- fixed an issue where context poly layers accepted wrong file type
Other fixes:
- made 'color by value' field mandatory with env polygon layers
- fixed z-order issue with env polygon layers (https://globalfishingwatch.atlassian.net/browse/MR-245)
> Fishing map/custom layer fixes

- applications/fishing-map/src/features/map/Map.tsx
- applications/fishing-map/src/features/map/MapScreenshot.tsx
- applications/fishing-map/src/features/map/map-features.hooks.ts
- applications/fishing-map/src/features/map/map.hooks.ts
Using multiple checks 
```
mapInstanceReady && mapFirstLoad && (idle || areTilesLoaded || mapStyleLoad
```
to ensure the map is loaded instead of checking by source because the source events are not reliable enough and we have a lot of errors with the timebar and the analysis
> use entire mapLoaded instead of sourcesLoaded to ensure reliability

- .changeset/strange-carrots-fetch.md
- applications/fishing-map/src/features/app/ErrorBoundary.tsx
- packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
- packages/layer-composer/src/generators/heatmap/util/fetch-breaks.ts
> Breaks review

- applications/fishing-map/src/features/analysis/Analysis.tsx
- applications/fishing-map/src/features/analysis/AnalysisItem.tsx
- applications/fishing-map/src/features/analysis/AnalysisItemGraph.tsx
- applications/fishing-map/src/features/app/app.selectors.ts
- applications/fishing-map/src/features/map/map.hooks.ts
- applications/fishing-map/src/features/map/map.selectors.ts
- applications/fishing-map/src/features/map/map.slice.ts
- applications/fishing-map/src/features/map/popups/TileClusterLayers.tsx
- applications/fishing-map/src/features/sidebar/SidebarHeader.tsx
- applications/fishing-map/src/features/timebar/Timebar.tsx
- applications/fishing-map/src/features/timebar/timebar.hooks.ts
- applications/fishing-map/src/features/timebar/timebar.slice.ts
- applications/fishing-map/src/features/workspace/common/FitBounds.tsx
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
- packages/layer-composer/src/generators/types.ts
- fixes spamming the 4w API when expanding timeline delta
- deprecates use of staticTime in both app and generator and move time to its own atom
> Fishing map/refacto cleanup of staticTime

- .changeset/sixty-buses-smash.md
- applications/fishing-map/src/features/timebar/TimebarActivityGraph.tsx
- packages/timebar/src/components/playback.js
- do not allow playback in the future (https://globalfishingwatch.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=MR&modal=detail&selectedIssue=MR-283)
- skip graph render timeout and render immediately on idle
> Fishing map/more timebar fixes

- applications/fishing-map/src/features/analysis/Analysis.module.css
- applications/fishing-map/src/features/analysis/Analysis.tsx
- applications/fishing-map/src/features/timebar/TimebarActivityGraph.tsx
- applications/fishing-map/src/features/timebar/TimebarActivityGraph.worker.ts
Avoid UI lock:
- move calculation needed to render the timebar graph to a worker
- increased debounce delays
> Fishing map/timebar graph worker

- .changeset/nasty-ants-shout.md
- applications/fishing-map/src/features/map/Map.tsx
- applications/fishing-map/src/features/map/map.hooks.ts
- applications/fishing-map/src/features/map/map.slice.ts
- applications/fishing-map/src/features/map/popups/HeatmapLayers.tsx
- applications/fishing-map/src/features/map/popups/Popup.module.css
- packages/fourwings-aggregate/test/test.mjs
- packages/layer-composer/src/generators/heatmap/modes/gridded.ts
- packages/layer-composer/src/generators/heatmap/util/time-chunks.ts
- packages/react-hooks/src/use-map-interaction/index.ts
- packages/react-hooks/src/use-map-interaction/use-map-interaction.ts
This is a fix for https://globalfishingwatch.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=MR&modal=detail&selectedIssue=MR-314
Here's the problem as I explained it to Raul:
Tile 8/68/122 con interval 10days, celda 3534, el tile tiene:
`[..., 3534,1815,1815,100, ...]`
O sea: un solo valor en la frame 1815.
El start del timebar es 17 de septiembre.
Yo calculo hago una conversion de la fecha en frame para saber si mostrar la frame o no, asi:
`Math.floor(timestampMs / 1000 / 60 / 60 / 24 / 10)`
Lo que me devuelve exactemente 1815, con lo cual la celda se puede ver en el mapa, pero al llamar la API se manda el start **del timebar** (17 de septiembre), no **el start del periodo de 10 dias que corresponde a la frame 1815**, es decir 11 de septiembre.
This PR implements a fix …
> Fishing map/4wings filter precision

- .changeset/quiet-mugs-boil.md
- applications/fishing-map/src/features/map/map.slice.ts
- applications/fishing-map/src/features/map/popups/HeatmapLayers.tsx
- packages/layer-composer/src/generators/heatmap/util/time-chunks.ts
- packages/react-hooks/src/use-map-interaction/index.ts
- packages/react-hooks/src/use-map-interaction/use-map-interaction.ts
- fixes an issue where the last frame was missing in both map and popup
- delta is now calculated using `ceil` for time range end, which can result in another extra frame queried
> fixed issue with 4w time range + more greedy

- .changeset/violet-games-drum.md
- applications/fishing-map/src/features/map/map.hooks.ts
- applications/fishing-map/src/features/map/map.slice.ts
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/types.ts
- packages/react-hooks/src/use-map-interaction/index.ts
- packages/react-hooks/src/use-map-interaction/use-map-interaction.ts
- merged code to prepare fishing and viirs interaction endpoints, only viirs is an array of one
- pass `dataset.config.type` to sublayer metadata in order to determine type of endpoint to call, rather than using`temporalgrid.sublayerId.startsWith` which seem unreliable to me
- some more fluff
> fetch viirs interaction technical refactos

- .changeset/blue-parrots-accept.md
- packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
- packages/layer-composer/src/generators/heatmap/util/time-chunks.ts
This is a fix to bug introduced in https://github.com/GlobalFishingWatch/frontend/commit/8d73b5205645965caa61c3443cbba4d9d8bef38d
Which resulted in integer delta between start/end varying between eg 311 and 312. 
Now integer start is computed, then integer delta, then integer end - which result in end being effectively the result of `round`, not `ceil`
> fixed instable delta time

- applications/fishing-map/src/data/config.ts
- applications/fishing-map/src/features/timebar/Timebar.tsx
- packages/timebar/src/components/timeline.js
- packages/timebar/src/components/timerange-selector.js
- packages/timebar/src/timebar.js
- packages/timebar/src/utils/index.js
- packages/timebar/types/components/timeline.d.ts
- packages/timebar/types/components/timerange-selector.d.ts
- packages/timebar/types/timebar.d.ts
- packages/timebar/types/utils/index.d.ts
Allows changing 'last 30 days' button behavior in both time range modal and button in timebar, so that lats 30 days can be counted from another date than 'today'. In fishing-map's case, last 30 days from availability of data (today minus 3 days)
Related to https://globalfishingwatch.atlassian.net/browse/MR-240
> last 30 days buttons behavior change

- .changeset/stale-hounds-search.md
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/vessel-events/vessel-events.ts
- packages/layer-composer/src/generators/vessel-events/vessel-events.utils.ts
Fix for Enrique's comment:
> one question about fishing event performance, I'm looking into this workspace. When I'm at the zoom level where the fishing events become part of the track the map became really unresponsive to me
This is due to merging all events datasets in https://github.com/GlobalFishingWatch/frontend/compare/fishing-map/fix-perf-issue-on-track-events-hover?expand=1#diff-f9708754c8ace51fecd0d6922da43e4dfa2044b5729a1f605a99b98043104df7R130, which generates a new array for events every time generators are reinstanciated. Fix is a semi-hack where the generator uses a custome memoizeOne equality check.
This is a bit unsatisfying and reveals larger underlying issues that we should look at fixing post-release:
- `getVesselEventsSegmentsGeojson` is very slow, around two seconds - …
> Fix perf issue on track events hover

- .changeset/poor-fans-trade.md
- applications/fishing-map/public/locales/source/translations.json
- applications/fishing-map/src/features/datasets/DatasetFile.tsx
- applications/fishing-map/src/features/map/popups/EnvironmentLayers.tsx
- applications/fishing-map/src/features/map/popups/FishingLayers.tsx
- applications/fishing-map/src/features/map/popups/PresenceLayers.tsx
- applications/fishing-map/src/features/map/popups/ViirsLayers.tsx
- packages/react-hooks/src/use-map-interaction/index.ts
- packages/react-hooks/src/use-map-interaction/use-map-interaction.ts
Allows specifying units by sublayer, not using the same for the whole AnimatedHeatmap.
This is the only interesting thing https://github.com/GlobalFishingWatch/frontend/pull/675/files#diff-da964bda90275d1e502b46a7f6f87331584e044ed5ed6844731a05bc6dec8b7aR104
Fixes MAP-443 https://globalfishingwatch.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=MAP-443&assignee=5f1f29eea1648700150d0631&assignee=5f1f2a4ecdb7b4001bb074e5
> Fixes popup units

- applications/fishing-map/public/locales/source/translations.json
- applications/fishing-map/src/features/timebar/TimebarSettings.tsx
Display fishing or presence in timebar settings labels (radio and tooltip) depending on current selection
> timebar settings adapt to fishing/presence

- applications/fishing-map/src/routes/routes.ts
This reduces URL length by approx 30% on a typical workspace with tracks. It detects repeated tokens, stores them apart in the URL, and replaces them with a prefix + index (so something like `~42`).
Not 100% sure about using `~` as token prefix. But it looks like a nice little wave 🌊
Also, we might want to add unit tests and/or double check a lot of workspaces before pushing that to prod a few days before release.
Example URL (see `tk` values at the end):
> ```?latitude=1.1958885602302823e-12&longitude=-37&zoom=1.3575518912508981&start=2021-04-09T00%3A00%3A00.000Z&end=2021-07-09T00%3A00%3A00.000Z&dvIn[0][id]=vessel-~2&dvIn[0][dvId]=92&dvIn[0][cfg][color]=%2367FBFE&dvIn[0][dsC][0][dsId]=~0&dvIn[0][dsC][0][pms][0][id]=~1&dvIn[0][dsC][0][pms][0][value]=~2&dvIn[0][dsC][0][ept]=~3&dvIn[0][dsC][ …
```
> Tokenize urls

- .changeset/metal-dryers-warn.md
- applications/fishing-map/src/features/map/popups/Popup.module.css
- applications/fishing-map/src/features/timebar/timebar.selectors.ts
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/types.ts
- packages/layer-composer/src/generators/vessel-events/vessel-events.ts
- packages/layer-composer/src/generators/vessel-events/vessel-events.utils.ts
Include new config in vessel dataview called `showAuthorizationStatus` to allow hiding the authorisation status in events layer and timebar. [Thread](https://globalfishingwatch.slack.com/archives/C0149CPE97U/p1626186020287800)
> support showAuthorizationStatus dataview config in encounter events

- applications/fishing-map/CHANGELOG.md
- applications/fishing-map/package.json
- applications/fishing-map/src/features/timebar/Timebar.tsx
- applications/temporalgrid-demo/CHANGELOG.md
- applications/temporalgrid-demo/package.json
- packages/timebar/CHANGELOG.md
- packages/timebar/package.json
- packages/timebar/src/timebar.js
- packages/timebar/types/timebar.d.ts
> MAP-456 Accept timebar locale prop

- .changeset/silver-planets-train.md
- applications/fishing-map/src/features/datasets/NewDataset.tsx
- packages/dataviews-client/src/resolve-dataviews-generators.ts
- packages/layer-composer/src/generators/types.ts
- packages/layer-composer/src/generators/user-context/user-context.ts
Fix for https://globalfishingwatch.atlassian.net/browse/MAP-455
This will disable interaction on user-submitted context layers, whenever the geojson or shapefile does not contain only polygons or multipolygons.
> Handle user context layers with line features

- applications/fishing-map/src/features/timebar/Timebar.tsx
- applications/fishing-map/src/features/timebar/timebar.selectors.ts
- synchronize tracks and tracks events display (wait for both to be loaded for each track) to avoid weird offsets
- fixed an issue where tracks would not appear again when graph not set to 'none' and added more than one track
- only show graph when there's only one track, not two
> various timebar fixes

- .changeset/wet-adults-drop.md
- applications/fishing-map/src/features/timebar/Timebar.tsx
- packages/layer-composer/src/generators/vessel-events/vessel-events.ts
- packages/timebar/src/charts/tracks-events.module.css
Shows a border around hovered event
and zooms in when clicking on the event on the timebar
> Fishing map/improve vessel events highlight

- applications/fishing-map/src/features/datasets/datasets.utils.ts
- applications/fishing-map/src/features/search/search.selectors.ts
- applications/fishing-map/src/features/workspace/workspace.slice.ts
Steps to reproduce issue:
1. Go to advance search and see only the datasets available for the current workspace:
2. Go to user panel (this will fetch all the datasets you have access)
3. Go back to search panel and now all the search datasets appears (soon it won't as PR fixes it)
This is normally an issue only for admin user which can read every dataset... but could happen for regular users too
> filter search options with only datasets from workspace

- applications/vessel-history/src/features/dataviews/dataviews.selectors.ts
- applications/vessel-history/src/features/dataviews/dataviews.utils.ts
- applications/vessel-history/src/features/map/Map.tsx
- applications/vessel-history/src/features/map/info/Info.tsx
- applications/vessel-history/src/features/map/map.selectors.ts
- applications/vessel-history/src/features/map/map.slice.ts
- applications/vessel-history/src/features/profile/components/activity/Activity.tsx
- applications/vessel-history/src/features/vessels/activity/vessels-activity.selectors.ts
Fixed missing params in events request to get:
Added placeholder when no events results in the current filter selection
TODO:
> Vessel viewer/fix events request

- applications/vessel-history/src/features/vessel-list-item/VesselListItem.test.tsx
- applications/vessel-history/src/features/vessel-list-item/__snapshots__/VesselListItem.test.tsx.snap
updated snapshots to validate vessel source with new values `AIS+Other` instead of `GFW+TMT`
> Fixed failing tests with old vessel source values (GFW+TMT)

- .changeset/wild-hornets-itch.md
- applications/fishing-map/public/locales/en/translations.json
- applications/fishing-map/public/locales/source/translations.json
- applications/fishing-map/src/data/config.ts
- applications/fishing-map/src/features/dataviews/dataviews.mock.ts
- applications/fishing-map/src/features/workspace/vessels/VesselEventsLegend.tsx
- applications/fishing-map/src/features/workspace/vessels/VesselSection.module.css
- packages/api-types/src/dataviews.ts
Include port events with confidence 4
Configuration required:
- Updated `public-global-fishing-effort:v20201001` dataset to include `public-global-port-visits-c2-events:v20201001` as realtedDataset
- Updated vesselDataview datasetsConfig with:
```json
{
"query": [
{
"id": "vessels",
"value": ""
},
{
"id": "summary",
"value": true
},
{
"id": "confidences",
"value": 4
}
],
"params": [],
"endpoint": "carriers-events",
"datasetId": "public-global-port-visits-c2-events:v20201001"
}
```
> Fishing map/port events

- applications/vessel-history/src/features/vessels/voyages/voyages.hook.ts
Fixes [VV-201](https://globalfishingwatch.atlassian.net/browse/VV-201) rendering the events which are out of the voyage
> Vessel viewer/show events out of voyages

- applications/vessel-history/src/App.tsx
- applications/vessel-history/src/features/app/analytics.hooks.ts
- applications/vessel-history/src/features/home/Home.tsx
- applications/vessel-history/src/features/search/AdvancedSearch.tsx
- applications/vessel-history/src/features/search/search.hooks.ts
- applications/vessel-history/src/features/search/search.thunk.ts
- applications/vessel-history/src/features/user/user.hooks.ts
- applications/vessel-history/src/features/user/user.slice.ts
- applications/vessel-history/src/store.ts
https://globalfishingwatch.atlassian.net/browse/VV-239
> VV-239 Refresh token automatically

- applications/fishing-map/src/features/i18n/i18n.ts
- applications/vessel-history/src/features/i18n/i18n.ts
As we need to publish the package for the definition types, makes more sense to have the same source of truth.
This PR replaces GitHub raw files for jsDelivery cdn to consume locales.
> use npm cdn to fetch locales

- packages/layer-composer/src/generators/heatmap/util/time-chunks.ts
Size of day tilesets: ~30% of original size
> smaller time chunks

- applications/fishing-map/src/features/analysis/analysis.hooks.ts
- packages/layer-composer/src/generators/heatmap/util/get-legends.ts
- keep time compare params when switching analysis mode
- automatically set base compare time when changing duration to avoid overlap in comparison periods
- change zoom-based factor to better adapt color scale to time compare mode
Before
After
> Fishing map/time compare UI fixes

- apps/fishing-map/features/download/downloadActivity.slice.ts
https://globalfishingwatch.atlassian.net/browse/MAP-624
> Download data from a custom polygon - zip includes undefined and name is not displayed in the pop up

- apps/fishing-map/features/download/DownloadActivityModal.tsx
- apps/fishing-map/features/download/downloadActivity.slice.ts
- libs/layer-composer/src/generators/index.ts
Request all activity datasets download in one single request to
- simplify the slice reducer request status
- save all files in the same zip file
> request report for all datasets in 1 request

- apps/fishing-map/features/datasets/datasets.utils.ts
- apps/fishing-map/features/search/SearchFilters.tsx
- apps/fishing-map/features/workspace/activity/ActivityFilters.tsx
- apps/fishing-map/features/workspace/activity/ActivitySchemaFilter.tsx
- Remove fixed filters ids to use fieldsAllowed from dataset to render filters
- Support sorting by dataset.config.fieldsOrder
- Support conditional rendering for filters based on [configuration](https://github.com/GlobalFishingWatch/frontend/compare/fishing-map/activity-filters?expand=1#diff-98ce0532eaaa9234e44e8380f15e942ae62e981698a6a4f6e67add3c292c9b85R49)
- Use same workflow for flags with some workarounds to allow sorting
https://user-images.githubusercontent.com/10500650/158187918-89cfeb7e-7984-40a7-9e7c-07d07bd89c6f.mp4
> Fishing map/activity filters

- apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
- apps/fishing-map/features/workspace/activity/ActivitySection.tsx
- apps/fishing-map/queries/base.ts
- apps/fishing-map/queries/stats-api.ts
- apps/fishing-map/store.ts
Compare traditional redux-toolkit slice approach against [react-toolkit-query](https://redux-toolkit.js.org/rtk-query/overview) method to fetch layer stats. 
It needs a custom [baseQuery](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#customizing-queries-with-basequery), see [code](https://github.com/GlobalFishingWatch/frontend/compare/fishing-map/activity-layer-stats...fishing-map/activity-layer-stats-rtk-query?expand=1#diff-aaef2cbeabe68e04bfa31d060c708e24c9e5579d76eb85114f6bc8c650413b43R4) but works nice
Apart of having less code boilerplate the main advantage vs the [previous approach](https://github.com/GlobalFishingWatch/frontend/pull/1274) is each request is done individually getting an automatic cache layer effortless and works great because this means changing a …
> Fishing map/activity layer stats rtk query

- libs/layer-composer/src/generators/vessel-events/vessel-events-shapes.ts
Updates event highlight style
- Event shapes: 
- [Encounter](https://github.com/GlobalFishingWatch/map-gl-sprites/commit/6892efe1baecb18889ed8c13b543033f7f31bde9) and [loitering](https://github.com/GlobalFishingWatch/map-gl-sprites/commit/7c8d543e6d22d75e3fa61c45d32afa11bf0b0b9f) highlight sprite
> update event shapes highlight style

- apps/fishing-map/features/resources/resources.utils.ts
- apps/fishing-map/features/timebar/TimebarSettings.module.css
- apps/fishing-map/features/timebar/timebar.selectors.ts
- apps/fishing-map/features/workspace/vessels/VesselEventsLegend.module.css
- libs/dataviews-client/src/resolve-dataviews-generators.ts
- libs/timebar/src/charts/tracks-events.module.css
- libs/timebar/src/charts/tracks-events.tsx
Small superficial fixes and one critical: https://github.com/GlobalFishingWatch/frontend/pull/1392/commits/039ae714ad20b15bf0d087a7a3e19ecd5ffa671a
Graph data was supposed to follow track data structure, but since tracks now comes as chunks, the base track data was wrong, which led to graph data being completely off. Now when calling the tracks API for graph data, timestamps are requested as well, so that graph data is now built independently of track data.
> Timebar fixes

- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/map/map.hooks.ts
- libs/layer-composer/src/generators/polygons/polygons.ts
- libs/layer-composer/src/generators/types.ts
- I don't think we need another param in the generator config for `loaded` because we can already handle the opacity at the [app level](https://github.com/GlobalFishingWatch/frontend/pull/1413/files#diff-36b02ca52df9696dd5bf7a310036c24a3f7a6890c3fee29e951f42cd99bb3af8R39)
- I also think adding an extra parameter for the hook is unnecessary because adds complexity and we can read the source status by id using the existing `useMapSourceTiles` [hook](https://github.com/GlobalFishingWatch/frontend/pull/1413/files#diff-224a0a8337cd448587a358158edf27b37fe7a1b5d58f6f4e1f8000af706c3ff2R81)
> simplify generator and hook

- libs/api-types/src/dataviews.ts
- libs/dataviews-client/src/resolve-dataviews-generators.ts
- Enable maxZoom on heatmap animated dataviews so that 4wing tiles beyond that zoom level are not requested and loaded.
https://user-images.githubusercontent.com/2205831/170121175-8f3bbe51-a029-4f3b-b56d-4099b0156661.mp4
> Limit zoom level on animated heatmap layers. MAP-797

- apps/fishing-map/features/datasets/datasets.utils.ts
- libs/api-types/src/dataviews.ts
This PR updates the needed configuration in dataviews to normalise the structure to be ready for the terraform migration:
show_icons
show_authorization_status
points_to_segments_switch_level
> Dataviews normalization

- apps/fishing-map/features/datasets/NewDataset.tsx
- apps/fishing-map/public/locales/source/translations.json
- Lets errors coming from parsing shapefiles, csvs and Geojsons show up in the error box
- Detects whether zipped shapefiles contains all required files - need to merge first https://github.com/calvinmetcalf/shapefile-js/pull/181
> File upload improve error handling

- apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
- apps/fishing-map/queries/stats-api.ts
Requires updating the 'statsHelp' and 'statsHelpDetection' keys on CrowdIn so that tooltips say "time range up to 1 year".
> Display activity layer stats only when time range is less than 1 year

- apps/fishing-map/features/map/map.slice.ts
- libs/api-types/src/vessel.ts
In instances like [this sar detection](http://localhost:3003/?latitude=69.8994943608468&longitude=19.996655542591952&zoom=10.335549728181997&start=2022-04-23T00%3A00%3A00.000Z&end=2022-04-24T00%3A00%3A00.000Z&dvIn[0][id]=vessel-~1&dvIn[0][dvId]=92&dvIn[0][cfg][clr]=%23F95E5E&dvIn[0][dsC][0][dsId]=private-global-other-vessels%3Av20201001&dvIn[0][dsC][0][pms][0][id]=~0&dvIn[0][dsC][0][pms][0][val]=~1&dvIn[0][dsC][0][ept]=~2&dvIn[0][dsC][1][dsId]=private-global-presence-tracks%3Av20201001&dvIn[0][dsC][1][pms][0][id]=~0&dvIn[0][dsC][1][pms][0][val]=~1&dvIn[0][dsC][1][ept]=tracks&dvIn[0][dsC][2][dsId]=public-global-loitering-events%3Av20201001&dvIn[0][dsC][2][qry][0][id]=~3&dvIn[0][dsC][2][qry][0][val]=~1&dvIn[0][dsC][2][ept]=~4&dvIn[0][dsC][3][dsId]=public-global-port-visits-c2-events%3Av20201 …
> Fishing map/choose right dataset based on vessel year

- apps/fishing-map/features/download/DownloadActivityModal.tsx
- apps/fishing-map/features/search/Search.tsx
- apps/fishing-map/features/user/User.tsx
- apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx
- apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
> Vessel groups polish

- apps/fishing-map/features/sidebar/Sidebar.tsx
- apps/fishing-map/features/user/User.tsx
- apps/fishing-map/features/user/user.selectors.ts
- apps/fishing-map/features/vessel-groups/vessel-groups.selectors.ts
- libs/api-types/src/user.ts
Show the vessel group features by checking the `vessel-group` permission instead of belonging to a particular user group.
> allow vessel groups feature from permissions instead of user group

- apps/vessel-history/package.json
- yarn.lock
@globalfishingwatchapp/vessel-history@1.1.3
- [#1672](https://github.com/GlobalFishingWatch/frontend/pull/1672): Fixed removing offline vessel does not update in the list. VV-491
**Full Changelog**: https://github.com/GlobalFishingWatch/frontend/compare/@globalfishingwatchapp/vessel-history@1.1.2...@globalfishingwatchapp/vessel-history@1.1.3
> 🚀 Release - Vessel Viewer v1.1.3

- apps/fishing-map/features/map/map.selectors.ts
- apps/fishing-map/features/workspace/shared/DatasetSchemaField.tsx
Frontend ready to support vessel groups without date range limit of 31 days.
Pending to do in the API as it returns this validation error:
```{"statusCode":422,"error":"Unprocessable Entity","messages":[{"title":"vessel-groups","detail":"Maximum 1 year of time range with vessel groups filter  "}]}```
> remove vessel groups timerange limit

- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/map/map-sources.utils.ts
- apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts
- apps/fishing-map/features/workspace/events/EventsLayerPanel.tsx
- apps/fishing-map/features/workspace/events/events.hooks.ts
- libs/data-transforms/src/features/filter-features-by-bounds.ts
- libs/dataviews-client/src/resolve-dataviews-generators.ts
- libs/layer-composer/src/generators/index.ts
- libs/layer-composer/src/generators/tile-cluster/config.ts
- libs/layer-composer/src/generators/tile-cluster/tile-cluster.ts
- libs/layer-composer/src/generators/types.ts
- libs/layer-composer/src/types/index.ts
Following the same concept than dynamic ramps for environmental layers. This PR generates breaks for the cluster radius size. [Workspace URL to test](https://fishing-map-fishing-map-clusters-dynamic-ramps-jzzp2ui3wq-uc.a.run.app/map/fishing-activity/testing_events_dynamic_ramp-public?dvIn[0][id]=bq-events-1665487988441&dvIn[0][cfg][breaks][0]=2&dvIn[0][cfg][breaks][1]=544&dvIn[0][cfg][breaks][2]=2022)
> Fishing map/clusters dynamic ramps

- libs/layer-composer/src/generators/heatmap/modes/gridded.ts
Fix env layers filters generating wrong expression in mapbox when not needed
> apply env layer filtering only when needed

- apps/fishing-map/features/hints/HelpHub.tsx
- apps/fishing-map/features/workspace/activity/ActivityFilters.tsx
- apps/fishing-map/features/workspace/environmental/EnvironmentalLayerPanel.tsx
- apps/fishing-map/features/workspace/environmental/HistogramRangeFilter.tsx
- apps/fishing-map/public/locales/source/translations.json
Follow the same workflow for histogram filter in  global environmental layers:
As the histogram sometimes takes some time to render this uses [useTransition](https://reactjs.org/docs/hooks-reference.html#usetransition) to add an loading spinner in the icon while rendering
> move histogram filter to activity filters

- apps/api-portal/package.json
- apps/deck-playground/package.json
- apps/fishing-map/package.json
- apps/fourwings-explorer/package.json
- apps/port-labeler/package.json
- apps/user-groups-admin/package.json
- tools/generators/app/files/package.json__tmpl__
- tools/generators/minisite/files/package.json__tmpl__
- yarn.lock
* Sync `eslint-plugin-react` versions to fix this error
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
Executing ~/.huskyrc
yarn run v1.22.17
$ ./frontend/node_modules/.bin/lint-staged
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] package.json — 141 files
[STARTED] *.{js,jsx,ts,tsx} — 72 files
[STARTED] *.{css, scss} — 3 files
[STARTED] eslint -c ./.eslintrc.js --fix
[STARTED] prettier --write
[SUCCESS] prettier --write
[STARTED] stylelint --fix
[SUCCESS] stylelint --fix
[SUCCESS] *.{css, scss} — 3 files
[FAILED] eslint -c ./.eslintrc.js --fix [FAILED]
[FAILED] eslint -c ./.eslintrc.js --fix [FAILED]
[SUCCESS] Running tasks for staged files...
[STARTED] Applying modifications …
```
> Fixed ESLint couldn't determine the plugin "react" uniquely.

- apps/vessel-history/features/regions/regions.slice.ts
Looks like the `public-rfmo` dataset is not ready for production yet, so this PR uses the legacy dataset until we have it ready.
Also took advantage of the change to make this faster requesting the 3 areas in parallel, please @rdgfuentes take a look at this later as I'm going to merge this to get the bug fixed asap.
> request areas in parallel and fix dataset id in production

- apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx
- apps/fishing-map/features/vessel-groups/VesselGroupModalVessels.tsx
- apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts
To avoid errors with large urls when retrieving a lot of vessels included in a vessel group this PR uses the new vessel-groups param in search vessels endpoint to fetch all the vessels info.
> fetch vessel groups by group id

- libs/layer-composer/src/generators/heatmap/util/get-time-chunks-interval.ts
- libs/layer-composer/src/generators/heatmap/util/time-chunks.ts
Fix analysis crash as was using interval `year` when no supported
> fix fallback option when omited datasets

- libs/api-client/src/api-client.ts
Update api-client to match [new refreshToken policy](https://globalfishingwatch.atlassian.net/browse/API-461)
> use new refreshToken after updating

- apps/fishing-map/features/datasets/NewDataset.tsx
- apps/fishing-map/features/datasets/datasets.utils.ts
- apps/fishing-map/features/map/map.draw.utils.ts
- apps/fishing-map/features/map/map.hooks.ts
- apps/fishing-map/features/map/popups/ContextLayers.hooks.ts
- apps/fishing-map/features/map/popups/ContextLayers.tsx
- apps/fishing-map/features/timebar/TimebarSettings.tsx
- apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx
- apps/fishing-map/features/workspace/context-areas/ContextAreaSection.tsx
- apps/fishing-map/features/workspace/environmental/EnvironmentalLayerPanel.tsx
- apps/fishing-map/features/workspace/environmental/histogram.hooks.ts
- libs/api-types/src/datasets.ts
- libs/api-types/src/dataviews.ts
- libs/dataviews-client/src/resolve-dataviews-generators.ts
- libs/layer-composer/src/generators/context/config.ts
- libs/layer-composer/src/generators/context/context.ts
- libs/layer-composer/src/generators/types.ts
- libs/layer-composer/src/types/index.ts
- libs/react-hooks/src/use-map-interaction/use-map-interaction.ts
⚠️ Blocked by https://github.com/GlobalFishingWatch/gfw-terraform-api/pull/60
Use the new DatasetType and dataset configuration to render static tiles with:
- `idProperty` as promoteId in mapbox to replace the missing gfw_id
- `valueProperties` as value in the tooltips
> Update context layers with new datasets and endpoints

- libs/dataviews-client/src/resolve-dataviews.ts
Fixes `DataviewInstance id: [xxxx] doesn't have a valid dataview ([number])` as the dataviewId now is a string and needs to be parsed
> fix resolve dataviews with legacy ids

- apps/fishing-map/features/analysis/analysis.hooks.ts
- apps/fishing-map/features/areas/areas.slice.ts
- apps/fishing-map/features/dataviews/dataviews.utils.ts
- apps/fishing-map/features/map/popups/ContextLayers.hooks.ts
- libs/api-types/src/datasets.ts
Fixes [missing area names](https://globalfishingwatch.atlassian.net/browse/MAP-1089) resolving the proper url to fetch area details.
Blocked by https://github.com/GlobalFishingWatch/api-datasets/pull/88
> read endpoint pathTemplate to retrieve context feature

- apps/fishing-map/features/datasets/datasets.utils.ts
- apps/fishing-map/features/workspace/workspace.slice.ts
This fixes GFW Staff sharing workspaces with guests as they include gaps as a related dataset (even if it is not used in the map yet)
> fetch only datasets defined in dataview

- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts
Before:
https://github.com/GlobalFishingWatch/frontend/assets/10500650/5a4795c9-f817-40eb-935d-0cd7388bc159
After:
https://github.com/GlobalFishingWatch/frontend/assets/10500650/28185556-b1dd-41d4-9a06-c4f4c6dce3eb
Extra: the metadata hash is calculated only with the sublayers visible
> recalculate timebar graph on mode change

- apps/fishing-map/features/dataviews/dataviews.slice.ts
- apps/fishing-map/features/dataviews/dataviews.utils.ts
- apps/fishing-map/features/map/popups/TileClusterLayers.tsx
- apps/fishing-map/features/map/popups/VesselsTable.tsx
- apps/fishing-map/features/reports/vessels/ReportVesselsTable.tsx
- apps/fishing-map/features/search/Search.tsx
- libs/api-types/src/dataviews.ts
As we started to have [http errors 431](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431) due a too large URL this PR makes it shorter.
This happens by storing just the raw datasetIds instead of the entire dataviewDatasetConfig and adding them [just before resolving](https://github.com/GlobalFishingWatch/frontend/compare/fishing-map/shorter-vessel-urls?expand=1#diff-1a1503a4e347164a35746c4e098cb27ca8ae3bc8cfdfa12cb989f9c0acfaa3d5R228)
**Comparison with default workspace and same vessel added:**
Link length with the new approach: 754 characters
```
https://fishing-map.dev.globalfishingwatch.org/map/?latitude=19&longitude=26&zoom=1.5&start=2023-03-24T00%3A00%3A00.000Z&end=2023-06-24T00%3A00%3A00.000Z&dvIn[0][id]=4e0e1a6ad-d6ed-d833-4fb3-18c67b0f8f05&dvIn[0][dvId]=fishing-map-vess …
```
> make vessel instances shorter in url

- libs/layer-composer/src/generators/vessel-events/vessel-events-shapes.ts
Use same memoization fn in vessel-events-shapers generator for getVesselEventsSegmentsGeojson
> memoize getVesselEventsSegmentsGeojson

- apps/fishing-map/features/map/map-layers.hooks.ts
- apps/fishing-map/features/timebar/timebar-vessel.hooks.ts
- apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx
- libs/deck-layers/src/layers/vessel/VesselEventsLayer.ts
- libs/deck-layers/src/layers/vessel/VesselLayer.ts
- libs/deck-layers/src/layers/vessel/vessel.hooks.ts
As we need granularity for the status of the data vessel resources this PRs replaces the atom `layersLoaded` property by a new `dataStatus` one. 
This stores an array of `{ type: 'track' | EventType , status: ResourceStatus }` with every layer loaded. [See example of how to get the status](https://github.com/GlobalFishingWatch/frontend/compare/deck-migration/layers-hooks-review...deck-migration/layers-hooks-data-status?expand=1#diff-b6ec3c581e2855592974c9e919dea4bdd64e083a4913c63492a8e13afda7518bR84)
Pending TODO:
- [ ] Handle data loading errors as I couldn't catch the loader error
> save data status by type

- apps/fishing-map/features/dataviews/dataviews.slice.ts
- apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx
Fixes missing track when logged after pinning a vessel without login
> resolve track dataset when available

- apps/fishing-map/.env.sample
- apps/fishing-map/data/config.ts
- apps/fishing-map/features/datasets/datasets.utils.ts
- apps/fishing-map/features/dataviews/dataviews.slice.ts
- apps/fishing-map/features/map/map.selectors.ts
- apps/fishing-map/features/reports/reports.utils.ts
- apps/fishing-map/features/reports/summary/ReportSummaryTags.tsx
- apps/fishing-map/features/sidebar/SidebarHeader.tsx
- apps/fishing-map/features/user/User.tsx
- apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx
- apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts
- apps/fishing-map/features/workspace/Workspace.tsx
- apps/fishing-map/features/workspace/activity/ActivityFilters.tsx
- apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
- apps/fishing-map/features/workspace/activity/ActivitySchemaFilter.tsx
- apps/fishing-map/features/workspace/shared/DatasetSchemaField.tsx
- apps/fishing-map/public/locales/source/translations.json
- apps/fishing-map/queries/stats-api.ts
- apps/fishing-map/routes/routes.selectors.ts
- apps/fishing-map/types/index.ts
- libs/api-types/src/datasets.ts
- libs/dataviews-client/src/resolve-dataviews.ts
- libs/layer-composer/src/generators/user-points/user-points.ts
Cherry-picking https://github.com/GlobalFishingWatch/frontend/pull/2164 to clean unnecessary `as string` validations and fixes:
> Fishing map/vessel groups no limit

- apps/fishing-map/features/app/app.selectors.ts
This PR fixes a bug that gets triggered os stored workspaces created with some `activity`, `detections` or `environment` layer activated. If you try to do a report on that workspace without any of those layers active the `reportCategory` is not coherent with the current categories, messing with map and report selection of the data to display.
[Screencast from 13-09-23 13:29:49.webm](https://github.com/GlobalFishingWatch/frontend/assets/6906348/61d5e72d-036e-46da-b706-d73b8e28789b)
[Screencast from 13-09-23 13:40:24.webm](https://github.com/GlobalFishingWatch/frontend/assets/6906348/e2a77068-7149-4203-9c64-0cd936209126)
> Avoid report category missmatch on stored workspaces

- apps/deck-playground/pages/styles.css
- apps/fishing-map/features/map/Map.module.css
- apps/fishing-map/features/map/MapScreenshot.tsx
- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/map/popups/Popup.module.css
- apps/fishing-map/pages/styles.css
- apps/fourwings-explorer/features/map/popups/Popup.module.css
- apps/fourwings-explorer/pages/styles.css
- apps/port-labeler/pages/styles.css
- apps/real-time-prototype/pages/styles.css
- apps/vessel-history/features/map/popups/Popup.module.css
- libs/layer-composer/package.json
- libs/layer-composer/src/generators/heatmap/modes/gridded.ts
- libs/layer-composer/src/generators/heatmap/util/get-base-layers.ts
- libs/layer-composer/src/generators/user-context/user-context.ts
- libs/layer-composer/src/generators/vessel-events/vessel-events.ts
- libs/react-hooks/package.json
- package.json
- yarn.lock
Update [maplibre fork](https://github.com/GlobalFishingWatch/maplibre-gl-js/pull/8) to [latest version](https://github.com/maplibre/maplibre-gl-js/releases/tag/v3.3.1)
Improvements to test in [this preview url](https://fishing-map-chore-update-maplibre-version-jzzp2ui3wq-uc.a.run.app/map))
- Being on the latest version makes it easier to keep updated in case of bugs
- Better [expression typings](https://github.com/maplibre/maplibre-gl-js/pull/1510)
- Significant improvement in blocking time
Before:
After:
> update maplibre version

- .github/gfw-bot.json
`ui-fishing-map-autodeploy-staging`trigger ready in cloud build but this depends on https://github.com/GlobalFishingWatch/gfw-github-bot/pull/5 to support `deploy-staging` github tag
> add cloudbuildTaskStagingId to gfw-bot

- apps/fishing-map/data/config.ts
- apps/fishing-map/data/default-workspaces/workspace.staging.ts
- apps/fishing-map/features/workspace/highlight-panel/highlight-panel.content.ts
- apps/fishing-map/next.config.js
This avoids publishing [ui-libs-i18n-labels-stable](https://github.com/GlobalFishingWatch/frontend/blob/fishing-map/staging-env/apps/fishing-map/cloudbuild.yaml#L157) on every staging preview trigger
> support staging as WORKSPACE_ENV

- apps/fishing-map/features/map/controls/MapSearch.tsx
- apps/fishing-map/features/workspaces-list/WorkspaceWizard.tsx
- apps/fishing-map/package.json
- apps/vessel-history/package.json
- libs/ui-components/package.json
- libs/ui-components/src/multi-select/MultiSelect.tsx
- package.json
- yarn.lock
Finally fixes the bug where all the multiselect options open at once when running locally by updating downshift
See migration guide to [v7](https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V7.md) and [v8](https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V8.md)
Before:
https://github.com/GlobalFishingWatch/frontend/assets/10500650/cdb3a271-0906-4c59-a794-17e2c1e6213e
After:
https://github.com/GlobalFishingWatch/frontend/assets/10500650/19b9fae4-8204-44d1-af93-00403c4e9fce
> update downshift version

- apps/fishing-map/features/download/downloadActivity.slice.ts
- apps/fishing-map/features/reports/title/ReportTitle.tsx
This PR fixes two small issues. 
-  The first one is related with API v3 updates. [`/v3/4wings/report` ](https://gateway.api.dev.globalfishingwatch.org/swagger?version=3#/4wings/get_v3_4wings_report) endpoint need params to be Uppercase (a `422` was being returned).
- Cleaning feature state on report buffer operation update was caussing the issue of leaving no area highlighted in case the buffer was removed before confirmation.
> Fishing map/v3 integration fixes

- apps/fishing-map/features/reports/title/ReportTitle.tsx
This PR fixes a couple of issues related to buffer state:
- When you open the buffer area tooltip (coming from a saved report) the default values doesn't match the buffer selection
- The area is not clean if you remove it.
Some thinking might be needed on the title creation logic (when the buffer is removed on a saved report with buffer the name of the reports remains the same but the report area is the original one, letting the name kind of out of sync) 
c.c: @satellitestudiodesign
> Fishing map/more buffer params cleanup

- apps/fishing-map/features/dataviews/dataviews.utils.ts
- apps/fishing-map/features/map/map.slice.ts
- apps/fishing-map/features/map/popups/EncounterTooltipRow.tsx
- apps/fishing-map/features/map/popups/VesselsTable.tsx
- apps/fishing-map/features/reports/vessels/ReportVesselsTable.tsx
- apps/fishing-map/features/vessel/VesselLink.tsx
- apps/fishing-map/features/vessel/VesselPin.tsx
- apps/fishing-map/features/vessel/related-vessels/RelatedEncounterVessels.tsx
- apps/fishing-map/features/vessel/related-vessels/RelatedOwnersVessels.tsx
- apps/fishing-map/features/vessel/related-vessels/RelatedVessel.tsx
- apps/fishing-map/features/vessel/vessel.slice.ts
- apps/fishing-map/features/vessel/vessel.utils.ts
- apps/fishing-map/features/workspace/shared/LayerPanel.module.css
- apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx
- apps/fishing-map/public/locales/source/translations.json
To show all the vessel track and events history data, we need to resolve all vessel identities before pinning a vessel to ensure the `relatedVesselIds` are populated into the dataviewInstance.
This is [easily done in the cell interaction](https://github.com/GlobalFishingWatch/frontend/commit/beccc4e1d41f0df4f6e01f72c295c92fe27efa16#diff-315ad2108ff73a49247a0562ce9ba936813e014830808cdbf2d44acb64ff84a3R182) as we already requested the vessel identity to the new API but we only have the `vesselId` in the following cases:
- Encounter layers
- Pinning a vessel from a report
- Related vessels in profile
To keep it as simple and reusable as possible the new <VesselPin /> component will request automatically the vesselIdentity info when passing a `vesselToResolve` prop and include the rest of the …
> Fishing map/all identities data in workspace

- apps/fishing-map/features/map/popups/VesselEventsLayers.tsx
This PR updates the way the `shipname` is resolved on the events popup to handle several identities.
> Ship name on popup

- libs/timebar/src/components/timerange-selector.js
- libs/timebar/src/timebar.js
PR fixing [this bug reported](https://globalfishingwatch.slack.com/archives/C0296TY92KC/p1699396660179769) 👇🏼 
```
User feedback - 17:25 29T 07 November 2023
Details
Timebar is not updating based on the selected start and end date. It seems to always add a few months to both the start and end date set by the user.
Name - Rollan Geronimo
Role - analyst 
```
`dayjs.utc` method is already normalizing month dates (since January is index `0` on months array). So we were adding a `+1` in some cases that were causing date to move month by one (so January would display February). 
There was another issue when handling input values from the `TimerangeSelector` component, we were using the `event.target.value` so January would be mont `1` hence adding another month (since `index` `1` would be …
> Avoid month index mess up

- libs/api-client/project.json
- libs/api-types/project.json
- libs/data-transforms/project.json
- libs/dataviews-client/project.json
- libs/features-aggregate/project.json
- libs/fourwings-aggregate/project.json
- libs/i18n-labels/project.json
- libs/layer-composer/project.json
- libs/ocean-areas/project.json
- libs/pbf-decoders/decoders/4wings-tile.js
- libs/pbf-decoders/decoders/vessels.js
- libs/pbf-decoders/package.json
- libs/pbf-decoders/project.json
- libs/react-hooks/project.json
- libs/timebar/project.json
- libs/ui-components/project.json
While I was testing to build libraries using [swc](https://nx.dev/nx-api/js/executors/swc#nxjsswc) for faster builds I realized the [incremental builds](https://nx.dev/concepts/more-concepts/incremental-builds#when-should-i-use-incremental-builds) are not working right now.
The own app is compiling the dependencies as `transpilePackages` in next so basically we are spending time on building libraries that we are not used.
This PR disables that step until we find a better solution, @weberjavi @rdgfuentes @satellitestudiodesign  could you test the `nx build [app]` works for you too?
> skip unneeded build step

- libs/timebar/src/components/timerange-selector.js
This PR avoids the situation where the user can increment month values on the timerange-selector when the selected year is higher than 2023 (when changing to month interval sometimes the end date is January the first 2024. With this fix, month input would be disabled so user can not select month 12 on year 2024)
> Avoid the chance to increment months on years beyond 2024

- libs/timebar/src/components/timerange-selector.js
This PR brings back the functionality of reseting lower time intervals to one (month and/or day) when an interval change is forced due to range limit between and start and end date is surpased.
[Grabación de pantalla desde 14-11-23 13:19:43.webm](https://github.com/GlobalFishingWatch/frontend/assets/6906348/54b7374e-38b4-41ed-8fba-61c7ca336c31)
> Fishing map/timerange reset to one on disabled

- apps/fishing-map/features/datasets/datasets.utils.ts
- apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
This includes the `neural_vessel_type` filter for the SAR dataset simplifying https://github.com/GlobalFishingWatch/frontend/pull/2386 as is using enums now.
> add neural_vessel_type as filter

- apps/vessel-history/features/map/Map.tsx
- apps/vessel-history/package.json
- [#2417](https://github.com/GlobalFishingWatch/frontend/pull/2417): VV-577. VV Link to VV 2.0 in Map with no fishing effort layer enabled
**Full Changelog**: https://github.com/GlobalFishingWatch/frontend/compare/@globalfishingwatchapp/vessel-history@1.9.0...@globalfishingwatchapp/vessel-history@1.9.1
> 🚀 Release - Vessel Viewer v1.9.1

- apps/fishing-map/data/default-workspaces/workspace.development.ts
- apps/fishing-map/data/layer-library/layers-environment.ts
- apps/fishing-map/data/workspaces.ts
- apps/fishing-map/features/dataviews/dataviews.mock.ts
- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/map/map-sources.utils.ts
- apps/fishing-map/features/map/popups/EnvironmentLayers.tsx
- apps/fishing-map/features/map/popups/PopupWrapper.tsx
- apps/fishing-map/features/workspace/environmental/environmental.hooks.ts
- libs/dataviews-client/src/resolve-dataviews-generators.ts
- libs/layer-composer/src/generators/heatmap/heatmap-static.ts
- libs/layer-composer/src/generators/heatmap/util/get-base-layers.ts
- libs/layer-composer/src/generators/heatmap/util/get-legends.ts
- libs/layer-composer/src/generators/index.ts
- libs/layer-composer/src/generators/types.ts
- libs/layer-composer/src/layer-composer.ts
- libs/layer-composer/src/transforms/sort/sort.ts
- libs/layer-composer/src/types/index.ts
- libs/react-hooks/src/use-map-interaction/index.ts
- libs/react-hooks/src/use-map-interaction/use-map-interaction.ts
- libs/react-hooks/src/use-map-legend/use-map-legend.ts
Renders bathymetry layer using the 4wings `mvt` format to simplify it as much as possible.
TODO:
> Fishing map/static heatmaps

- apps/fishing-map/features/sidebar/CategoryTabs.tsx
This PR avoids the situation in which a pinned vessel is removed from the map when the user performs a new vessel search from the search icon on the sidebar category tabs 👇🏼 
This does not happens when the search is performed from the vessel sidebar panel
> Avoid history replacement on search link click

- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts
- apps/fishing-map/features/workspace/common/LayerFilters.tsx
- apps/fishing-map/features/workspace/common/LayerSchemaFilter.tsx
- apps/fishing-map/features/workspace/environmental/HistogramRangeFilter.tsx
This follows the same strategy to change dataviews filters for the environmental visible values filter instead of changing the dataview [directly](https://github.com/GlobalFishingWatch/frontend/compare/fishing-map/fix-updates-on-env-filters?expand=1#diff-2d75e059e2a7e1370210f762b9ec13e0505962a60af0b26d0f94ac41dad16f6aL37)
> updates environmental filters with same workflow than other filters

- apps/fishing-map/features/datasets/datasets.utils.ts
- apps/fishing-map/features/search/advanced/SearchAdvancedFilters.tsx
- apps/fishing-map/features/search/advanced/advanced-search.utils.ts
- apps/fishing-map/features/search/search.config.selectors.ts
- apps/fishing-map/features/search/search.config.ts
- apps/fishing-map/features/search/search.slice.ts
- apps/fishing-map/types/index.ts
- libs/api-client/src/utils/search.ts
Add missing `nationalId` for Ecuador VMS source:
[Preview url](https://fishing-map-fix-advanced-search-missing-filters-jzzp2ui3wq-uc.a.run.app)
> support filters without schemas in advanced search

- apps/fishing-map/features/workspace/common/MapLegend.tsx
- libs/deck-layer-composer/src/hooks/deck-layers-legends.hooks.ts
- libs/deck-layers/src/layers/fourwings/FourwingsHeatmapLayer.ts
- libs/deck-layers/src/layers/fourwings/FourwingsHeatmapStaticLayer.ts
- libs/deck-layers/src/layers/fourwings/FourwingsHeatmapTileLayer.ts
- libs/deck-layers/src/layers/fourwings/fourwings.types.ts
- libs/deck-layers/src/layers/fourwings/fourwings.utils.ts
- libs/deck-layers/src/utils/colorRamps.ts
- libs/deck-layers/src/utils/colors.ts
- libs/layer-composer/src/generators/heatmap/util/colors.ts
> improve 4wings rendering

- apps/fishing-map/features/map/Map.tsx
- apps/fishing-map/features/map/map.hooks.ts
- apps/fishing-map/features/map/popups/MapPopups.tsx
- apps/fishing-map/features/map/popups/Popup.module.css
- apps/fishing-map/features/map/popups/PopupWrapper.tsx
- apps/fishing-map/features/map/popups/VesselsTable.tsx
- apps/fishing-map/features/timebar/timebar-vessel.hooks.ts
- libs/deck-layer-composer/src/hooks/deck-layers-composer.hooks.ts
- libs/deck-layer-composer/src/resolvers/context.ts
- libs/deck-layer-composer/src/resolvers/fourwings.ts
- libs/deck-layer-composer/src/resolvers/index.ts
- libs/deck-layer-composer/src/resolvers/types.ts
- libs/deck-layer-composer/src/resolvers/vessels.ts
- libs/deck-layers/src/layers/context/ContextLayer.ts
- libs/deck-layers/src/layers/context/context.types.ts
- libs/deck-layers/src/layers/fourwings/FourwingsHeatmapLayer.ts
- libs/deck-layers/src/layers/fourwings/FourwingsHeatmapStaticLayer.ts
- libs/deck-layers/src/layers/fourwings/FourwingsPositionsTileLayer.ts
- libs/deck-layers/src/layers/fourwings/fourwings.types.ts
- libs/deck-layers/src/layers/vessel/VesselEventsLayer.ts
- libs/deck-layers/src/layers/vessel/VesselLayer.ts
- libs/deck-layers/src/layers/vessel/vessel.types.ts
- package.json
- yarn.lock
> Map interactions tooltips

- apps/fishing-map/features/reports/report.slice.ts
Testing presence report for New Zealand EEZ in 2020
Before
After
> fetch only fields needed in report to make the response lighter

- apps/fishing-map/features/dataviews/dataviews.utils.ts
- apps/fishing-map/features/map/map-sources.hooks.ts
- apps/fishing-map/features/map/map.hooks.ts
- apps/fishing-map/features/map/popups/EncounterTooltipRow.tsx
This PR allows 30 minutes events cluster to dispatch the same fetch thunk than regular events cluster
> Fishing map/retrieve events data for 30min encounters

- apps/fishing-map/data/config.ts
- apps/fishing-map/features/workspace/common/OutOfBoundsDisclaimer.tsx
Fixes out of bounds disclaimer when no extendEnd value available
> fix disclaimer when no dataset extend end

- libs/deck-layers/src/layers/fourwings/positions/FourwingsPositionsTileLayer.ts
> fix positions time range

- apps/fishing-map/features/app/App.tsx
- apps/fishing-map/features/dataviews/selectors/dataviews.selectors.ts
- apps/fishing-map/features/user/UserVesselGroups.tsx
- apps/fishing-map/features/vessel-group-report/VesselGroupReport.module.css
- apps/fishing-map/features/vessel-group-report/VesselGroupReportLink.tsx
- apps/fishing-map/features/vessel-group-report/VesselGroupReportTitle.tsx
- apps/fishing-map/features/vessel-group-report/vessel.config.selectors.ts
- apps/fishing-map/features/vessel-group-report/vessels/VesselGroupReportVessels.tsx
- apps/fishing-map/features/vessel/vessel.config.ts
- apps/fishing-map/features/workspace/vessel-groups/VesselGroupsLayerPanel.tsx
- apps/fishing-map/routes/routes.ts
- apps/fishing-map/types/index.ts
- libs/deck-layers/src/layers/fourwings/heatmap/FourwingsHeatmapStaticLayer.ts
Moves the vessel group report path to a workspace based one.
> Fishing map/vessel profile route

- apps/fishing-map/features/reports/events/VGREventsVesselsTable.tsx
- apps/fishing-map/features/reports/vessel-groups/VesselGroupReport.tsx
- apps/fishing-map/features/reports/vessel-groups/vessels/VesselGroupReportVesselsTable.tsx
- apps/fishing-map/features/reports/vessel-groups/vessels/VesselGroupReportVesselsTableFooter.tsx
- apps/fishing-map/features/search/search.slice.ts
- apps/fishing-map/features/vessel-groups/VesselGroupListTooltip.tsx
- apps/fishing-map/features/vessel/VesselPin.tsx
- apps/fishing-map/utils/info.ts
> Fishing map/vessel profile 3 feedback javi 2

- apps/fishing-map/features/app/App.tsx
- apps/fishing-map/features/dataviews/selectors/dataviews.instances.selectors.ts
- apps/fishing-map/features/reports/areas/AreaReport.tsx
- apps/fishing-map/features/reports/ports/PortsReport.tsx
- apps/fishing-map/features/reports/vessel-groups/VesselGroupReport.tsx
- apps/fishing-map/features/sidebar/Sidebar.tsx
- apps/fishing-map/features/vessel/Vessel.tsx
- apps/fishing-map/features/workspace/Workspace.tsx
- apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
- apps/fishing-map/features/workspace/common/Title.module.css
- apps/fishing-map/features/workspace/common/Title.tsx
- apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx
- apps/fishing-map/features/workspace/vessels/VesselsSection.tsx
- apps/fishing-map/features/workspace/workspace-migration.hooks.tsx
Stop using deprecated datasets by:
- removing the activity and the vessel layers when containing deprecated datasets
- blocking the UI to toggle or add new layers
- making the migration toast not skippable
> Fishing map/migration disclaimer

- .github/labeler.yml
- apps/track-labeler/src/features/timebar/Timebar.module.css
- apps/track-labeler/src/features/timebar/Timebar.tsx
- package.json
- yarn.lock
This PR avoids `rc-slider `to crash the app due to the incompatibility with current (recently updated) `react-dom` version of the project.
> Track labeler/rc slider update

- apps/fishing-map/features/map/Map.module.css
- apps/fishing-map/features/reports/report-area/title/ReportTitle.tsx
Hopefully [this](https://stackoverflow.com/questions/54866986/how-does-object-fit-work-with-canvas-element) makes the trick to fix https://github.com/GlobalFishingWatch/frontend/pull/3103
@GeorgiaDesigns, can you please test if it works for you?
The mini globe can be a bit outside of the map... but I think it is better than the current solution
> add object-fit for map canvas to ensure print doesn't change the ratio

- apps/data-download-portal/src/components/table/table.tsx
- apps/data-download-portal/src/pages/dataset/dataset.tsx
- apps/data-download-portal/src/utils/folderConfig.tsx
DDP TESTING
1 - download collapsed folder 2013-fleet-daily-100-v3 (314 files) -> downloaded 315 files (all in folder + 1 root file possibly in cache)
2 - cleaned cache and download collapsed folder 2012-fleet-daily-100-v3 (366 files) ->
desselect and reselected and clicked download
expanded and clicked download
nothing happened
3 - selected 2 root readme files -> downloaded the 2012-fleet-daily-100-v3 files (366 files)
4 - expanded 2013-fleet-daily-100-v3 folder and selected 5 files then clicked to download -> nothing happened
5 - collapsed folder and selected 1 root readme file -> downloaded all 2013-fleet-daily-100-v3 files (314 files) 
delayed -
- 2012-fleet-daily-100-v3 downloaded (366 files)
- 2 readme files downloaded
- 5 2013 selected files downloaded
- 5 2013 selected files + 1 …
> hotfix ddp download

- apps/fishing-map/features/dataviews/dataviews.utils.ts
- apps/fishing-map/features/reports/report-vessel-group/VesselGroupReport.tsx
- apps/fishing-map/features/reports/report-vessel-group/VesselGroupReportTitle.tsx
- apps/fishing-map/features/reports/report-vessel-group/vessel-group-report.selectors.ts
- apps/fishing-map/features/reports/reports.selectors.ts
- apps/fishing-map/features/reports/reports.types.ts
- apps/fishing-map/features/reports/shared/vessels/ReportVessels.tsx
- apps/fishing-map/features/reports/shared/vessels/ReportVesselsGraph.module.css
- apps/fishing-map/features/reports/shared/vessels/ReportVesselsGraph.tsx
- apps/fishing-map/features/reports/shared/vessels/ReportVesselsGraphSelector.tsx
- apps/fishing-map/features/reports/shared/vessels/ReportVesselsIndividualTooltip.tsx
- apps/fishing-map/features/reports/shared/vessels/ReportVesselsTable.tsx
- apps/fishing-map/features/reports/shared/vessels/ReportVesselsTableFooter.tsx
- apps/fishing-map/features/reports/shared/vessels/report-vessels.selectors.ts
- apps/fishing-map/features/reports/shared/vessels/report-vessels.types.ts
- apps/fishing-map/features/reports/tabs/activity/reports-activity.types.ts
- apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightCoverage.tsx
- apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightCoverageGraph.module.css
- apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightCoverageGraph.tsx
- apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsights.tsx
- apps/fishing-map/features/reports/tabs/vessel-group-insights/vessel-group-report-insights.utils.ts
- apps/fishing-map/features/vessel-groups/VesselGroupModal.module.css
- apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx
- apps/fishing-map/features/vessel-groups/VesselGroupModalVessels.tsx
- apps/fishing-map/features/vessel-groups/vessel-groups.utils.ts
- apps/fishing-map/features/vessel/identity/DataTerminology.module.css
- apps/fishing-map/features/vessel/identity/DataTerminology.tsx
[Vessel group updates](https://dev-ui-fishing-map-vessel-groups-updates-706952489382.us-central1.run.app/):
- Allow users to copy other user vessel group 
- Group vessel group edit vessels modal by its ssvid
- Move coverage to the vessels tab
- Other tweaks
> Fishing map/vessel groups updates

- apps/api-portal/features/user/user.ts
- apps/fishing-map/features/map/map-layers.hooks.ts
- apps/port-labeler/features/map/Map.tsx
- apps/real-time-prototype/features/map/Map.tsx
- apps/track-labeler/src/features/user/user.slice.ts
- libs/api-client/package.json
- libs/api-client/src/api-client.ts
- libs/dataviews-client/package.json
- libs/deck-layer-composer/package.json
- libs/deck-layers/package.json
- libs/deck-layers/src/utils/fetch.ts
- libs/react-hooks/package.json
This fixes the issue when having multiple tabs open. 
To avoid the expired refreshToken when multiple GFWAPI instances are present, the instance always reads from the localStorage now.
> api-client/fix memory refresh token
