GlobalFishingWatch/frontend

.changeset/few-falcons-relate.md, .changeset/perfect-suits-clap.md, applications/amathea/package.json, packages/layer-composer/src/generators/heatmap/heatmap.ts, packages/react-hooks/src/use-dataviews-layers/use-dataviews-layers.ts, yarn.lock
Fix filters and prepare release
=> Fix heatmap generator

.changeset/tough-donuts-grin.md, applications/amathea/src/features/app/App.tsx, applications/amathea/src/features/map/Map.tsx, applications/amathea/src/features/map/map.context.tsx, applications/amathea/src/features/map/map.selectors.ts, applications/amathea/src/features/workspaces/Workspaces.module.css, applications/amathea/src/features/workspaces/Workspaces.tsx, applications/amathea/src/features/workspaces/workspaces.hook.ts, applications/amathea/src/features/workspaces/workspaces.slice.ts, packages/ui-components/src/color-bar/ColorBar.tsx, packages/ui-components/src/color-bar/index.ts
=> Amathea review

.changeset/sixty-stingrays-repair.md, applications/fishing-map/package.json, applications/fishing-map/src/data/config.ts, applications/fishing-map/src/features/layer-panel/LayerPanel.tsx, applications/fishing-map/src/features/map/Map.tsx, applications/fishing-map/src/features/map/map.hooks.ts, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/map/map.slice.ts, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/workspace/workspace.mock.ts, applications/fishing-map/src/routes/routes.selectors.ts, applications/fishing-map/src/routes/routes.ts, applications/fishing-map/src/types/index.ts, applications/temporalgrid-demo/src/App.js, packages/dataviews-client/src/types.ts, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
Test 4wings generator with timeline interaction.
=> fishing-map: Fourwings test

.changeset/silver-needles-own.md, .changeset/thin-foxes-happen.md, applications/fishing-map/src/features/sidebar/VesselsSection.tsx, applications/fishing-map/src/features/workspace/workspace.mock.ts, applications/fishing-map/src/features/workspace/workspace.selectors.ts, packages/dataviews-client/src/dataviews-client.ts, packages/dataviews-client/src/index.ts, packages/dataviews-client/src/resolve-dataviews.ts, packages/dataviews-client/src/types.ts, packages/react-hooks/src/use-dataviews-layers/use-dataviews-layers.ts, packages/react-hooks/src/use-workspace/use-workspace.ts
⚠️ Breaking change in dataview types to migrate dataviews and datasets config structure
=> Multiples workspace dataviews config

.changeset/old-items-smell.md, applications/fishing-map/src/App.tsx, applications/fishing-map/src/features/dataviews/dataviews.mock.ts, applications/fishing-map/src/features/debug/DebugMenu.module.css, applications/fishing-map/src/features/debug/DebugMenu.tsx, applications/fishing-map/src/features/debug/debug.slice.ts, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/workspace/workspace.mock.ts, applications/fishing-map/src/store.ts, linting/index.js, packages/layer-composer/src/generators/background/background.ts, packages/layer-composer/src/generators/basemap/basemap-layers.ts, packages/layer-composer/src/generators/heatmap/config.ts, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts, packages/layer-composer/src/generators/index.ts, packages/ui-components/src/map-legend/ColorRamp.tsx
Corrects a bunch of issues with blob rendering mode, scales it more or less to time period selected, and adds a debug menu to activate it (using 'd' key) and other super secret things in the future
=> Fishing map blob 

applications/fishing-map/src/data/flags.ts, applications/fishing-map/src/features/dataviews/dataviews.mock.ts, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/sidebar/heatmaps/HeatmapFilters.tsx, applications/fishing-map/src/features/sidebar/heatmaps/HeatmapLayerPanel.tsx, applications/fishing-map/src/features/workspace/workspace.mock.ts, applications/fishing-map/src/routes/routes.selectors.ts, applications/fishing-map/src/types/index.ts
- Sets up mock workspace with two 4w based dataviews
- Logic to merge all 4w based dataviews into a single generator with multiple sublayers
- Store filters in dataview instances
=> Merge 4w sublayers 

.changeset/six-boats-relax.md, applications/fishing-map/src/App.tsx, applications/fishing-map/src/features/dataviews/dataviews.mock.ts, applications/fishing-map/src/features/debug/DebugMenu.module.css, applications/fishing-map/src/features/debug/DebugMenu.tsx, applications/fishing-map/src/features/debug/debug.slice.ts, applications/fishing-map/src/features/map/Map.tsx, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/hooks/use-debug-menu.ts
- now requires pressing 7 times the 'd' key to show the debug menu
- adds experimental extruded mode
- adds map debug mode
=> Debug menu

applications/fishing-map/src/features/datasets/datasets.mock.ts, applications/fishing-map/src/features/dataviews/dataviews.mock.ts, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/sidebar/Sidebar.tsx, applications/fishing-map/src/features/sidebar/common/Sections.module.css, applications/fishing-map/src/features/sidebar/context-areas/ContextAreaLayerPanel.tsx, applications/fishing-map/src/features/sidebar/context-areas/ContextAreaSection.tsx, applications/fishing-map/src/features/workspace/workspace.hook.ts, applications/fishing-map/src/features/workspace/workspace.mock.ts, applications/fishing-map/src/features/workspace/workspace.selectors.ts, yarn.lock
MPA as context area example:
Also, restore dataviewInstance on `+` icon button click in context areas and heatmap after removal all of them
=> protected context area

applications/fishing-map/src/features/map/map.hooks.ts, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/map/map.slice.ts, applications/fishing-map/src/features/workspace/workspace.selectors.ts, applications/fishing-map/src/utils/info.ts, packages/dataviews-client/src/resolve-endpoint.ts
=> Load vessel info for multiple sublayers

applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/timebar/Timebar.tsx
=> Timebar and track highlight + bookmark

.changeset/brown-students-lie.md, applications/fishing-map/src/data/config.ts, applications/fishing-map/src/features/timebar/TimebarSettings.tsx, applications/fishing-map/src/features/timebar/timebar.hooks.ts, applications/fishing-map/src/types/index.ts
My code review from https://github.com/GlobalFishingWatch/frontend/pull/152
=> fix timebar vis hook selection

.changeset/spicy-tigers-joke.md, packages/data-transforms/src/track-value-array-to-segments/types.ts
new Field
`
export enum Field {
lonlat = 'lonlat',
longitude = 'longitude',
latitude = 'latitude',
timestamp = 'timestamp',
fishing = 'fishing',
speed = 'speed',
course = 'course',
night = 'night',
distanceFromPort = 'distance_from_port',
elevation = 'elevation',
}
`
=> Added elevation & distance from port to Field

applications/fishing-map/CHANGELOG.md, applications/fishing-map/package.json, applications/fishing-map/src/features/dataviews/dataviews.mock.ts, applications/fishing-map/src/features/dataviews/dataviews.slice.ts, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/workspace/workspace.default.dev.ts, applications/fishing-map/src/features/workspace/workspace.slice.ts, applications/temporalgrid-demo/CHANGELOG.md, applications/temporalgrid-demo/package.json, packages/layer-composer/CHANGELOG.md, packages/layer-composer/package.json, packages/layer-composer/src/generators/heatmap/heatmap.ts
=> Release fishing map to pro

applications/fishing-map/CHANGELOG.md, applications/fishing-map/package.json, applications/fishing-map/src/features/app/app.selectors.ts, applications/fishing-map/src/features/map/controls/MapControls.tsx, applications/fishing-map/src/features/map/controls/MapSearch.module.css, applications/fishing-map/src/features/map/controls/MapSearch.tsx, applications/fishing-map/src/features/workspace/workspace.slice.ts, packages/ocean-areas/CHANGELOG.md, packages/ocean-areas/README.md, packages/ocean-areas/package.json, packages/ocean-areas/src/ocean-areas.ts
=> Adds a search of ocean areas and EEZs to fishing-map

.changeset/cyan-jokes-thank.md, .changeset/spicy-tomatoes-push.md, applications/fishing-map/public/locales/en/datasets.json, applications/fishing-map/public/locales/source/datasets.json, applications/fishing-map/src/data/datasets.ts, applications/fishing-map/src/features/map/Map.tsx, applications/fishing-map/src/features/map/map.selectors.ts, applications/fishing-map/src/features/map/popups/PopupWrapper.tsx, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/timebar/timebar.selectors.ts, applications/fishing-map/src/features/workspace/Workspace.tsx, applications/fishing-map/src/features/workspace/environmental/EnvironmentalLayerPanel.tsx, applications/fishing-map/src/features/workspace/environmental/EnvironmentalSection.tsx, applications/fishing-map/src/features/workspace/workspace.default.development.ts, applications/fishing-map/src/features/workspace/workspace.selectors.ts, packages/layer-composer/src/generators/heatmap/heatmap.ts
=> Fishing map/environmental layers

.changeset/shy-llamas-sleep.md, packages/layer-composer/src/generators/track/track.ts, packages/layer-composer/src/generators/types.ts
I am adding a new property for the track layer  configuration to support set the opacity of the line
=> Added opacity option to track layer

.changeset/honest-carrots-draw.md, applications/fishing-map/CHANGELOG.md, applications/fishing-map/package.json, applications/temporalgrid-demo/CHANGELOG.md, applications/temporalgrid-demo/package.json, package.json, packages/timebar/CHANGELOG.md, packages/timebar/package.json, packages/timebar/src/charts/stacked-activity.js, yarn.lock
- Improves visualisation (only one "bar" per layer)
- Reduces complexity (no need for two copies of the path and the css transformation)
=> Improve stacked-activity chart

applications/vessel-history/cloudbuild_autodeploy_PR.yaml, applications/vessel-history/package.json, yarn.lock
=> Fixed build failed: missing typings for redux-first-router-link

.changeset/loud-pigs-notice.md, packages/fourwings-aggregate/src/aggregate-tile.ts, packages/fourwings-aggregate/test/cell-consistency.test.mjs
Reported here: https://globalfishingwatch.atlassian.net/browse/MAP-285
Before:
After:
=> fixed low level of activity at the bottom of the tiles

.changeset/fifty-sloths-compete.md, applications/sandbox/src/components/Choices.tsx, applications/sandbox/src/components/Logos.tsx, applications/sandbox/src/pages/Components.tsx, packages/ocean-areas/src/index.ts, packages/ocean-areas/src/ocean-areas.ts, packages/ui-components/src/choice/Choice.module.css, packages/ui-components/src/choice/Choice.tsx, packages/ui-components/src/choice/index.ts, packages/ui-components/src/index.ts
Creates the new Choice component and adds an example to the sandbox
https://user-images.githubusercontent.com/38662877/110927759-53a12e00-8326-11eb-8ed8-03e4c7c35e4f.mov
=> UI components / add choice component

applications/fishing-map/src/features/debug/DebugMenu.module.css, applications/fishing-map/src/features/debug/DebugMenu.tsx, applications/fishing-map/src/routes/routes.ts
Adds a URL workspace preview window in the debug modal.
Additionally, shortens the URL by replacing common terms by abbreviations.
=> URL workspace preview window

applications/fishing-map/src/features/workspace/vessels/VesselLayerPanel.tsx
- Added support for formatting vessel fields of type array
=> Fishing map/fix vessel layer panel values format

.github/gfw-bot.json, applications/vessel-history/cloudbuild_autodeploy_PR.yaml
=> vessel history - enable autodeploy bot 

.changeset/tidy-monkeys-hide.md, packages/dataviews-client/src/resolve-dataviews-generators.ts, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts, packages/layer-composer/src/generators/types.ts
=> fix intervals ranges

.changeset/smooth-camels-applaud.md, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
Sort datasets to improve chance of hitting cache
=> Sort datasets to improve chance of hitting cache

applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/es/translations.json, applications/vessel-history/public/locales/fr/translations.json, applications/vessel-history/public/locales/id/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/data/constants.ts, applications/vessel-history/src/features/home/Home.module.css, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/search/search.slice.ts, applications/vessel-history/src/features/search/search.thunk.ts, applications/vessel-history/src/routes/routes.selectors.ts, applications/vessel-history/src/routes/routes.ts
https://globalfishingwatch.atlassian.net/browse/VH-92
=> added pagination to VH

applications/fishing-map/src/features/analysis/Analysis.tsx, applications/fishing-map/src/features/analysis/analysis.slice.test.ts, applications/fishing-map/src/features/analysis/analysis.slice.ts, applications/fishing-map/src/features/analysis/analysis.utils.ts
=> MAP-329 Create single analysis report on multiple dataviews

.changeset/small-vans-jog.md, .changeset/sweet-pugs-prove.md, applications/fishing-map/src/features/app/App.tsx, applications/fishing-map/src/features/workspace/Workspace.tsx, packages/dataviews-client/src/resolve-dataviews-generators.ts, packages/layer-composer/src/generators/heatmap/util/get-legends.ts, packages/layer-composer/src/generators/types.ts, packages/ui-components/src/icon/Icon.tsx
Make the color ramp white end optional and disable it for environmental layers.
Also fixes:
=> Layer composer/fix to white

applications/fishing-map/src/features/map/map.hooks.ts, packages/react-hooks/src/use-map-interaction/index.ts, packages/react-hooks/src/use-map-interaction/use-map-interaction.ts, yarn.lock
Removes a fix made for context layers that's not needed (anymore?) that made the heatmap tooltip fail
=> fixed tooltips

.changeset/moody-queens-rhyme.md, applications/fishing-map/src/features/datasets/datasets.hook.ts, applications/fishing-map/src/features/dataviews/dataviews.utils.ts, applications/fishing-map/src/features/workspace/common/Color.tsx, applications/fishing-map/src/features/workspace/heatmaps/HeatmapsSection.tsx, applications/fishing-map/src/features/workspace/workspace.hook.ts, applications/sandbox/src/components/ColorBar.tsx, applications/vessel-history/src/features/dataviews/dataviews.utils.ts, packages/api-types/src/dataviews.ts, packages/ui-components/src/color-bar/ColorBar.tsx, packages/ui-components/src/color-bar/index.ts, packages/ui-components/src/index.ts, yarn.lock
Adds generic color cycling mechanism when adding a dataview to the map:
- picks a fill or line color palette
- picks the first color of this palette which have the least occurrences amongst all workspace dataviews (visible or not)
=> Fishing map/color cycling

applications/fishing-map/src/features/search/SearchFilters.tsx, applications/fishing-map/src/features/search/search.slice.ts
- Encode all query values in the vessel advanced search
- Fix filter by active after and active before dates
=> MAP-365 Fix vessels advanced search

.changeset/sharp-ducks-tie.md, applications/fishing-map/src/data/default-workspaces/workspace.development.ts, applications/fishing-map/src/data/default-workspaces/workspace.production.ts, applications/fishing-map/src/data/workspaces.ts, applications/fishing-map/src/features/workspace/workspace.slice.ts, packages/layer-composer/src/generators/heatmap/heatmap.ts
Fixes issues that prevented user tracks to show up in most workspaces.
=> Fishing map/user tracks fixes

.changeset/fifty-pumpkins-occur.md, applications/fishing-map/src/data/config.ts, packages/timebar/src/components/bookmark.js, packages/timebar/src/components/timeline.js, packages/timebar/src/components/timeline.module.css, packages/timebar/src/components/timerange-selector.js, packages/timebar/src/utils/index.js, packages/timebar/types/components/bookmark.d.ts, packages/timebar/types/components/timeline.d.ts, packages/timebar/types/utils/index.d.ts
https://user-images.githubusercontent.com/1583415/117292130-1bbeee80-ae70-11eb-8fdc-ba38802900c7.mov
https://globalfishingwatch.atlassian.net/browse/MR-240
=> fishing-map/Future absoluteEnd and last 30 days button

.changeset/three-pianos-tie.md, package.json, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts, packages/layer-composer/src/generators/heatmap/util/time-chunks.ts, packages/layer-composer/src/generators/index.ts, packages/layer-composer/src/index.ts
Fixes issues highlighted here:
https://globalfishingwatch.atlassian.net/browse/MR-248
(there's a likely backend issue too see https://globalfishingwatch.atlassian.net/browse/MR-248?focusedCommentId=12270)
=> Fishing map/environment fixes

.changeset/pink-pens-check.md, applications/fishing-map/public/locales/es/translations.json, applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/app/App.tsx, applications/fishing-map/src/features/dataviews/dataviews.selectors.ts, applications/fishing-map/src/features/map/Map.module.css, applications/fishing-map/src/features/map/popups/ContextLayers.tsx, applications/fishing-map/src/features/map/popups/Popup.module.css, applications/fishing-map/src/features/resources/resources.selectors.ts, applications/fishing-map/src/features/sidebar/Sidebar.module.css, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/workspace/heatmaps/HeatmapInfoModal.module.css, applications/fishing-map/src/features/workspace/heatmaps/HeatmapsSection.module.css, applications/fishing-map/src/features/workspace/shared/ExpandedContainer.module.css, applications/fishing-map/src/features/workspace/shared/Sections.module.css, packages/dataviews-client/src/resolve-dataviews-generators.ts, packages/layer-composer/src/generators/heatmap/util/colors.ts, packages/layer-composer/src/generators/heatmap/util/get-legends.ts, packages/timebar/src/components/playback.module.css, packages/timebar/src/components/timeline.module.css, packages/timebar/src/timebar.module.css, packages/ui-components/src/choice/Choice.tsx, packages/ui-components/src/map-legend/Bivariate.tsx, packages/ui-components/src/split-view/SplitView.module.css, packages/ui-components/src/split-view/SplitView.tsx
Some basic mobile styling and other tweaks and fixes
=> Fishing map/minor fixes

.changeset/plenty-nails-applaud.md, applications/fishing-map/src/features/map/map-features.hooks.ts, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/timebar/TimebarActivityGraph.tsx
Fixes constantly rebuilding graph when only jumping of frame which resulted in poor overall app performance.
=> [WIP] Fishing map/fix timebar graph

.changeset/moody-terms-press.md, packages/data-transforms/src/track-value-array-to-segments/track-value-array-to-segments.test.ts, packages/data-transforms/src/track-value-array-to-segments/track-value-array-to-segments.ts
=> LABELER-109 Fix value array track decoding

applications/fishing-map/public/locales/en/datasets.json, applications/fishing-map/public/locales/source/datasets.json
Update all datasets entities to run [this script](https://github.com/GlobalFishingWatch/crowdin-datasets-internationalization) and obtain the latest datasets changes pointing to production
=> update datasets trasnlations with latest script exec

applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/analysis/Analysis.tsx, packages/ui-components/src/button/Button.tsx
Change download report behaviour to show login link on a guest user and filter reports by dataset permissions (none of the VMS will be available to download)
=> login to create a report

.changeset/dull-taxis-confess.md, packages/ui-components/src/header/Header.module.css
typo in class name in header css
=> added missing style - inverted mode

.changeset/angry-olives-dream.md, packages/ui-components/src/header/Header.tsx
=> removed donate button from header

.changeset/fair-seals-speak.md, applications/fishing-map/src/features/analysis/AnalysisItemGraph.tsx, packages/fourwings-aggregate/src/get-time-series.ts, packages/fourwings-aggregate/test/get-time-series.test.mjs
- fixed calculating averages on padded NaN values in avg mode
- fixed min max y calculation that resulted in falling back to recharts default hence not taking padding into account
=> Fishing map/fix analysis broken graph

applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/analysis/Analysis.tsx
Disable download button when no ais dataset available
=> disable download button when no ais dataset in analysis active

.changeset/quick-panthers-grin.md, packages/ui-components/src/multi-select/MultiSelect.tsx
Added the option of display all the selected options in the multiselects
=> added display all options in multiselect

applications/vessel-history/package.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/App.tsx, applications/vessel-history/src/data/constants.ts, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/search/search.slice.ts, applications/vessel-history/src/features/settings/Settings.module.css, applications/vessel-history/src/features/settings/Settings.tsx, applications/vessel-history/src/features/settings/components/ActivityEvents.tsx, applications/vessel-history/src/features/settings/components/EncounterEvents.tsx, applications/vessel-history/src/features/settings/components/Encounters.tsx, applications/vessel-history/src/features/settings/components/FishingEvents.tsx, applications/vessel-history/src/features/settings/components/LoiteringEvents.tsx, applications/vessel-history/src/features/settings/components/PortVisits.tsx, applications/vessel-history/src/features/settings/components/SettingsComponents.module.css, applications/vessel-history/src/features/settings/settings.hooks.ts, applications/vessel-history/src/features/settings/settings.slice.ts, applications/vessel-history/src/index.tsx, applications/vessel-history/src/offline-store.ts, applications/vessel-history/src/routes/routes.ts, applications/vessel-history/src/store.ts, yarn.lock
https://globalfishingwatch.atlassian.net/browse/VH-74
The translations in another PR
The options for the multiselects need to be defined
Also added a new feature in the multiselect component @j8seangel
=> Added settings page

applications/fishing-map/package.json, applications/fishing-map/src/features/timebar/TimebarActivityGraph.worker.ts, yarn.lock
https://globalfishingwatch.atlassian.net/browse/MAP-322
fix broken compatibility with old browsers (lost when we switch to compute the timebar graph in a worker)
=> fix broken compatibility with old browsers

applications/fishing-map/public/locales/en/translations.json, applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/feedback/FeedbackModal.tsx, applications/fishing-map/src/features/sidebar/CategoryTabs.tsx, applications/fishing-map/src/utils/shared.ts
uses the new questions flow and fields
=> Fishing map/feedback form

.changeset/blue-cats-pay.md, packages/ui-components/src/header/Header.links.ts
Added new item to the header
https://globalfishingwatch.atlassian.net/browse/DOWNLOAD-14
=> added Marine Protected Areas to the header

.changeset/smart-schools-chew.md, packages/ui-components/src/header/Header.module.css
PR to try to fix the version problem
=> change to generate new version

applications/fishing-map/src/data/config.ts, applications/fishing-map/src/features/app/App.tsx, applications/fishing-map/src/features/app/app.selectors.ts, applications/fishing-map/src/features/sidebar/Sidebar.tsx, applications/fishing-map/src/features/sidebar/SidebarHeader.tsx, applications/fishing-map/src/features/workspace/Workspace.tsx, applications/fishing-map/src/features/workspace/context-areas/ContextAreaSection.tsx, applications/fishing-map/src/features/workspace/environmental/EnvironmentalSection.tsx, applications/fishing-map/src/features/workspace/heatmaps/HeatmapLayerPanel.tsx, applications/fishing-map/src/features/workspace/heatmaps/HeatmapsSection.tsx, applications/fishing-map/src/features/workspace/workspace.slice.ts, applications/fishing-map/src/types/index.ts
=> Adds a readOnly urlParam to remove unnecessary content when embedded

applications/vessel-history/src/features/profile/components/activity/Activity.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityDescription.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityDescriptionEEZ.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityDescriptionRFMO.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityGroupDescription.tsx, applications/vessel-history/src/features/regions/regions.selectors.ts, applications/vessel-history/src/features/regions/regions.slice.ts, applications/vessel-history/src/features/vessels/activity/vessels-activity.thunk.ts, applications/vessel-history/src/types/activity.ts, applications/vessel-history/src/utils/region-name-transform.ts
added better description to the events of the activity
translations still missing until I have more event types an a better understanding of how the string will be built
=> improved descriptions of the events

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/components/activity/Activity.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityDate.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityModalContent.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityModalDetails.module.css, applications/vessel-history/src/features/profile/components/activity/description/ActivityDescription.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityDescriptionEEZ.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityDescriptionRFMO.tsx, applications/vessel-history/src/features/profile/components/activity/description/ActivityGroupDescription.tsx, applications/vessel-history/src/features/regions/regions.selectors.ts, packages/ui-components/src/modal/Modal.tsx, yarn.lock
https://globalfishingwatch.atlassian.net/browse/VE-108
=> added modal with details

applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/data/dataviews.md, applications/fishing-map/src/features/app/App.tsx, applications/fishing-map/src/features/timebar/TimebarActivityGraph.tsx, applications/fishing-map/src/features/timebar/timebar.hooks.ts, applications/fishing-map/src/features/welcome/Welcome.module.css, applications/fishing-map/src/features/welcome/Welcome.tsx, applications/fishing-map/src/features/welcome/welcome.content.ts, applications/fishing-map/src/hooks/use-local-storage.ts
Shows a welcome popup for non-marine manager workspaces, which can be toggled off.
=> welcome popup for map v3

applications/fishing-map/public/locales/en/translations.json, applications/fishing-map/public/locales/es/translations.json, applications/fishing-map/public/locales/fr/translations.json, applications/fishing-map/public/locales/id/translations.json, applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/welcome/Welcome.module.css, applications/fishing-map/src/features/welcome/Welcome.tsx, applications/fishing-map/src/features/welcome/welcome.content.ts
- don't show again checked by default
- don't show again placed at the top of the modal
- added content
=> Fishing map/welcome popup update

.changeset/lucky-pandas-agree.md, applications/fishing-map/CHANGELOG.md, applications/fishing-map/package.json, applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/timebar/Timebar.module.css, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/timebar/TimebarActivityGraph.tsx, applications/temporalgrid-demo/CHANGELOG.md, applications/temporalgrid-demo/package.json, packages/timebar/CHANGELOG.md, packages/timebar/package.json, packages/timebar/src/charts/tracks-events.js, packages/timebar/src/charts/tracks-events.module.css
- variable event height depending on # tracks 
- do not show any tracks in timebar when # tracks > 10
=> Fishing map/max tracks

applications/fishing-map/src/features/datasets/NewDataset.tsx, applications/fishing-map/src/features/datasets/NewDatasetTooltip.tsx, applications/fishing-map/src/features/map/popups/FishingLayers.tsx, applications/fishing-map/src/features/timebar/Timebar.tsx
=> MR-318 Fix GA Events

.changeset/red-queens-greet.md, packages/react-hooks/src/use-map-interaction/use-map-interaction.ts
https://user-images.githubusercontent.com/10500650/125298277-4887fa00-e328-11eb-8900-6c2bc1544fe5.mp4
=> disable interaction for attribution links

applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/datasets/NewDatasetTooltip.tsx
https://globalfishingwatch.atlassian.net/browse/MAP-450
=> fix-empty-datasets-label

applications/fishing-map/src/data/dataviews.md, applications/fishing-map/src/data/default-workspaces/workspace.production.ts, applications/fishing-map/src/data/workspaces.ts
Preparing the production release:
=> create missing dataviews for pro

applications/fishing-map/src/features/workspaces-list/WorkspacesList.tsx
=> use html a for external links in workspaces-list

.changeset/empty-mirrors-cheat.md, applications/dataviews-editor/CHANGELOG.md, applications/dataviews-editor/package.json, applications/fishing-map/CHANGELOG.md, applications/fishing-map/package.json, applications/temporalgrid-demo/CHANGELOG.md, applications/temporalgrid-demo/package.json, applications/tile-inspector/CHANGELOG.md, applications/tile-inspector/package.json, applications/vessel-history/CHANGELOG.md, applications/vessel-history/package.json, packages/layer-composer/CHANGELOG.md, packages/layer-composer/package.json, packages/layer-composer/src/generators/track/track.ts, packages/react-hooks/package.json, packages/ui-components/package.json
=> fix track highlight

applications/fishing-map/src/features/analysis/Analysis.tsx
add ecuador private vms datasets to the list of supported download reports
=> support report download for ecuador private workspace

applications/fishing-map/src/features/analysis/Analysis.tsx, applications/fishing-map/src/features/app/App.tsx, applications/fishing-map/src/features/datasets/NewDatasetTooltip.tsx, applications/fishing-map/src/features/search/Search.tsx, applications/fishing-map/src/features/sidebar/CategoryTabs.tsx, applications/fishing-map/src/features/sidebar/SidebarHeader.tsx, applications/fishing-map/src/features/timebar/timebar.hooks.ts, applications/fishing-map/src/features/user/User.tsx, applications/fishing-map/src/features/user/user.slice.ts, applications/fishing-map/src/features/workspace/Workspace.module.css, applications/fishing-map/src/features/workspace/Workspace.tsx, applications/fishing-map/src/features/workspace/vessels/VesselLayerPanel.tsx, applications/fishing-map/src/routes/LoginLink.tsx, applications/fishing-map/src/routes/routes.hook.ts, applications/fishing-map/src/routes/routes.ts, applications/fishing-map/src/store.ts, packages/api-client/src/api-client.ts
Save callbackUrl in local storage to avoid http 431 errors
=> use localStorage for categoryTab login link

.changeset/curly-kiwis-complain.md, applications/fishing-map/CHANGELOG.md, applications/fishing-map/package.json, applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/timebar/timebar.hooks.ts, applications/fishing-map/src/features/workspace/vessels/VesselLayerPanel.tsx, applications/temporalgrid-demo/CHANGELOG.md, applications/temporalgrid-demo/package.json, packages/timebar/CHANGELOG.md, packages/timebar/package.json, packages/timebar/src/charts/tracks.js
=> Fishing map/private ecuador fixes

applications/fishing-map/src/features/user/user.slice.ts, applications/fishing-map/src/routes/routes.hook.ts, applications/fishing-map/src/routes/routes.middlewares.ts, applications/fishing-map/src/routes/routes.ts, applications/fishing-map/src/store.ts, applications/fishing-map/src/types/index.ts
Fix redirection issue when there was a pathname in the url
=> fix url path after redirect

applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/vessel-list-item/VesselListItem.module.css, applications/vessel-history/src/features/vessel-list-item/VesselListItem.tsx, applications/vessel-history/src/features/vessel-list-item/__snapshots__/VesselListItem.test.tsx.snap
=> VV-123 Fix click on vessel without name does not open details

.changeset/fifty-cups-search.md, applications/fishing-map/src/features/workspace/common/FitBounds.tsx, packages/data-transforms/src/index.ts, packages/data-transforms/src/wrap-longitudes/index.ts, packages/data-transforms/src/wrap-longitudes/wrap-longitudes.ts
New data-transform helper to use wrapLongitudes in bounding boxes and avoid antimeridian fitBound issues
=> Fishing map/fix track bounds

.changeset/tidy-candles-cheat.md, applications/vessel-history/src/features/profile/components/activity/ActivityModalContentDetailsLoitering.tsx, packages/api-types/src/events.ts
- Update loitering event fields
- Fixed missing loitering events info
=> Fixed missing loitering events info

.changeset/moody-mangos-scream.md, applications/vessel-history/src/data/config.ts, applications/vessel-history/src/features/dataviews/dataviews.utils.ts, applications/vessel-history/src/features/map/Map.tsx, applications/vessel-history/src/features/map/map-events.hooks.ts, applications/vessel-history/src/features/map/map.selectors.ts, applications/vessel-history/src/features/map/map.slice.ts, packages/dataviews-client/src/resolve-dataviews-generators.ts, packages/layer-composer/src/generators/types.ts, packages/layer-composer/src/generators/vessel-events/vessel-events.ts, yarn.lock
https://globalfishingwatch.atlassian.net/browse/VV-137
=> VV-137 select vessel events onclick

applications/vessel-history/src/features/profile/Profile.tsx
https://globalfishingwatch.atlassian.net/browse/VV-150
Fix error in TMT vessels after join in a GFW vessel (wrong activities)
=> fix events in tmt vessels

applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/es/translations.json, applications/vessel-history/public/locales/fr/translations.json, applications/vessel-history/public/locales/id/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/profile/components/InfoField.tsx, applications/vessel-history/src/features/vessels/sources/tmt.slice.ts, applications/vessel-history/src/features/vessels/vessels.utils.mock.ts, applications/vessel-history/src/features/vessels/vessels.utils.ts, applications/vessel-history/src/types/index.ts
https://globalfishingwatch.atlassian.net/browse/VV-132
=> added iuu status

applications/vessel-history/src/data/constants.ts
- Enabled searching and viewing Support vessels
=> VV-71 Enabled searching and viewing Support vessels

applications/vessel-history/src/features/vessels/__snapshots__/vessels.utils.test.ts.snap, applications/vessel-history/src/features/vessels/sources/tmt.slice.ts, applications/vessel-history/src/features/vessels/vessels.utils.mock.ts
- Sorting field value history chronologically from most recent to oldest.
=> Fix values history order

applications/vessel-history/package.json
- Upgrade ui-components version to use `MultiSelect` `onFilterOptions`
=> bump ui-components version

applications/fishing-map/src/data/config.ts, applications/fishing-map/src/features/search/Search.module.css, applications/fishing-map/src/features/search/Search.tsx, applications/fishing-map/src/features/search/TransmissionsTimeline.module.css, applications/fishing-map/src/features/search/TransmissionsTimeline.tsx
=> Adds a yearly timeline of transmissions to vessels search card

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/Profile.tsx
https://globalfishingwatch.atlassian.net/browse/VV-154
=> use GFW vessel name always in the profile

.changeset/pretty-parrots-crash.md, applications/fishing-map/src/features/search/search.slice.ts, packages/api-client/src/index.ts, packages/api-client/src/utils/search.ts
Moves logic to build advanced query to a util in api-client.
Needed for https://globalfishingwatch.atlassian.net/browse/VV-117
=> Move advanced query logic to api-client

.changeset/odd-parrots-clap.md, applications/fishing-map/src/features/search/Search.tsx, packages/api-types/src/vessel.ts
Show nationalId when available in search results
=> Fishing map/vms search results

applications/vessel-history/public/locales/en/flags.json, applications/vessel-history/public/locales/es/flags.json, applications/vessel-history/public/locales/id/flags.json, applications/vessel-history/public/locales/source/flags.json, applications/vessel-history/src/data/flags.ts
https://globalfishingwatch.atlassian.net/browse/VV-192
=> fix TWN flag

applications/fishing-map/public/locales/source/translations.json, applications/fishing-map/src/features/app/app.selectors.ts, applications/fishing-map/src/features/datasets/datasets.slice.ts, applications/fishing-map/src/features/dataviews/dataviews.selectors.ts, applications/fishing-map/src/features/dataviews/dataviews.utils.ts, applications/fishing-map/src/features/map/popups/FishingLayers.tsx
=> Fishing map/presence tracks poc polish

applications/vessel-history/package.json, applications/vessel-history/src/features/datasets/datasets.slice.ts, applications/vessel-history/src/features/dataviews/dataviews.slice.ts, applications/vessel-history/src/features/vessels/offline-vessels.slice.ts
=> Fix VV builds failing since 80ddf62d

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/App.tsx, applications/vessel-history/src/data/config.ts, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/splash/Splash.module.css, applications/vessel-history/src/features/splash/Splash.tsx, applications/vessel-history/src/features/user/user.hooks.ts, applications/vessel-history/src/index.tsx
See https://globalfishingwatch.atlassian.net/browse/VV-146
=> User access

applications/vessel-history/src/data/config.ts, applications/vessel-history/src/features/event-filters/EventFilters.module.css, applications/vessel-history/src/features/event-filters/EventFilters.tsx, applications/vessel-history/src/features/map/Map.tsx, applications/vessel-history/src/features/map/info/Info.module.css, applications/vessel-history/src/features/map/info/Info.tsx, applications/vessel-history/src/features/profile/Profile.tsx, applications/vessel-history/src/features/profile/components/activity/Activity.tsx, applications/vessel-history/src/features/search/SimpleSearch.tsx
=> added link from activity tab to map

applications/vessel-history/src/features/vessel-list-item/VesselListItem.module.css, applications/vessel-history/src/features/vessel-list-item/VesselListItem.tsx
- Fixed delete offline vessel opening vessel profile
=> Fixed delete offline vessel opens vessel profile

applications/vessel-history/package.json, applications/vessel-history/src/App.test.tsx, applications/vessel-history/src/__snapshots__/App.test.tsx.snap, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/i18n/i18n.ts
- Changed approach to test App by mocking `i18n` and leaving `useSuspense: true` (default) in the i18n config
=> Use i18n mock for snapshot testing

applications/vessel-history/src/features/profile/components/activity/ActivityModalContentDetailsEncounter.tsx
https://globalfishingwatch.atlassian.net/browse/VV-194
=> removed auth status and np trav from encounters

applications/fishing-map/src/features/dataviews/dataviews.mock.ts, applications/fishing-map/src/features/timebar/timebar.selectors.ts, packages/api-client/src/api-client.ts
See https://github.com/GlobalFishingWatch/api-events-service/pull/17
=> use vessel name from info rather than events

applications/fishing-map/cloudbuild.yaml, applications/fishing-map/cloudbuild_autodeploy_PR.yaml
=> improvements images build

applications/vessel-history/cloudbuild_autodeploy_PR.yaml
- tests execution moved to another PR pipeline
=> Cleanup VV autodeploy PR piepeline

applications/vessel-history/src/data/config.ts, applications/vessel-history/src/features/map/Map.tsx, applications/vessel-history/src/features/profile/Profile.tsx, applications/vessel-history/src/features/profile/components/activity/Activity.tsx
Improvements related to the performance of the map and how to preselect events in the map
=> Feature/vesel viewer/improve tabs

applications/vessel-history/src/features/dataviews/dataviews.utils.ts, applications/vessel-history/src/features/profile/Profile.tsx, applications/vessel-history/src/features/vessels/vessels.selectors.ts
- Ensure vessel dataview matches current vessel before fetching vessel resources
=> Fix events and tracks not shown

applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/vessels/__snapshots__/vessels.utils.test.ts.snap, applications/vessel-history/src/features/vessels/sources/gfw.slice.ts, applications/vessel-history/src/features/vessels/sources/tmt.slice.ts, applications/vessel-history/src/features/vessels/vessels.utils.mock.ts, applications/vessel-history/src/types/index.ts
=> VV-229 Added vesselType with history for AIS

applications/vessel-history/src/features/search/search.thunk.ts
https://globalfishingwatch.atlassian.net/browse/VV-209
=> Use new search flow TMT + GFW

applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/profile/components/InfoField.tsx, applications/vessel-history/src/features/profile/components/InfoFieldHistory.tsx
https://globalfishingwatch.atlassian.net/browse/VV-210
=> hide dates in some TMT values

applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/components/activity/ActivityModalContentDetailsPortVisit.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityModalContentField.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityModalDetails.module.css
task > https://globalfishingwatch.atlassian.net/browse/VV-174
details > https://globalfishingwatch.atlassian.net/browse/VV-68
design: pending confirmation
=> added confidence help

applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/routes/routes.selectors.ts
Fix for https://globalfishingwatch.atlassian.net/browse/VV-235
=> fixed issue where search results wouldnt appear when shipname not specified

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/home/Home.module.css, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/search/search.hooks.ts, applications/vessel-history/src/features/vessel-list-item/VesselListItem.module.css, applications/vessel-history/src/features/vessel-list-item/VesselListItem.tsx
https://user-images.githubusercontent.com/2205831/133614123-e3af5050-4103-412d-ae1a-349ba486e3e7.mov
=> VV-217 Select multiple vessels on search results to merge

applications/vessel-history/src/data/constants.ts
- Regardless of the environment display vessel source API
=> VV Display source in vessel search results

applications/vessel-history/src/features/profile/components/activity/Activity.module.css
=> Fixed highlights action icons stacked

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/dataviews/dataviews.utils.ts, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/profile/Profile.tsx, applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/vessels/vessels.utils.ts, applications/vessel-history/src/routes/routes.selectors.ts, applications/vessel-history/src/types/index.ts
- Merge vessels activity
- Disable save for offline view button on merged vessels view
- Updated profile title on merged vessels view
=> VV-229 Merge vessels activity

.changeset/quiet-swans-beg.md, .changeset/strange-pianos-own.md, applications/fishing-map/src/features/datasets/datasets.slice.ts, packages/dataviews-client/src/resolve-dataviews-generators.ts, packages/dataviews-client/src/resolve-dataviews.ts, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
=> Fishing map/ee poc

.changeset/tasty-eggs-rush.md, applications/fishing-map/src/features/timebar/Timebar.tsx, applications/fishing-map/src/features/timebar/timebar.selectors.ts, packages/timebar/src/charts/tracks.js, packages/timebar/src/charts/tracks.module.css
- adds an animation to loading tracks
- makes sure tracks don't 'jump' y positions when other track load 
- magically removes `syncedTracks` logic that is now unneeded
https://user-images.githubusercontent.com/1583415/133799914-cebfca8f-da1b-4af8-af0f-e3542a8cd565.mov
=> Fishing map/timebar track loading

.changeset/eleven-forks-kneel.md, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts, packages/layer-composer/src/generators/heatmap/modes/gridded.ts, packages/layer-composer/src/generators/heatmap/util/get-base-layer.ts, packages/layer-composer/src/generators/types.ts, packages/layer-composer/src/types/index.ts
support custom group for ordering heatmap layers to render the earth engine prototype on top of the land
=> support heatmap groups

applications/vessel-history/src/features/search/search.thunk.ts
Fixes using advance search as basic:
=> force to always use advance search

applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/dataviews/dataviews.config.ts, applications/vessel-history/src/features/map/controls/MapControls.module.css, applications/vessel-history/src/features/map/controls/MapControls.tsx
https://globalfishingwatch.atlassian.net/browse/VV-176
=> removed mpas and added info modal

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/home/Home.module.css, applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/map/info/Info.module.css, applications/vessel-history/src/features/map/info/Info.tsx, applications/vessel-history/src/features/profile/Profile.module.css, applications/vessel-history/src/features/profile/components/Info.module.css, applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/profile/components/activity/Activity.module.css, applications/vessel-history/src/features/profile/components/activity/Activity.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityEvent.tsx, applications/vessel-history/src/features/profile/components/activity/ActivityVoyage.tsx, applications/vessel-history/src/features/search/AdvancedSearch.module.css, applications/vessel-history/src/features/vessel-list-item/VesselListItem.module.css
=> style tweaks for wider screens

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/vessels/activity/vessels-activity.selectors.ts
https://globalfishingwatch.atlassian.net/browse/VV-246
=> VV-246 Display all event regions

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/profile/components/InfoField.tsx, applications/vessel-history/src/features/profile/components/InfoFieldHistory.tsx, applications/vessel-history/src/features/vessel-list-item/VesselListItem.tsx, applications/vessel-history/src/features/vessels/vessels.hook.ts, applications/vessel-history/src/types/vessel.ts
https://globalfishingwatch.atlassian.net/browse/VV-199
=> VV-199 INFO tab change source data as GFW on gear type and vessel type

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/components/activity/Activity.tsx
https://globalfishingwatch.atlassian.net/browse/VV-223
=> clarify no events data

applications/vessel-history/src/features/profile/components/activity/ActivityModalContentDetailsEncounter.tsx
https://globalfishingwatch.atlassian.net/browse/VV-242
=> added mmsi and vessel type in encounter events

applications/vessel-history/src/features/profile/components/activity/ActivityModalContentDetailsLoitering.tsx
https://globalfishingwatch.atlassian.net/browse/VV-247
=> removed position from loitering events

applications/vessel-history/src/features/settings/Settings.module.css
=> Fixed settings info icon general section

applications/vessel-history/src/features/profile/components/activity/Activity.module.css
=> improve highlights styles - removed X scroll

applications/vessel-history/src/features/map/info/Info.tsx, applications/vessel-history/src/features/map/map.selectors.ts, applications/vessel-history/src/features/map/map.slice.ts
https://globalfishingwatch.atlassian.net/browse/VV-249
=> display port exit in the map

applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/profile/components/InfoField.tsx
https://globalfishingwatch.atlassian.net/browse/VV-241
=> VV-241 Help text for gear type, vessel type and iuu status

applications/vessel-history/src/features/profile/components/InfoFieldHistory.tsx
https://globalfishingwatch.atlassian.net/browse/VV-255
=> VV-255 Fixed "0" is displayed in BUILT YEAR and IUU STATUS

.changeset/giant-dogs-relax.md, applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/i18n/i18nDate.tsx, applications/vessel-history/src/features/vessel-list-item/VesselListItem.tsx, packages/api-types/src/vessel.ts
https://globalfishingwatch.atlassian.net/browse/VV-215
=> added amount of transmissions

applications/vessel-history/nginx/nginx.conf, applications/vessel-history/package.json, applications/vessel-history/public/manifest.json, applications/vessel-history/src/features/i18n/i18n.ts, applications/vessel-history/src/routes/routes.ts
https://globalfishingwatch.atlassian.net/browse/VV-252
=> VV-252 Setup prod instance for /vessel-viewer

applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/settings/components/ActivityEvents.tsx, applications/vessel-history/src/features/settings/components/PortVisits.tsx
https://globalfishingwatch.atlassian.net/browse/VV-251
=> update Select option to None

applications/vessel-history/src/features/profile/components/activity/ActivityModalContentDetailsPortVisit.tsx
https://globalfishingwatch.atlassian.net/browse/VV-195
=> display only intermediateAnchorage port

applications/vessel-history/public/locales/en/translations.json, applications/vessel-history/public/locales/source/translations.json, applications/vessel-history/src/features/dataviews/dataviews.config.ts, applications/vessel-history/src/features/i18n/__mocks__/i18n.ts, applications/vessel-history/src/features/i18n/i18n.ts, applications/vessel-history/src/features/i18n/react-i18next.d.ts, applications/vessel-history/src/features/i18n/utils.ts, applications/vessel-history/src/features/map/controls/MapControls.module.css, applications/vessel-history/src/features/map/controls/MapControls.tsx, applications/vessel-history/src/features/profile/components/AuthorizationsField.tsx, applications/vessel-history/src/features/profile/components/Info.module.css
This PR need rebase
https://globalfishingwatch.atlassian.net/browse/VV-176
=> Added layer descriptions from packages

applications/vessel-history/src/features/settings/components/ActivityEvents.tsx, applications/vessel-history/src/features/settings/components/PortVisits.tsx
https://user-images.githubusercontent.com/2205831/135915507-6661291e-964f-4472-8ae2-d5b9e15fc295.mov
=> VV-296 Fixed Downshift is not showing correct selection

applications/vessel-history/src/features/datasets/datasets.slice.ts, applications/vessel-history/src/features/dataviews/dataviews.slice.ts, applications/vessel-history/src/features/profile/Profile.tsx, applications/vessel-history/src/features/profile/components/Info.tsx, applications/vessel-history/src/features/vessels/vessels.selectors.ts, applications/vessel-history/src/features/vessels/vessels.slice.ts, applications/vessel-history/src/features/vessels/voyages/voyages.hook.ts, applications/vessel-history/src/routes/routes.selectors.ts
- Prevent fetching dataviews and datasets multiple times
- Prevent fetching the vessel multiple times
- Moved voyages state to redux store
https://user-images.githubusercontent.com/2205831/139469492-40924b91-294f-4a2c-a869-1ffda7ebab43.mov
=> VV-321 Map flashing with merged vessel

applications/vessel-history/src/routes/routes.middlewares.ts, applications/vessel-history/src/types/index.ts
- After login when performing a search additional requests to `/auth/token` were performed throwing 400 errors
=> VV Fixed multiple requests to /token

applications/vessel-history/src/features/settings/settings.hooks.ts
https://globalfishingwatch.atlassian.net/browse/VV-260
=> Issue with downshift UI component

.changeset/stale-pumas-lay.md, applications/fishing-map/src/features/feedback/FeedbackModal.tsx, packages/timebar/src/components/timeline.js
Added some missing translations
=> added missing translations

applications/vessel-history/src/features/settings/components/ActivityEvents.tsx, applications/vessel-history/src/features/settings/components/PortVisits.tsx, applications/vessel-history/src/features/settings/components/SettingsComponents.module.css
https://globalfishingwatch.atlassian.net/browse/VV-325
=> Help  modal can be opened outside the icon (i) in settings page

.changeset/curly-balloons-wash.md, applications/fishing-map/src/features/analysis/analysis.hooks.ts, applications/fishing-map/src/features/map/map.hooks.ts, applications/fishing-map/src/features/map/popups/ComparisonRow.tsx, packages/layer-composer/src/generators/heatmap/heatmap-animated.ts
Fixes a race condition when breaks are being fetched.
=> Layer composer/fix race condition fetch breaks

applications/fishing-map/src/data/default-workspaces/workspace.development.ts, applications/fishing-map/src/data/default-workspaces/workspace.production.ts, applications/fishing-map/src/features/i18n/i18n.ts, applications/fishing-map/src/features/welcome/welcome.content.ts, applications/fishing-map/src/features/workspace/highlight-panel/HighlightPanel.tsx, applications/fishing-map/src/features/workspace/highlight-panel/highlight-panel.content.ts, applications/fishing-map/src/features/workspaces-list/workspaces-list.slice.ts, applications/fishing-map/src/types/index.ts
Draft to add Portuguese language when translations are ready
Pending translations to add:
=> Portuguese language

applications/vessel-history/src/features/profile/components/Info.module.css, applications/vessel-history/src/features/profile/components/InfoField.tsx
https://globalfishingwatch.atlassian.net/browse/VV-326
=> Help modal can be opened outside the icon (i) in info tab

applications/vessel-history/src/features/home/Home.tsx, applications/vessel-history/src/features/profile/components/Info.tsx
https://globalfishingwatch.atlassian.net/browse/VV-328
=> TMT Contact us - email is missing "+"

applications/vessel-history/src/features/event-filters/EventFilters.tsx
https://globalfishingwatch.atlassian.net/browse/VV-329
=> FR translation issues

apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/map/map.slice.ts, apps/fishing-map/features/map/popups/PopupWrapper.tsx, apps/fishing-map/features/map/popups/ViirsLayers.tsx, apps/fishing-map/features/map/popups/ViirsMatchLayers.tsx, apps/fishing-map/next.config.js, apps/vessel-history/next.config.js, libs/layer-composer/src/generators/types.ts
New popup for viirs match prototype
=> Fishing map/viirs vessel interaction

apps/fishing-map/features/help/hints/Hint.tsx, apps/fishing-map/features/help/hints/HintsHub.tsx
https://globalfishingwatch.atlassian.net/browse/MAP-621
=> Implementing google analytics for help hints

apps/vessel-history/offline/service-worker.ts, apps/vessel-history/pages/_app.tsx, apps/vessel-history/pages/_document.tsx, apps/vessel-history/pages/styles.css, libs/ui-components/src/base.css
WIP
some styles are broken because there are changes in the base ui components
this pr is to share ideas
=> Css styles are broken after merging nx monorepo

apps/vessel-history/features/data-and-terminology/DataAndTerminology.tsx, apps/vessel-history/features/event-filters/EventFilters.tsx, apps/vessel-history/features/map/controls/MapControls.tsx, apps/vessel-history/features/profile/components/Highlights.tsx, apps/vessel-history/features/profile/components/InfoFieldHistory.tsx, apps/vessel-history/features/profile/components/activity/Activity.tsx, apps/vessel-history/nginx.conf, apps/vessel-history/pages/_document.tsx
https://globalfishingwatch.atlassian.net/browse/VV-331
=> VV-331 Modal popups not working

apps/fishing-map/features/analysis/AnalysisPeriodComparison.tsx, apps/fishing-map/features/analysis/AnalysisPeriodComparisonGraph.tsx, apps/fishing-map/features/map/Map.tsx, apps/fishing-map/pages/_app.tsx, libs/ui-components/src/input-date/InputDate.tsx
=> Fishing map/period comparison graph fixes

apps/fishing-map/features/map/popups/FishingLayers.tsx, apps/fishing-map/features/map/popups/Popup.module.css
=> vessels pin icon

apps/fishing-map/data/config.ts, apps/fishing-map/features/app/App.tsx, apps/fishing-map/features/app/AppModals.tsx, apps/fishing-map/features/datasets/EditDataset.tsx, apps/fishing-map/features/datasets/NewDataset.tsx, apps/fishing-map/features/download/DownloadActivityModal.tsx, apps/fishing-map/features/download/DownloadTrackModal.tsx, apps/fishing-map/features/feedback/FeedbackModal.tsx, apps/fishing-map/features/help/HelpModal.tsx, apps/fishing-map/features/map/MapScreenshot.tsx, apps/fishing-map/features/map/controls/MapControls.tsx, apps/fishing-map/features/user/UserDatasets.tsx, apps/fishing-map/features/workspace/common/InfoModal.tsx, apps/fishing-map/features/workspace/shared/NewWorkspaceModal.tsx
Centralize ROOT_DOM_ELEMENT with `__next` to fix screenshot using old CRA root element
=> Fishing map/fix screenshot

apps/fishing-map/features/help/hints/Hint.tsx, apps/fishing-map/features/map/popups/FishingLayers.module.css, apps/fishing-map/features/map/popups/FishingLayers.tsx, apps/fishing-map/features/map/popups/Popup.module.css, apps/fishing-map/features/map/popups/PopupWrapper.tsx, apps/fishing-map/features/map/popups/TileClusterLayers.tsx, apps/fishing-map/features/map/popups/ViirsMatchLayers.tsx, apps/fishing-map/public/locales/source/translations.json
=> Fishing map/popup table

apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/next-env.d.ts, libs/dataviews-client/src/resolve-dataviews-generators.ts
=> Fixes release

apps/fishing-map/features/analysis/Analysis.tsx, apps/fishing-map/features/analysis/AnalysisBeforeAfter.tsx, apps/fishing-map/features/analysis/AnalysisPeriodComparison.tsx, apps/fishing-map/features/download/DownloadActivityModal.tsx, apps/fishing-map/features/map/MapDraw.tsx, apps/fishing-map/features/map/popups/ContextLayers.hooks.ts, apps/fishing-map/features/map/popups/ContextLayers.tsx, apps/fishing-map/features/map/popups/ContextLayersRow.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaSection.tsx
https://globalfishingwatch.atlassian.net/browse/MAP-666
=> Implementing google analytics for "v1.5" release features

apps/vessel-history/data/config.ts
https://globalfishingwatch.atlassian.net/browse/VV-344
=> VV-344 Grant GFW Staff group users access to VV

apps/vessel-history/features/dataviews/dataviews.utils.ts, apps/vessel-history/features/map/Map.tsx, apps/vessel-history/features/profile/Profile.tsx, apps/vessel-history/features/vessels/activity/vessels-activity.selectors.ts, apps/vessel-history/features/vessels/sources/gfw.slice.ts, apps/vessel-history/features/vessels/sources/tmt.slice.ts, apps/vessel-history/features/vessels/vessels.hook.ts, apps/vessel-history/features/vessels/vessels.selectors.ts, apps/vessel-history/features/vessels/vessels.slice.ts, apps/vessel-history/features/vessels/vessels.utils.ts, apps/vessel-history/routes/routes.selectors.ts, libs/dataviews-client/src/resources/resources-slice.ts
https://globalfishingwatch.atlassian.net/browse/VV-341
=> Manual merge of a TMT and GFW records is not working 

apps/fishing-map/features/map/map-viewport.hooks.ts, apps/fishing-map/features/timebar/timebar.hooks.ts, apps/fishing-map/package.json, apps/vessel-history/features/map/map-viewport.hooks.ts, apps/vessel-history/package.json, tools/generators/app/files/features/map/map-viewport.hooks.ts, tools/generators/app/files/features/timebar/timebar.hooks.ts, tools/generators/app/files/package.json__tmpl__, yarn.lock
https://recoiljs.org/blog/2022/01/28/0.6.0-release
=> update recoil version

apps/vessel-history/data/config.ts, apps/vessel-history/features/user/user.hooks.ts, apps/vessel-history/package.json
https://globalfishingwatch.atlassian.net/browse/VV-345
=> VV-345 Updated VV authorization to use permissions instead of groups

apps/fishing-map/features/search/SearchFilters.tsx, apps/fishing-map/features/search/search.slice.ts
Fixes advanced search, see commits history
=> Fishing map/fix advanced search

apps/fishing-map/features/app/AppModals.tsx, apps/fishing-map/hooks/secret-menu.hooks.ts
Hit 'w' 7 times to remove all url workspace parameters.
=> adds a keyboard combo to reset workspace

apps/fishing-map/features/map/controls/MapInfo.tsx, apps/fishing-map/features/map/popups/VesselsTable.module.css, apps/fishing-map/features/map/popups/VesselsTable.tsx, apps/fishing-map/public/locales/source/translations.json
Add interactive timestamps for viirs match detections:
- Fit to first and last when multiple
- Fit to entire day when single
=> Fishing map/viirs match timestamps

libs/dataviews-client/src/resolve-dataviews-generators.ts, libs/layer-composer/src/generators/heatmap/config.ts, libs/layer-composer/src/generators/heatmap/heatmap-animated.ts, libs/layer-composer/src/generators/heatmap/util/time-chunks.ts, libs/layer-composer/src/generators/index.ts, libs/layer-composer/src/generators/types.ts
Centralize and simplify interval switching logic.
=> Simplify interval switching logic

apps/fishing-map/features/datasets/NewDatasetTooltip.tsx, apps/fishing-map/features/datasets/datasets.hook.ts, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaSection.tsx, apps/fishing-map/features/workspace/shared/LayerPanel.module.css, apps/fishing-map/public/locales/source/translations.json, libs/i18n-labels/source/datasets.json
https://globalfishingwatch.atlassian.net/browse/MAP-702https://globalfishingwatch.atlassian.net/browse/MAP-702
Here shown with fallback text, waiting for datasets i18n
=> Added data warnings on selected datasets

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/download/DownloadActivityModal.tsx, apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/map/map.slice.ts, apps/fishing-map/features/map/popups/VesselsTable.tsx, apps/fishing-map/features/map/popups/ViirsMatchLayers.tsx, apps/fishing-map/features/workspace/activity/ActivitySchemaFilter.tsx, libs/dataviews-client/src/resolve-dataviews-generators.ts
See commits history for the list of fixes
=> Fishing map/polish viirs interaction

apps/fishing-map/features/bigquery/BigQuery.tsx, apps/fishing-map/features/bigquery/bigquery.slice.ts, libs/api-client/src/api-client.ts
Use new errors format, only used in BQ creation errors for now.
=> show errors in bq dataset creation

apps/fishing-map/features/analysis/Analysis.tsx, apps/fishing-map/features/analysis/AnalysisLayerPanel.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/pages/styles.css
=> Fishing map/bug fixes

apps/fishing-map/data/dataviews.md, apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/map/popups/ContextLayers.tsx, libs/i18n-labels/source/datasets.json, libs/layer-composer/src/generators/basemap/basemap-layers.ts, libs/layer-composer/src/generators/context/context-layers.ts, libs/layer-composer/src/generators/context/context.ts, libs/layer-composer/src/generators/context/context.utils.ts, libs/layer-composer/src/generators/types.ts
Adds graticules as a new context layer and shows values. Renders thirty, ten, five or single degree lines depending on zoom level.
=> Fishing map/graticules as reference layer

apps/port-labeler/features/sidebar/sidebar.hooks.ts, apps/port-labeler/types/index.ts
https://globalfishingwatch.atlassian.net/browse/LABELER-117
=> refactor input/output model

apps/fishing-map/features/workspace/activity/ActivitySchemaFilter.tsx, apps/fishing-map/features/workspace/shared/DatasetSchemaField.tsx, libs/ui-components/src/slider/Slider.tsx, libs/ui-components/src/slider/slider.module.css
Allows slider component to have discrete steps for non-linear filters and adds a histogram (static for VIIRS for now)
=> Fishing map/slider range

apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/highlight-panel/HighlightPanel.tsx, apps/fishing-map/features/workspace/highlight-panel/highlight-panel.content.ts, libs/dataviews-client/src/resolve-dataviews-generators.ts
Update everything for VIIRS match release.
Pending merging of https://github.com/GlobalFishingWatch/datasets-versioning/pull/23 and properly testing
=> Release VIIRS match

apps/port-labeler/features/labeler/labeler.selectors.ts, apps/port-labeler/features/labeler/labeler.slice.ts, apps/port-labeler/features/sidebar/sidebar.hooks.ts, apps/port-labeler/features/table-anchorage/TableAnchorage.tsx, apps/port-labeler/features/table-anchorage/TableRow.tsx, apps/port-labeler/features/table-anchorage/components/SubareaSelector.tsx, apps/port-labeler/types/index.ts
https://globalfishingwatch.atlassian.net/browse/LABELER-118
=> improve port list

apps/vessel-history/features/vessels/sources/tmt.slice.ts, apps/vessel-history/features/vessels/vessels.slice.ts
https://globalfishingwatch.atlassian.net/browse/VV-373
=> When TMT detail API is not working, we should display at least GFW data

apps/fishing-map/features/timebar/timebar.selectors.ts, libs/data-transforms/src/wrap-longitudes/wrap-longitudes.ts, libs/dataviews-client/src/resources/resources-slice.ts
Wrap longitudes client side for user tracks.
Fix for https://globalfishingwatch.atlassian.net/browse/MAP-795
=> wrap longitudes client side for user tracks

apps/vessel-history/features/home/Home.module.css, apps/vessel-history/features/home/Home.tsx, apps/vessel-history/features/partners/Partners.module.css, apps/vessel-history/features/partners/Partners.tsx, apps/vessel-history/features/splash/Splash.module.css, apps/vessel-history/features/splash/Splash.tsx
https://globalfishingwatch.atlassian.net/browse/VV-372
=> Update VV landing page with GFW/TMT logos

apps/vessel-history/features/profile/Profile.tsx
https://globalfishingwatch.atlassian.net/browse/VV-375
=> Offline view - Map view is displaying the track from another vessel

apps/fishing-map/features/analysis/analysis.hooks.ts, apps/fishing-map/features/map/Map.tsx, apps/fishing-map/features/map/MapScreenshot.tsx, apps/fishing-map/features/map/controls/MapControls.tsx, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts, apps/fishing-map/features/timebar/TimebarActivityGraph.tsx
=> Fishing map/fixes

apps/api-portal/components/user-additional-fields/user-additional-fields.module.css, apps/api-portal/components/user-additional-fields/user-additional-fields.tsx, apps/api-portal/lib/types.ts
https://globalfishingwatch.atlassian.net/browse/API-273
=> API Portal. Token Site - If intended user is "Commercial", block flow. API-273

apps/fishing-map/features/map/map.utils.ts
Found a use case that https://github.com/GlobalFishingWatch/frontend/pull/1368 doesn't cover so this PR fixes the filter by viewport issue using the same approach than before but moving only the needed features.
=> fix missing features filtered by viewport in timebar

libs/fourwings-aggregate/src/get-time-series.ts
https://globalfishingwatch.atlassian.net/browse/MAP-784
=> Coastal Fisheries - missing data in timebar and others

.github/labeler.yml
Follow-up of https://github.com/GlobalFishingWatch/frontend/pull/1375
=> added all libs and apps

apps/fishing-map/features/map/popups/Popup.module.css
=> set max tooltip list height

libs/layer-composer/src/generators/vessel-events/vessel-events-shapes.ts
=> sort highlighted events

apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/activity/ActivityFilters.module.css, apps/fishing-map/features/workspace/highlight-panel/highlight-panel.content.ts, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/es/translations.json, libs/dataviews-client/src/resolve-dataviews-generators.ts, libs/i18n-labels/en/datasets.json, libs/i18n-labels/es/datasets.json, libs/i18n-labels/fr/datasets.json, libs/i18n-labels/id/datasets.json, libs/i18n-labels/pt/datasets.json, libs/i18n-labels/source/datasets.json
Merging master to develop as some hotfixes were deployed on prod but not merged back to develop.
=> Master to develop

apps/fishing-map/pages/_document.tsx, apps/fishing-map/public/icons/manifest.webmanifest, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, apps/fishing-map/public/unsupported.html, apps/fishing-map/routes/description.reducer.ts, apps/fishing-map/routes/routes.middlewares.ts, apps/fishing-map/routes/routes.ts, apps/fishing-map/store.ts
https://globalfishingwatch.atlassian.net/browse/MAP-804
=> Have three different descriptions on meta descriptions to improve SEO (CVP, MM, MAP)

apps/user-groups-admin/components/user-groups/detail.tsx, apps/user-groups-admin/package.json
=> User groups admin feedback

.github/gfw-bot.json, apps/vessel-history/features/event-filters/filters.hooks.ts, apps/vessel-history/features/profile/Profile.tsx
Merge this once https://github.com/GlobalFishingWatch/gfw-github-bot/pull/4 is merged
=> update cloudbuildTaskDevId ids

apps/fishing-map/features/dataviews/dataviews.selectors.ts, apps/fishing-map/features/dataviews/dataviews.slice.ts, apps/fishing-map/features/map/Map.tsx, apps/fishing-map/features/map/map-sources.hooks.ts, apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/map/map.selectors.ts, apps/fishing-map/features/workspace/activity/ActivityAuxiliaryLayer.tsx, libs/dataviews-client/src/resolve-dataviews-generators.ts, libs/dataviews-client/src/resources/get-resources.ts, libs/layer-composer/src/generators/polygons/polygons.ts, libs/layer-composer/src/generators/types.ts
Using mapbox to fetch the geojson and the `useMapSourceTilesLoaded` to render the loading state for the footprint layer
Pros: it simplifies the workflow and remove a lot of code
Cons: the layer remains on the map until the new geojson is loaded
=> use mapbox url to fetch the resource

libs/layer-composer/package.json, libs/layer-composer/src/generators/heatmap/heatmap-animated.ts, libs/react-hooks/package.json, package.json, yarn.lock
Uses https://github.com/GlobalFishingWatch/maplibre-gl-js/pull/5 to avoid spamming the 4wings tiles API
=> update 4wings tiles debounced

apps/fishing-map/features/map/controls/MiniGlobeInfo.tsx
fixes missing https://github.com/GlobalFishingWatch/frontend/pull/1416 commit
=> fix initial miniglobe name

apps/port-labeler/features/labeler/labeler.slice.ts, apps/port-labeler/features/sidebar/SidebarHeader.tsx, apps/port-labeler/features/table-anchorage/TableAnchorage.module.css, apps/port-labeler/features/table-anchorage/TableAnchorage.tsx, apps/port-labeler/features/table-anchorage/TableHeader.tsx, apps/port-labeler/features/table-anchorage/TableRow.tsx, apps/port-labeler/public/locales/en/translations.json, apps/port-labeler/public/locales/es/translations.json, apps/port-labeler/public/locales/fr/translations.json, apps/port-labeler/public/locales/source/translations.json
https://globalfishingwatch.atlassian.net/browse/LABELER-119
=> Port Labeler // User wants to be able to see the anchorage-id in order to find quickly an specific anchorage

apps/port-labeler/features/table-anchorage/TableRow.tsx, apps/port-labeler/package.json, yarn.lock
https://globalfishingwatch.atlassian.net/browse/LABELER-121
=> We want IDS to be unique to avoid collisions on ports and subareas

apps/fishing-map/features/app/App.tsx, apps/fishing-map/features/app/app.hooks.ts
Wait for the tab to become visible for the first time before rendering the map
=> Don't render the map until tab becomes visible for the first time

package.json, yarn.lock
trying to fix the map crash doing a rollback for the react 17 version of next
=> use next with react 17

apps/fishing-map/features/workspace/environmental/UserTrackLayerPanel.tsx, libs/data-transforms/src/csv-to-track-segments/csvToTrackSegments.ts
Hides
when id field is not selected
=> hide no_id when no id field selected

libs/layer-composer/src/generators/basemap/basemap-layers.ts
Use gateway (by environment and version) for satellite tiles
=> uset gateway endpoint for gtiles

apps/api-portal/Dockerfile, apps/fishing-map/Dockerfile, apps/port-labeler/Dockerfile, apps/tile-inspector/Dockerfile, apps/user-groups-admin/Dockerfile, apps/vessel-history/Dockerfile, tools/generators/app/files/Dockerfile, tools/generators/minisite/files/Dockerfile
Due to this bug GoogleContainerTools/kaniko#1297
=> Omit alpine update packages

apps/fishing-map/data/config.ts, apps/fishing-map/features/workspace/Workspace.module.css, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/public/locales/source/translations.json
=> show labels for user workspaces

apps/fishing-map/features/app/AppModals.tsx, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/download/DownloadTrackModal.tsx, apps/fishing-map/features/help/hints/Hint.module.css, apps/fishing-map/features/help/hints/HintsHub.tsx, apps/fishing-map/features/map/popups/VesselsTable.tsx, apps/fishing-map/features/user/GFWOnly.module.css, apps/fishing-map/features/user/GFWOnly.tsx, apps/fishing-map/features/workspace/common/InfoModalContent.tsx, apps/fishing-map/features/workspace/shared/layer-panel-sort.hook.ts, apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, libs/ui-components/src/base.css
=> Show warnings when features or datasets are only visible by GFW users

apps/vessel-history/features/settings/components/ActivityEvents.tsx, apps/vessel-history/features/settings/components/PortVisits.tsx, apps/vessel-history/features/settings/components/SettingsComponents.module.css
https://globalfishingwatch.atlassian.net/browse/VV-261
=> Inconsistency in data validation // VV-261

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.hooks.ts, apps/fishing-map/features/vessel-groups/vessel-groups.selectors.ts, apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts, apps/fishing-map/features/workspace/activity/ActivityFilters.module.css, apps/fishing-map/features/workspace/activity/ActivityFilters.tsx, apps/fishing-map/features/workspace/activity/ActivitySchemaFilter.tsx, apps/fishing-map/features/workspace/shared/DatasetSchemaField.tsx, libs/layer-composer/src/generators/heatmap/heatmap-animated.ts, libs/layer-composer/src/generators/heatmap/util/fetch-breaks.ts, libs/layer-composer/src/generators/heatmap/util/get-legends.ts, libs/layer-composer/src/generators/heatmap/util/index.ts
- Request bins on vessel groups
- Add new vessel group created to dataview instance
=> Fishing map/vessel groups ramps

apps/fishing-map/features/datasets/DatasetLabel.tsx, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/user/User.tsx, apps/fishing-map/features/user/user.selectors.ts, apps/fishing-map/features/vessel-groups/VesselGroupModal.module.css, apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.hooks.ts, apps/fishing-map/features/vessel-groups/vessel-groups.selectors.ts, apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/features/workspace/activity/ActivityFilters.tsx, apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx, apps/fishing-map/public/locales/source/translations.json, libs/api-client/src/utils/errors.ts, libs/api-types/src/vesselGroups.ts
=> Fishing map/vessel groups permissions

apps/fishing-map/features/search/Search.module.css, apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/sidebar/Sidebar.tsx, apps/fishing-map/features/user/UserVesselGroups.tsx, apps/fishing-map/features/vessel-groups/VesselGroupModal.module.css, apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx, apps/fishing-map/features/vessel-groups/VesselGroupModalSearch.tsx, apps/fishing-map/features/vessel-groups/VesselGroupModalVessels.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.selectors.ts, apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/public/locales/source/translations.json, libs/api-types/src/vesselGroups.ts
support add new vessels in a existing vessel group
also support editing from the user panel
=> Fishing map/vessel groups edit

apps/fishing-map/features/datasets/NewDatasetTooltip.tsx, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/user/UserDatasets.tsx, apps/fishing-map/features/workspace/common/Title.tsx, apps/fishing-map/features/workspace/environmental/UserTrackLayerPanel.tsx, libs/data-transforms/src/segments/segments-to-bbox.ts
=> Show icons next to dataset names

apps/vessel-history/features/profile/Profile.tsx
https://globalfishingwatch.atlassian.net/browse/VV-397
=> No activity data is display when merging a TMT only vessel with a GFW vessel // VV-397

apps/vessel-history/features/home/Home.tsx
a fix for this PR https://github.com/GlobalFishingWatch/frontend/pull/1489
=> fix see vessel for merged vessels

apps/fishing-map/features/workspace/activity/ActivityFilters.tsx, apps/fishing-map/features/workspace/activity/ActivitySchemaFilter.tsx, libs/ui-components/src/multi-select/MultiSelect.tsx
Save the changes in a temporal state to apply all at once when the select list is closed
=> Fishing map/apply filters on select close

apps/fishing-map/features/workspace/environmental/environmental.hooks.ts, libs/dataviews-client/src/resolve-dataviews-generators.ts, libs/dataviews-client/src/url-workspace.ts, libs/layer-composer/src/generators/heatmap/util/fetch-breaks.ts, libs/layer-composer/src/generators/heatmap/util/get-legends.ts, libs/layer-composer/src/generators/types.ts, libs/layer-composer/src/layer-composer.ts, libs/react-hooks/src/use-layer-composer/use-layer-composer.ts
Fix multiple activity layers ending in white color ramp
Support white end for environmental layers
=> Fishing map/activity layer fixes

apps/fishing-map/features/i18n/i18nDate.tsx, apps/fishing-map/features/map/popups/VesselEventsLayers.tsx, apps/fishing-map/features/resources/resources.utils.ts, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/utils/events.ts, libs/dataviews-client/src/resources/resources-slice.ts, libs/layer-composer/src/generators/heatmap/util/get-legends.ts
=> Fishing map/bugs clean

apps/fishing-map/data/dataviews.md, apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/workspace/environmental/environmental.hooks.ts, libs/dataviews-client/src/resolve-dataviews-generators.ts, libs/fourwings-aggregate/package.json, libs/fourwings-aggregate/src/aggregate-cell.ts, libs/fourwings-aggregate/src/aggregate-tile.ts, libs/fourwings-aggregate/src/util.ts, libs/layer-composer/src/generators/heatmap/modes/gridded.ts
=> Global env layers

apps/fishing-map/features/user/UserWorkspaces.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts
- [] ~Matched VIIRS with unknown vessels~ need to be addressed in the API
=> Fishing map/release bug fixing

apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/dataviews/dataviews.selectors.ts, apps/fishing-map/features/debug/DebugMenu.tsx, apps/fishing-map/features/i18n/LanguageToggle.tsx, apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/user/GFWOnly.tsx, apps/fishing-map/features/workspace/common/Title.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/shared/LayerPanel.module.css, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, libs/layer-composer/src/generators/basemap-labels/basemap-labels-layers.ts, libs/layer-composer/src/generators/basemap-labels/basemap-labels.ts, libs/layer-composer/src/generators/basemap/basemap-layers.ts, libs/layer-composer/src/generators/basemap/basemap.ts, libs/layer-composer/src/generators/index.ts, libs/layer-composer/src/generators/types.ts
=> show basemap labels as a reference layer

apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx, apps/fishing-map/queries/stats-api.ts
Merge once develop is released into production
=> remove 1year stats limit

apps/vessel-history/features/profile/components/ForcedLabor.tsx, apps/vessel-history/types/index.ts
=> fix reported cases source property // VV-391

apps/vessel-history/data/config.ts, apps/vessel-history/features/profile/components/ForcedLabor.module.css, apps/vessel-history/features/profile/components/ForcedLabor.tsx, apps/vessel-history/public/locales/en/translations.json, apps/vessel-history/public/locales/source/translations.json
=> change forced labor model to 2020 // VV-391

libs/dataviews-client/src/url-workspace.ts
migrate public to full VMS track datasets
=> test full dataset id migration

apps/vessel-history/features/terminology/__snapshots__/terminology-ais-disabling.spec.tsx.snap, apps/vessel-history/features/terminology/terminology-ais-disabling.tsx, apps/vessel-history/public/locales/source/translations.json
https://globalfishingwatch.atlassian.net/browse/VV-432
=> Display risk indicator for INTENTIONAL DISABLING events in Vessel Viewer Risk Summary VV-432

apps/vessel-history/features/activity-by-type/activity-by-type.module.css
=> Adjust bottom margin on activity by type heading buttons. VV-427

apps/port-labeler/features/map/map-style.ts, yarn.lock
https://globalfishingwatch.atlassian.net/browse/LABELER-127
=> update satellite map on port inspector

apps/vessel-history/features/data-and-terminology/DataAndTerminology.tsx, apps/vessel-history/features/home/Home.tsx, apps/vessel-history/features/vessel-list-item/VesselListItem.tsx, apps/vessel-history/public/locales/en/translations.json, apps/vessel-history/public/locales/source/translations.json
wip
https://globalfishingwatch.atlassian.net/browse/VV-449
=> Display info pop-up on vessel viewer search page to define 'transmissions' VV-449

apps/vessel-history/features/profile/components/Info.tsx
=> Format built year to display only the year. VV-443

apps/vessel-history/features/risk-section/risk-section.module.css, apps/vessel-history/features/risk-section/risk-section.tsx, apps/vessel-history/features/risk-summary/risk-summary.tsx
https://globalfishingwatch.atlassian.net/browse/VV-448
=> Display identity and event icons alongside the categories in vessel viewer risk summary tab VV-448

apps/vessel-history/features/resources/resources.slice.ts
https://globalfishingwatch.atlassian.net/browse/VV-118?focusedCommentId=17517
=> removed non intentional disabling gaps VV-118

apps/fishing-map/features/timebar/timebar.selectors.ts
Fixes https://globalfishingwatch.atlassian.net/browse/MAP-756
=> fix crash when more than 10 vessels

apps/vessel-history/public/locales/en/translations.json
https://globalfishingwatch.atlassian.net/browse/VV-449
=> Display info pop-up on vessel viewer search page to define 'transmissions'

apps/fishing-map/features/datasets/datasets.slice.ts, apps/vessel-history/features/dataviews/dataviews.selectors.ts, libs/dataviews-client/src/resources/get-resources.ts
Fixes https://globalfishingwatch.slack.com/archives/C0296TY92KC/p1662503287197889
=> fix user-tracks missing datasetConfig

apps/vessel-history/features/risk-indicator/risk-indicator.slice.ts, apps/vessel-history/package.json
Fixed inconsistent results with TMT RFMO IUU blacklist status. VV-481
=> 🚀  Release - Vessel Viewer v1.1.1

apps/vessel-history/features/activity-by-type/activity-by-type.tsx
Fix for [this error calling method of undefined](https://github.com/GlobalFishingWatch/frontend/pull/1661/files#r966360043)  detected by @fertandil87
=> Fixed error calling method of undefined. VV-427

apps/vessel-history/features/profile/components/activity/AisCoverage.tsx, apps/vessel-history/features/risk-summary/risk-summary.tsx, libs/ui-components/src/progress-bar/ProgressBar.tsx
https://globalfishingwatch.atlassian.net/browse/VV-445
=> Display AIS coverage metric in vessel viewer to a whole number VV-445

apps/fishing-map/features/workspace/environmental/HistogramRangeFilter.tsx, apps/fishing-map/features/workspace/environmental/histogram.hooks.ts
Add histogram to environmental layers, pending to confirm [dataset configuration](https://github.com/GlobalFishingWatch/datasets-versioning/pull/47) (don't merge this until datasets merged)
=> histogram to global env layers filter

apps/vessel-history/features/terminology/__snapshots__/terminology-iuu.spec.tsx.snap, apps/vessel-history/features/terminology/terminology-iuu.tsx
=> Fixed warning on test

apps/vessel-history/features/vessel-list-item/VesselListItem.module.css, apps/vessel-history/features/vessel-list-item/VesselListItem.tsx
https://globalfishingwatch.atlassian.net/browse/VV-449
=> Improvement to not fire position modal outside the button VV-449

apps/vessel-history/features/settings/Settings.module.css, apps/vessel-history/features/settings/Settings.tsx, apps/vessel-history/features/settings/components/ActivityEvents.tsx, apps/vessel-history/features/settings/settings.hooks.ts, apps/vessel-history/features/settings/settings.slice.ts, apps/vessel-history/features/vessels/activity/__mocks__/highlight.mock.ts, apps/vessel-history/features/vessels/activity/__snapshots__/vessels-highlight.worker.test.ts.snap, apps/vessel-history/features/vessels/activity/vessels-highlight.worker.test.ts, apps/vessel-history/features/vessels/activity/vessels-highlight.worker.ts, apps/vessel-history/public/locales/source/translations.json, libs/ui-components/src/multi-select/MultiSelect.tsx
https://globalfishingwatch.atlassian.net/browse/VV-279
=> Enable or disable all highlight settings at event type level // VV-279

apps/vessel-history/features/home/Home.tsx, apps/vessel-history/features/profile/Profile.tsx, apps/vessel-history/features/profile/components/Info.tsx, apps/vessel-history/features/vessel-list-item/VesselListItem.tsx, apps/vessel-history/features/vessels/__snapshots__/vessels.utils.test.ts.snap, apps/vessel-history/features/vessels/offline-vessels.selectors.ts, apps/vessel-history/features/vessels/sources/gfw.slice.ts, apps/vessel-history/features/vessels/sources/tmt.slice.ts, apps/vessel-history/features/vessels/vessels.slice.ts, apps/vessel-history/features/vessels/vessels.utils.mock.ts, apps/vessel-history/features/vessels/vessels.utils.ts, apps/vessel-history/types/index.ts, apps/vessel-history/types/vessel.ts, apps/vessel-history/utils/async-slice.ts, libs/api-types/src/vessel.ts
https://globalfishingwatch.atlassian.net/browse/VV-231
=> Offline vessel Merge // VV-231

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/shared/DatasetSourceField.tsx, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, libs/api-types/src/datasets.ts
=> Fishing map/show source always and name dataviews based on category and subcategory

libs/api-types/src/datasets.ts
Do not merge until these PRs are merged:
https://github.com/GlobalFishingWatch/datasets-versioning/pull/49
https://github.com/GlobalFishingWatch/api-datasets/pull/71
=> update dataset detection category

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/activity/ActivitySection.tsx
=> show sources in activity layer adding

apps/deck-playground/features/map/Map.tsx, apps/deck-playground/features/map/layers.hooks.ts, apps/deck-playground/features/sidebar/Sidebar.tsx, apps/deck-playground/features/timebar/Timebar.tsx, apps/deck-playground/features/timebar/TimebarActivityGraph.tsx, apps/deck-playground/layers/fourwings/FourwingsLayer.ts, apps/deck-playground/layers/fourwings/FourwingsTileLayer.ts, apps/deck-playground/layers/fourwings/fourwings.hooks.ts, apps/deck-playground/layers/fourwings/fourwings.utils.ts
Testing to store the class instance into its own atom and hook
=> move deck instances to own hook

apps/deck-playground/features/timebar/TimebarActivityGraph.tsx, apps/deck-playground/layers/fourwings/FourwingsLayer.ts, apps/deck-playground/layers/fourwings/fourwings.hooks.ts, apps/deck-playground/layers/fourwings/fourwings.utils.ts
PR to deploy and compare the differences between updating the color ramp at the viewport load vs every tile load
=> udpate color ramp on every tile load

apps/vessel-history/features/search/search.utils.ts
https://globalfishingwatch.atlassian.net/browse/VV-464
=> Enable automatic merge when searching by multiple identifiers

apps/fishing-map/features/analysis/AnalysisBeforeAfter.tsx, apps/fishing-map/features/workspace/activity/ActivitySection.tsx
=> fix crash when no sublayers ready

apps/fishing-map/features/analysis/analysis-timeseries.utils.ts, apps/fishing-map/features/map/map-sources.hooks.ts, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts, libs/features-aggregate/src/timeseries.ts, libs/fourwings-aggregate/src/get-time-series.ts, libs/layer-composer/src/types/index.ts
=> update timebar graph on env layer filter

apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/search/search.slice.ts
Render all vessel results for GFW Staff members so they can compare between Other and Fishing vessels
=> not remove duplicated vessel Ids for gfwstaff

apps/vessel-history/features/activity-by-type/activity-by-type.tsx
https://globalfishingwatch.atlassian.net/browse/VV-498
=> Add data and terminology on activity by type. VV-498

apps/fishing-map/features/app/analytics.hooks.ts, apps/port-labeler/features/app/analytics.hooks.ts, apps/vessel-history/features/app/analytics.hooks.ts
https://globalfishingwatch.atlassian.net/browse/VV-438
=> Remove User-Id from the values sent to Google Analytics from the apps VV-438

apps/port-labeler/features/search/Search.module.css, apps/port-labeler/features/search/Search.tsx, apps/port-labeler/features/search/search.hooks.ts, apps/port-labeler/features/sidebar/SidebarHeader.tsx, apps/port-labeler/features/table-anchorage/TableRow.tsx
https://globalfishingwatch.atlassian.net/browse/LABELER-126
=> As a user I want to search for a port or anchorage both in country or global view LABELER-126

apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/features/datasets/NewDatasetTooltip.tsx, apps/fishing-map/features/download/DownloadActivityModal.tsx, apps/fishing-map/features/workspace/Workspace.module.css, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/environmental/EnvironmentalLayerPanel.tsx, apps/fishing-map/features/workspace/events/EventsLayerPanel.tsx, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, libs/api-client/src/api-client.ts
=> User feedback improvements

apps/fishing-map/features/analysis/analysisDescription.hooks.ts, apps/fishing-map/features/app/app.selectors.ts, apps/fishing-map/features/map/popups/EnvironmentLayers.tsx
=> Fishing map/guide screenshots feedback

apps/fishing-map/package.json, apps/tile-inspector/package.json, apps/vessel-history/package.json, libs/layer-composer/package.json, libs/timebar/package.json, libs/ui-components/package.json, package.json, yarn.lock
This reverts commit 293b4cd809b573348007374af14d6af3ca3bd572.
=> Revert d3 dependencies update breaking tests

apps/vessel-history/features/search/search.utils.ts
https://globalfishingwatch.atlassian.net/browse/VV-510
* Fixed merged vessel name in search results displays different name compared to Info Tab
=> Fixed merged vessel name in search results. VV-510

apps/vessel-history/features/activity-by-type/activity-by-type.selectors.ts, apps/vessel-history/features/vessels/activity/vessels-activity.selectors.ts
https://globalfishingwatch.atlassian.net/browse/VV-426?focusedCommentId=18047
=> Display start or end anchorage port name when intermediate is empty. VV-426

apps/vessel-history/features/profile/Profile.tsx, apps/vessel-history/features/risk-summary/risk-summary.tsx
https://globalfishingwatch.atlassian.net/browse/VV-507
=> Display risk summary tab for Port inspectors. VV-507

apps/vessel-history/features/vessel-list-item/VesselListItem.tsx
https://globalfishingwatch.atlassian.net/browse/VV-511
=> Remove trailing number in offline vessels name.VV-511

apps/vessel-history/features/activity-by-type/activity-by-type.selectors.ts, apps/vessel-history/features/vessels/activity/vessels-activity.selectors.ts
https://globalfishingwatch.atlassian.net/browse/VV-426
This PR addresses PR comments on #1745
=> Prevent app crash when intermediateAnchorage is undefined. VV-426

apps/vessel-history/data/config.ts, apps/vessel-history/features/date-range-label/date-range-label.tsx
https://globalfishingwatch.atlassian.net/browse/VV-508
=> Fixed risk summary time range excluding data delay. VV-508

apps/fishing-map/features/workspace/activity/ActivitySection.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaSection.tsx, apps/fishing-map/features/workspace/detections/DetectionsSection.tsx, apps/fishing-map/features/workspace/environmental/EnvironmentalSection.tsx, apps/fishing-map/features/workspace/events/EventsSection.tsx, apps/fishing-map/features/workspace/vessels/VesselsSection.tsx
=> Remove section headers from screenshots

apps/vessel-history/features/activity-by-type/activity-by-type.tsx, apps/vessel-history/features/profile/components/activity/Activity.module.css, apps/vessel-history/features/risk-indicator/risk-indicator.module.css
https://globalfishingwatch.atlassian.net/browse/VV-512
=> Tweak main port visits style. VV-512

apps/fishing-map/features/dataviews/dataviews.selectors.ts, apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/download/download.utils.ts, apps/fishing-map/public/locales/source/translations.json
Disable download group by mmsi when not available in every related vessel datasets
=> Fishing map/mmsi reports download

apps/fishing-map/features/app/App.module.css, apps/fishing-map/features/footer/Footer.tsx, apps/fishing-map/features/map/Map.tsx
=> Fishing map/mobile tweaks

apps/fishing-map/features/sidebar/CategoryTabs.tsx, apps/fishing-map/features/sidebar/WhatsNew.module.css, apps/fishing-map/features/sidebar/WhatsNew.tsx, apps/fishing-map/package.json, apps/fishing-map/public/locales/source/translations.json
=> Add a hint to WhatsNew when viewing a new major or minor version

apps/vessel-history/features/home/Home.tsx, apps/vessel-history/features/search/AdvancedSearch.tsx, apps/vessel-history/features/search/SearchPlaceholders.tsx, apps/vessel-history/features/search/search.selectors.ts, apps/vessel-history/features/search/search.slice.ts, apps/vessel-history/features/search/search.thunk.ts, apps/vessel-history/public/locales/source/translations.json
https://globalfishingwatch.atlassian.net/browse/VV-451
=> Improve the landing page during vessel searches in vessel viewer // VV-451

apps/fishing-map/features/dataviews/dataviews.slice.ts, apps/vessel-history/features/datasets/datasets.slice.ts, apps/vessel-history/features/dataviews/dataviews.config.ts, apps/vessel-history/features/dataviews/dataviews.selectors.ts, apps/vessel-history/features/dataviews/dataviews.slice.ts, apps/vessel-history/features/dataviews/dataviews.utils.ts, libs/api-types/src/dataviews.ts, libs/dataviews-client/src/resolve-dataviews.ts
cherry-picking changes from https://github.com/GlobalFishingWatch/frontend/pull/1702 to avoid commits duplication after rebases
=> Load and consume VV dataviews by slug

apps/vessel-history/features/vessel-list-item/components/RelatedVesselListItem.tsx, apps/vessel-history/public/locales/en/translations.json, apps/vessel-history/public/locales/source/translations.json
https://globalfishingwatch.atlassian.net/browse/VV-489
=> update reference from "AIS transmissions" to "AIS positions" in line with change in search result in VV-489

apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx
=> Allow users to change the color of activity layers

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/map/controls/MapSearch.module.css, apps/fishing-map/features/workspace/environmental/EnvironmentalLayerPanel.tsx, apps/fishing-map/features/workspace/shared/DatasetSchemaField.tsx
=> Fishing map/gee feedback

apps/vessel-history/features/activity-by-type/activity-by-type.tsx, apps/vessel-history/features/profile/Profile.tsx, apps/vessel-history/features/risk-identity-indicator/risk-identity-indicator.tsx, apps/vessel-history/features/risk-indicator/risk-indicator.tsx, apps/vessel-history/features/risk-iuu-indicator/risk-iuu-indicator.tsx, apps/vessel-history/features/risk-summary/risk-summary.tsx
https://globalfishingwatch.atlassian.net/browse/VV-513
=> Track VV clicks in Activity by Type and Risk Summary tabs VV-513 

apps/vessel-history/features/vessels/activity/vessels-activity.selectors.ts
https://globalfishingwatch.atlassian.net/browse/VV-525
=> avoid ezz regions without id VV-525

apps/api-portal/project.json, apps/fishing-map/project.json, apps/port-labeler/project.json, apps/vessel-history/project.json
Testing to skip the export step in builds
=> dont export fishing-map app

apps/fishing-map/data/dataviews.md, apps/fishing-map/features/map/popups/ContextLayers.tsx
=> Release 1212(2)

apps/vessel-history/features/profile/components/Info.tsx, apps/vessel-history/public/locales/en/translations.json
https://globalfishingwatch.atlassian.net/browse/VV-531
=> AIS Positions not displayed on merged vessels in the INFO Tab VV-531

apps/vessel-history/features/dataviews/dataviews.config.ts, apps/vessel-history/features/map/Map.tsx, apps/vessel-history/features/map/map-events.hooks.ts, apps/vessel-history/features/map/popups/Popup.module.css, apps/vessel-history/features/map/popups/PopupWrapper.tsx
https://globalfishingwatch.atlassian.net/browse/VV-477
=> add click tooltip to VV map to show region names VV-477

apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx, apps/fishing-map/features/vessel-groups/VesselGroupModalVessels.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts
Release https://github.com/GlobalFishingWatch/frontend/pull/1860 to prod
=> fetch vessel groups by group id

apps/fishing-map/features/analysis/Analysis.module.css, apps/fishing-map/features/analysis/Analysis.tsx, apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/download/DownloadActivityProductsBanner.tsx, apps/fishing-map/features/download/DownloadModal.module.css, apps/fishing-map/features/modals/Modals.tsx, apps/fishing-map/features/welcome/SourceSwitch.content.ts, apps/fishing-map/features/welcome/WelcomeSourceSwitch.tsx
=> Add messages alerting of the 2023 AIS source change

apps/fishing-map/features/analysis/Analysis.module.css, apps/fishing-map/features/analysis/Analysis.tsx, apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/download/DownloadActivityProductsBanner.tsx, apps/fishing-map/features/download/DownloadModal.module.css, apps/fishing-map/features/modals/Modals.tsx, apps/fishing-map/features/welcome/SourceSwitch.content.ts, apps/fishing-map/features/welcome/WelcomeSourceSwitch.tsx
Deploying https://github.com/GlobalFishingWatch/frontend/pull/1868 to production
=> Fishing map/source switch messages

apps/fishing-map/features/welcome/SourceSwitch.content.ts
=> new translations

apps/fishing-map/features/welcome/SourceSwitch.content.ts
=> add new translations

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, libs/dataviews-client/src/resolve-dataviews-generators.ts
Add filters for context layers based on dataset schema:
=> Fishing map/context layers filtering

libs/layer-composer/src/generators/heatmap/util/get-time-chunks-interval.ts, libs/layer-composer/src/generators/heatmap/util/time-chunks.ts
Release https://github.com/GlobalFishingWatch/frontend/pull/1882 into production
=> fix fallback option when omited datasets

apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/vessel-groups/VesselGroupModalVessels.tsx, apps/vessel-history/features/vessel-list-item/VesselListItem.tsx, apps/vessel-history/features/vessel-list-item/components/RelatedVesselListItem.tsx, libs/ui-components/src/transmissions-timeline/TransmissionsTimeline.module.css, libs/ui-components/src/transmissions-timeline/TransmissionsTimeline.tsx
=> Update transmissions timeline

.yarnrc.yml, apps/api-portal/Dockerfile, apps/api-portal/cloudbuild.yaml, apps/deck-playground/cloudbuild.yaml, apps/fishing-map/Dockerfile, apps/fishing-map/cloudbuild.yaml, apps/port-labeler/Dockerfile, apps/port-labeler/cloudbuild.yaml, apps/vessel-history/Dockerfile, apps/vessel-history/cloudbuild.yaml, apps/vessel-history/next.config.js, cloudbuild.yaml, package.json
upgrade the node versions and yarn version in the deploy
=> Upgrade cloud build ENG-444

apps/fishing-map/pages/index.tsx
Reverts GlobalFishingWatch/frontend#1910
=> Revert "change page description for marine manager"

apps/fishing-map/features/analysis/analysis.hooks.ts, apps/fishing-map/features/areas/areas.slice.ts, apps/fishing-map/features/dataviews/dataviews.utils.ts, apps/fishing-map/features/map/popups/ContextLayers.hooks.ts, apps/fishing-map/features/reports/reports.hooks.ts, libs/api-types/src/datasets.ts
Blocked by https://github.com/GlobalFishingWatch/api-datasets/pull/86
=> read endpoint pathTemplate to retrieve context feature

apps/fishing-map/features/map/popups/ContextLayers.tsx
Fixes MPAs tooltips with: https://github.com/GlobalFishingWatch/gfw-terraform-api/pull/92
=> show name for mpa tooltips

apps/fishing-map/features/map/map-sources.hooks.ts, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts
WIP: fixing timebar missing updates
=> Fishing map/timebar hotfix

apps/fishing-map/features/download/downloadTrack.config.ts, apps/fishing-map/features/download/downloadTrack.slice.ts
Uses new `geojson` format to download directly the track without pagination.
=> fix track download format

apps/fishing-map/features/map/map-sources.hooks.ts, apps/fishing-map/features/map/map-sources.utils.ts, apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/map/popups/ContextLayersRow.tsx, apps/fishing-map/features/reports/title/ReportTitle.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/context-areas/context.utils.ts, apps/fishing-map/features/workspace/shared/LayerPanel.module.css, apps/fishing-map/public/locales/source/translations.json, libs/layer-composer/src/generators/context/config.ts, libs/layer-composer/src/generators/context/context-layers.ts, libs/layer-composer/src/generators/context/context.ts, libs/layer-composer/src/generators/context/context.utils.ts, libs/layer-composer/src/generators/index.ts, libs/layer-composer/src/generators/types.ts
=> Fishing map/dynamic reports closest areas

apps/fishing-map/features/reports/reports.selectors.ts, apps/fishing-map/features/reports/summary/ReportSummary.tsx, apps/fishing-map/features/reports/summary/ReportSummaryTags.tsx, apps/fishing-map/features/reports/vessels/ReportVessels.tsx, apps/fishing-map/public/locales/source/translations.json
Polish unknown vessels in detections:
=> Fishing map/dynamic reports unkown detection vessels

apps/fishing-map/features/app/app.selectors.ts, apps/fishing-map/features/reports/Report.module.css, apps/fishing-map/features/reports/Report.tsx, apps/fishing-map/features/reports/placeholders/ReportVesselsPlaceholder.tsx, apps/fishing-map/features/reports/reports.hooks.ts, apps/fishing-map/features/reports/reports.selectors.ts, apps/fishing-map/features/reports/reports.slice.ts, apps/fishing-map/features/reports/summary/ReportSummary.tsx, apps/fishing-map/public/locales/source/translations.json
Report update on demand after timebar changes
TODO:
=> Fishing map/dynamic reports update report button

apps/fishing-map/features/map/popups/ContextLayers.hooks.ts, apps/fishing-map/features/reports/placeholders/ReportActivityPlaceholder.tsx, apps/fishing-map/features/reports/placeholders/ReportSummaryPlaceholder.tsx, apps/fishing-map/features/reports/placeholders/ReportSummaryTagsPlaceholder.tsx, apps/fishing-map/features/reports/placeholders/ReportTitlePlaceholder.tsx, apps/fishing-map/features/reports/placeholders/ReportVesselsPlaceholder.tsx, apps/fishing-map/features/reports/placeholders/placeholders.module.css, apps/fishing-map/features/reports/reports-timeseries.utils.ts, apps/fishing-map/features/reports/reports.hooks.ts, apps/fishing-map/features/reports/reports.selectors.ts, apps/fishing-map/features/reports/reports.slice.ts, apps/fishing-map/features/reports/title/ReportTitle.tsx, apps/fishing-map/features/reports/vessels/ReportVesselsGraph.tsx, apps/fishing-map/features/reports/vessels/ReportVesselsGraphSelector.tsx, apps/fishing-map/features/reports/vessels/ReportVesselsTable.module.css, apps/fishing-map/features/reports/vessels/ReportVesselsTable.tsx, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/public/locales/source/translations.json, apps/fishing-map/routes/routes.middlewares.ts, apps/fishing-map/types/index.ts
=> Friday 24 almost final tweaks

libs/data-transforms/src/csv-to-track-segments/guessColumns.ts, libs/layer-composer/src/generators/types.ts, libs/layer-composer/src/generators/user-points/user-points.ts
=> Fishing map/points layers review

apps/fishing-map/features/datasets/NewDatasetTooltip.tsx, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/map/controls/MapInfo.module.css, apps/fishing-map/features/map/controls/MapInfo.tsx, apps/fishing-map/features/map/controls/MiniGlobeInfo.tsx, apps/fishing-map/features/user/UserDatasets.tsx, apps/fishing-map/features/user/UserVesselGroups.tsx, apps/fishing-map/features/user/UserWorkspaces.tsx, apps/fishing-map/features/user/UserWorkspacesPrivate.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.hooks.ts, apps/fishing-map/features/vessel-groups/vessel-groups.utils.ts, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/workspace.utils.ts
[Add sexagesimal coordinates to MapInfo](https://github.com/GlobalFishingWatch/frontend/commit/c844b316d18299cd94d13dbbe0f1c0cad62c747b)
[show a 🔒 in private workspaces label](https://github.com/GlobalFishingWatch/frontend/commit/1e2bfe2e5b380d9c2b73c313129e7d97c8da14ae)
[show a 🔒 in private datasets label](https://github.com/GlobalFishingWatch/frontend/commit/72b9ab869b5ad9f6f15188347d327f37bb8f3278)
[show a 🔒 in private vessel groups label](https://github.com/GlobalFishingWatch/frontend/pull/1981/commits/a1a1d71230e35a59e997ad7ce7b99f203c05cac6)
=> Fishing map/usability tweaks

apps/fishing-map/features/datasets/datasets.hook.ts, apps/fishing-map/features/user/UserDatasets.tsx, apps/fishing-map/features/user/UserVesselGroups.tsx, apps/fishing-map/features/user/UserWorkspacesPrivate.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/public/locales/source/translations.json, apps/fishing-map/routes/routes.middlewares.ts, apps/fishing-map/utils/dates.ts, libs/api-types/src/vesselGroups.ts
Adds a new arrow icon to see the selected dataset in the current workspace. (If there isn't one, it will use the default one)
=> add user dataset to current workspace in user panel

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/workspace.slice.ts
Cherry picking https://github.com/GlobalFishingWatch/frontend/pull/1997 to prod
=> Fetch only datasets defined in dataview

apps/fishing-map/features/datasets/datasets.utils.ts
=> Fishing map/hotfix missing mm datasets

apps/vessel-history/README.md, apps/vessel-history/cloudbuild.yaml, apps/vessel-history/data/config.ts, apps/vessel-history/features/activity-by-type/activity-by-type.tsx, apps/vessel-history/features/app/App.tsx, apps/vessel-history/features/datasets/datasets.slice.ts, apps/vessel-history/features/dataviews/dataviews.config.ts, apps/vessel-history/features/dataviews/dataviews.selectors.ts, apps/vessel-history/features/dataviews/dataviews.slice.ts, apps/vessel-history/features/dataviews/dataviews.utils.ts, apps/vessel-history/features/home/Home.tsx, apps/vessel-history/features/map/map.selectors.ts, apps/vessel-history/features/profile/Profile.tsx, apps/vessel-history/features/profile/components/activity/ActivityModalContentDetailsGap.tsx, apps/vessel-history/features/psma/psma.selectors.ts, apps/vessel-history/features/psma/psma.slice.ts, apps/vessel-history/features/regions/regions.slice.ts, apps/vessel-history/features/resources/resources.utils.ts, apps/vessel-history/features/risk-indicator/risk-indicator.hook.ts, apps/vessel-history/features/risk-indicator/risk-indicator.slice.ts, apps/vessel-history/features/search/search.thunk.ts, apps/vessel-history/features/user/user.hooks.ts, apps/vessel-history/features/user/user.slice.ts, apps/vessel-history/features/vessels/activity/vessels-activity.selectors.ts, apps/vessel-history/features/vessels/sources/gfw.slice.ts, apps/vessel-history/features/vessels/sources/tmt.slice.ts, apps/vessel-history/http-client/http-client.ts, apps/vessel-history/types/index.ts, libs/api-types/src/events.ts
https://globalfishingwatch.atlassian.net/browse/VV-550
=> Make a Blueprint version of the Vessel Viewer // VV-550

apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/reports/Report.tsx, apps/fishing-map/features/reports/reports.hooks.ts, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/features/user/UserReports.tsx, apps/fishing-map/features/user/UserWorkspaces.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/routes/routes.hook.ts, apps/fishing-map/routes/routes.middlewares.ts, apps/fishing-map/routes/routes.ts
Replace report close button with a new edit button to navigate to the workspace
=> Fishing map/close report button

apps/fishing-map/data/config.ts, apps/fishing-map/features/app/app.selectors.ts, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/dataviews/dataviews.selectors.ts, apps/fishing-map/features/dataviews/dataviews.slice.ts, apps/fishing-map/features/reports/activity/ReportActivityPeriodComparisonGraph.tsx, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, libs/timebar/src/utils/index.js
Fixes https://github.com/GlobalFishingWatch/frontend/pull/2012 using endDate of datasets active in the workspace
=> Fishing map/latest data available from datasets. MAP-1160

apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/user/UserInfo.tsx, apps/fishing-map/features/user/UserWorkspaces.tsx, apps/fishing-map/features/vessel/Vessel.tsx, apps/fishing-map/features/vessel/VesselEvents.tsx, apps/fishing-map/features/vessel/Vesseldentity.tsx, apps/fishing-map/features/vessel/vessel.slice.ts, apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx, apps/fishing-map/features/workspace/workspace.selectors.ts, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/next.config.js, apps/fishing-map/pages/[category]/[workspace]/vessel/[datasetId]/[vesselId].tsx, apps/fishing-map/routes/routes.actions.ts, apps/fishing-map/routes/routes.hook.ts, apps/fishing-map/routes/routes.middlewares.ts
Navigating only in client side is the best option we have for now
=> use redux-first-router to navigate to vessel-profile

apps/fishing-map/data/config.ts, apps/fishing-map/features/workspace/highlight-panel/highlight-panel.content.ts
https://globalfishingwatch.atlassian.net/browse/VMS-37
=> Fix production environment detection to show highlight poup. VMS-37

apps/fishing-map/features/user/user.slice.ts
https://globalfishingwatch.atlassian.net/browse/VMS-37
=> Include PNG in the private WS list. VMS-37

apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/map/map.slice.ts, apps/fishing-map/features/map/popups/VesselsTable.module.css, apps/fishing-map/features/map/popups/VesselsTable.tsx, apps/fishing-map/features/reports/NewReportModal.tsx, apps/fishing-map/features/reports/Report.module.css, apps/fishing-map/features/reports/Report.tsx, apps/fishing-map/features/reports/reports.slice.ts, apps/fishing-map/features/reports/vessels/ReportVesselsTable.module.css, apps/fishing-map/features/search/SearchPlaceholders.module.css, apps/fishing-map/features/search/SearchPlaceholders.tsx, apps/fishing-map/features/user/User.module.css, apps/fishing-map/features/user/UserReports.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/public/locales/source/translations.json
=> Fishing map/release tweaks

apps/fishing-map/features/user/user.slice.ts
https://globalfishingwatch.atlassian.net/browse/MAP-1171
=> Display Costa Rica en private workspaces list. MAP-1171

apps/fishing-map/features/user/user.slice.ts
https://globalfishingwatch.atlassian.net/browse/VMS-7
=> Include Chile in the list of private workspaces. VMS-7

apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/features/workspace/highlight-panel/highlight-panel.content.ts
https://globalfishingwatch.atlassian.net/browse/VMS-46
=> Display highlight popup on PNG release and default datasets. VMS-46

apps/fishing-map/features/workspace/highlight-panel/highlight-panel.content.ts
https://globalfishingwatch.atlassian.net/browse/VMS-46
=> Fix PNG highlight popup translation. VMS-46 

apps/fishing-map/features/feedback/FeedbackModal.tsx, apps/fishing-map/features/sidebar/CategoryTabs.module.css, apps/fishing-map/features/sidebar/CategoryTabs.tsx, apps/fishing-map/public/locales/source/translations.json
=> add canny to feedback options

apps/fishing-map/features/download/DownloadActivityModal.tsx, apps/fishing-map/features/map/map.slice.ts, apps/fishing-map/features/reports/summary/ReportSummary.tsx, libs/react-hooks/src/use-map-interaction/use-map-interaction.ts
=> Fishing map/map interaction review

apps/fishing-map/features/app/analytics.hooks.ts
Including https://github.com/GlobalFishingWatch/frontend/pull/2110 into fishing-map
=> use snake_case for ga4 properties

apps/fishing-map/features/app/analytics.hooks.ts, apps/fishing-map/pages/_document.tsx
Add the changes in https://github.com/GlobalFishingWatch/frontend/pull/2115/files
=> update analytis setup

apps/real-time-prototype/features/map/Map.tsx, apps/real-time-prototype/features/sidebar/VesselsSection.tsx, apps/real-time-prototype/layers/basemap/BasemapLayer.ts
=> real-time-prototype tasks

apps/fishing-map/features/vessel/activity/VesselActivitySummary.tsx, apps/fishing-map/features/vessel/identity/VesselIdentity.tsx, apps/fishing-map/features/vessel/identity/VesselIdentityField.module.css, apps/fishing-map/features/vessel/identity/VesselIdentityField.tsx
https://github.com/GlobalFishingWatch/frontend/assets/10500650/f93cae02-1a7f-4fa1-81b3-a4ca0bea3f67
=> highlight identity field change

apps/fishing-map-e2e/cypress.config.ts, apps/fishing-map-e2e/src/constants/urls.ts, apps/fishing-map-e2e/src/e2e/app.cy.ts, apps/fishing-map-e2e/src/e2e/fishing-activity/vms.cy.ts, apps/fishing-map-e2e/src/e2e/login.cy.ts, apps/fishing-map-e2e/src/e2e/map/map.cy.ts, apps/fishing-map-e2e/src/support/app.po.ts, apps/fishing-map-e2e/src/support/commands.ts, libs/timebar/src/components/timeline.js
https://github.com/GlobalFishingWatch/frontend/assets/1672451/79f3c950-c1ba-4a6d-91b9-4d386f3d8bf0
=> added test for the map, vessels api, and others

apps/fishing-map/features/timebar/timebar.selectors.ts, apps/fishing-map/features/workspace/environmental/EnvironmentalSection.tsx, apps/fishing-map/features/workspace/shared/Sections.module.css, apps/fishing-map/public/locales/source/translations.json, libs/data-transforms/src/segments/index.ts, libs/data-transforms/src/segments/segments-to-geojson.ts
=> Fishing map/small things to release

apps/fishing-map/features/app/App.tsx, apps/fishing-map/features/datasets/datasets.mock.ts, apps/fishing-map/features/datasets/datasets.slice.ts, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/dataviews/dataviews.mock.ts, apps/fishing-map/features/map/map.slice.ts, apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/search/SearchBasic.tsx, apps/fishing-map/features/search/SearchBasicResultList.tsx, apps/fishing-map/features/vessel/Vessel.tsx, apps/fishing-map/features/vessel/VesselHeader.tsx, apps/fishing-map/features/vessel/VesselLink.tsx, apps/fishing-map/features/vessel/vessel.config.ts
=> Fishing map/search identity fixes

apps/fishing-map/features/regions/regions.hooks.ts, apps/fishing-map/features/vessel/activity/VesselActivitySummary.tsx, apps/fishing-map/features/vessel/activity/event/ActivityDate.tsx, apps/fishing-map/features/vessel/activity/event/Event.tsx, apps/fishing-map/features/vessel/activity/event/EventDetail.tsx, apps/fishing-map/features/vessel/activity/event/event.hook.tsx, apps/fishing-map/features/vessel/identity/VesselIdentity.module.css, apps/fishing-map/features/vessel/identity/VesselIdentity.tsx, apps/fishing-map/features/vessel/identity/VesselIdentityField.tsx
=> Fishing map/show authorizations translations

apps/fishing-map-e2e/src/constants/vms.ts
Brazil Open Tuna Presence is no longer present in the VMS list
=> remove Brazil Open Tuna Presence

apps/fishing-map-e2e/cypress.config.ts, apps/fishing-map-e2e/src/constants/buttons.ts, apps/fishing-map-e2e/src/constants/search.ts, apps/fishing-map-e2e/src/constants/urls.ts, apps/fishing-map-e2e/src/e2e/map/analysis.cy.ts, apps/fishing-map-e2e/src/e2e/map/eez-download.cy.ts, apps/fishing-map-e2e/src/support/app.po.ts, apps/fishing-map-e2e/src/support/commands.ts, apps/fishing-map-e2e/src/support/map/eez-download.po.ts, apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/download/DownloadActivityModal.tsx, apps/fishing-map/features/map/popups/ContextLayersRow.tsx, apps/fishing-map/package.json, libs/ui-components/src/choice/Choice.tsx, libs/ui-components/src/tabs/Tabs.tsx, libs/ui-components/src/tabs/index.ts, libs/ui-components/src/tag/Tag.tsx, yarn.lock
https://globalfishingwatch.atlassian.net/browse/MAP-1219
https://github.com/GlobalFishingWatch/frontend/assets/1672451/33b6a891-106c-427a-982c-271809b91d56
=> Download visible activity layer for selected area // MAP-1219

apps/vessel-history/README.md
Added license and attribution details
=> Update README.md to include license

apps/fishing-map/data/default-workspaces/context-layers.ts, apps/fishing-map/data/default-workspaces/marine-manager.ts, apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/features/dataviews/dataviews.slice.ts, apps/fishing-map/features/vessel/Vessel.tsx, apps/fishing-map/features/vessel/activity/vessels-activity.selectors.ts, apps/fishing-map/features/vessel/areas/VesselAreas.tsx, apps/fishing-map/features/workspace/workspace.hook.ts
=> Fishing map/context areas in standalone vessel

apps/fishing-map/features/search/basic/SearchBasicResult.tsx, apps/fishing-map/features/vessel/Vessel.tsx, apps/fishing-map/features/vessel/VesselHeader.tsx, apps/fishing-map/features/vessel/VesselLink.tsx, apps/fishing-map/features/vessel/identity/VesselIdentitySelector.tsx, apps/fishing-map/features/vessel/vessel-bounds.hooks.ts, apps/fishing-map/features/vessel/vessel.hooks.ts, apps/fishing-map/features/vessel/vessel.slice.ts, apps/fishing-map/features/vessel/vessel.utils.ts
Fit to vessel bounds on internal links
=> Fishing map/profile fit bounds

apps/fishing-map/features/download/downloadTrack.slice.ts, apps/fishing-map/package.json, apps/fishing-map/public/tracks-download/README.md, yarn.lock
Temporary workaround until api endpoints are ready to include readme.md file in downloaded tracks
=> feat: include readme file for download track zip

apps/fishing-map/features/bigquery/BigQuery.tsx, apps/fishing-map/features/datasets/DatasetConfig.tsx, apps/fishing-map/features/datasets/EditDataset.tsx, apps/fishing-map/features/editor/DataviewEditor.tsx, apps/fishing-map/features/feedback/FeedbackModal.module.css, apps/fishing-map/features/map/MapDraw.tsx, apps/fishing-map/features/map/controls/MapSearch.module.css, apps/fishing-map/features/reports/NewReportModal.tsx, apps/fishing-map/features/reports/activity/ReportActivityBeforeAfter.module.css, apps/fishing-map/features/reports/vessels/ReportVesselsFilter.module.css, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/features/workspace/activity/ActivityFilters.module.css, apps/fishing-map/features/workspace/shared/NewWorkspaceModal.tsx, apps/fishing-map/features/workspaces-list/WorkspaceWizard.module.css, libs/timebar/src/components/timerange-selector.module.css, libs/ui-components/src/base.css, libs/ui-components/src/button/Button.module.css, libs/ui-components/src/input-text/InputText.module.css, libs/ui-components/src/multi-select/MultiSelect.module.css, libs/ui-components/src/select/Select.module.css, libs/ui-components/src/tabs/Tabs.module.css
=> Update input and button styles

apps/fishing-map/features/map/MapDraw.tsx, apps/fishing-map/features/map/MapDrawControl.tsx, apps/fishing-map/package.json, yarn.lock
Fixes coordinates selection, but I can't still understand why the default `useState` doesn't work
=> use recoil to store drawing coordinate position

apps/fishing-map/features/app/App.tsx, apps/fishing-map/features/map/Map.tsx, apps/fishing-map/features/map/controls/MapControls.tsx, apps/fishing-map/features/map/controls/MapSearch.tsx, apps/fishing-map/features/map/map-bounds.hooks.ts, apps/fishing-map/features/map/map-context.hooks.ts, apps/fishing-map/features/map/map-viewport.hooks.ts, apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/map/popups/ContextLayers.hooks.ts, apps/fishing-map/features/reports/reports.hooks.ts, apps/fishing-map/features/sidebar/CategoryTabs.tsx, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts, apps/fishing-map/features/user/UserWorkspaces.tsx, apps/fishing-map/features/user/UserWorkspacesPrivate.tsx, apps/fishing-map/features/workspace/activity/ActivityFitBounds.tsx, apps/fishing-map/features/workspace/common/FitBounds.tsx, apps/fishing-map/features/workspace/environmental/environmental.hooks.ts, apps/fishing-map/features/workspace/environmental/histogram.hooks.ts, apps/fishing-map/features/workspace/events/events.hooks.ts, apps/fishing-map/features/workspaces-list/WorkspaceWizard.tsx, apps/fishing-map/features/workspaces-list/WorkspacesList.tsx, apps/fishing-map/hooks/screen.hooks.ts, apps/fishing-map/types/index.ts, apps/fishing-map/utils/url.ts, apps/fourwings-explorer/features/analysis/analysis.area.hooks.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapTileLayer.ts, libs/layer-composer/src/generators/heatmap/util/colors.ts
=> Deck migration/mapbox dependencies clean up review

apps/fishing-map/features/vessel/vessel.slice.ts, apps/fishing-map/features/vessel/vessel.utils.ts, apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx, apps/fishing-map/utils/info.ts, libs/api-types/src/identity-vessel.ts
Reverts GlobalFishingWatch/frontend#2299
=> Revert "Fishing map/new geartype format"

apps/fishing-map/features/reports/Report.tsx, apps/fishing-map/features/reports/reports.hooks.ts
This PR updates highlighting for report areas letting the update to be aware of reportBufferHash and moving the logic to happen on report area update
=> fishing-map/buffer-highlight-issues

apps/api-portal/app/robots.ts, apps/api-portal/components/layout.tsx, apps/api-portal/next.config.js, apps/api-portal/package.json, apps/api-portal/public/robots.txt
https://globalfishingwatch.atlassian.net/browse/MAP-1252
=> MAP-1252. Set noindex on api-portal

apps/fishing-map/features/dataviews/dataviews.utils.ts, apps/fishing-map/features/download/DownloadTrackModal.tsx, apps/fishing-map/features/download/downloadTrack.config.ts, apps/fishing-map/features/download/downloadTrack.slice.ts, apps/fishing-map/features/modals/Modals.tsx, apps/fishing-map/features/vessel/VesselHeader.tsx, apps/fishing-map/features/vessel/vessel.selectors.ts, apps/fishing-map/features/vessel/vessel.slice.ts, apps/fishing-map/features/workspace/vessels/VesselDownload.tsx, apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx
=> Fishing map/vessel profile download

apps/fishing-map/features/app/app.selectors.ts, apps/fishing-map/features/map/popups/ContextLayersRow.tsx, apps/fishing-map/features/reports/reports.selectors.ts, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/features/workspace/workspace.slice.ts
This PR fixes the issues when a buffered area report is saved
=> Fishing map/report save buffer params

apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts
Fixes search by mmsi in vessel groups
=> fix search by mmsi in vessel groups

apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts
Invalidates cache for searching vessels with in the group
=> fix vessel groups cache

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/features/workspace/environmental/EnvironmentalLayerPanel.tsx, apps/fishing-map/features/workspace/environmental/UserTrackLayerPanel.tsx, apps/fishing-map/features/workspace/events/EventsLayerPanel.tsx, apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/public/locales/source/translations.json
=> Fishing map bugs review

apps/vessel-history/next.config.js, apps/vessel-history/package.json, apps/vessel-history/pages/_document.tsx, apps/vessel-history/public/robots.txt
https://globalfishingwatch.atlassian.net/browse/VV-576
=> VV-576 Add no-index tag to VV

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/dataviews/dataviews.utils.ts, apps/fishing-map/features/workspace/workspace.selectors.ts, libs/dataviews-client/src/resolve-dataviews.ts, libs/dataviews-client/src/resolve-endpoint.ts, libs/dataviews-client/src/resources/get-resources.ts, libs/dataviews-client/src/url-workspace/migrations.config.ts, libs/dataviews-client/src/url-workspace/migrations.ts, libs/dataviews-client/src/url-workspace/url-workspace.ts
Support loading tracks from different dataset than the configured in the dataview datasetConfig
Pending confirmation for the same with event datasets
=> fix loading legacy track data

apps/fishing-map/features/map/map.slice.ts
Fixes https://globalfishingwatch.slack.com/archives/C0296TY92KC/p1699458761268049
=> fix missing name in cell interaction click

apps/fishing-map/features/timebar/timebar.selectors.ts, apps/fishing-map/features/user/UserLoggedIconButton.tsx, libs/data-transforms/src/track-value-array-to-segments/track-value-array-to-segments.ts
Fixes https://globalfishingwatch.slack.com/archives/C0296TY92KC/p1699461460582249
=> Fishing map/fix vessel graph

apps/vessel-history/features/dataviews/dataviews.config.ts, apps/vessel-history/features/map/Map.tsx, apps/vessel-history/features/map/controls/MapControls.tsx, apps/vessel-history/public/locales/source/translations.json, libs/api-types/src/datasets.ts
https://globalfishingwatch.atlassian.net/browse/VV-576
=> VV-574 Add link to vv vessel in gfw map

apps/fishing-map-e2e/.env.sample, apps/fishing-map-e2e/cloudbuild.yaml, apps/fishing-map-e2e/src/constants/buttons.ts, apps/fishing-map-e2e/src/constants/urls.ts, apps/fishing-map-e2e/src/constants/workspace.ts, apps/fishing-map-e2e/src/e2e/map/analysis.cy.ts, apps/fishing-map-e2e/src/e2e/sidebar/save-workspace.cy.ts, apps/fishing-map-e2e/src/support/app.po.ts, apps/fishing-map-e2e/src/support/sidebar/save-workspace.po.ts, apps/fishing-map/cloudbuild.yaml, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/features/user/User.tsx, apps/fishing-map/features/user/UserButton.tsx, apps/fishing-map/features/user/UserWorkspaces.tsx, apps/fishing-map/features/workspace/Workspace.module.css, apps/fishing-map/features/workspace/Workspace.tsx, apps/fishing-map/features/workspace/shared/NewWorkspaceModal.tsx
https://globalfishingwatch.atlassian.net/browse/MAP-1220
https://github.com/GlobalFishingWatch/frontend/assets/90259114/5bc3199b-f032-49eb-95eb-3d50270b18eb
=> Create and delete new workspace test

apps/fishing-map-e2e/cloudbuild.yaml, apps/fishing-map-e2e/cypress.config.ts, apps/fishing-map/cloudbuild.yaml
save testing videos in a bucket
https://globalfishingwatch.atlassian.net/browse/ENG-564
=> Improve debug of the tests

apps/fishing-map/cloudbuild.yaml
https://globalfishingwatch.atlassian.net/browse/ENG-564
Set production url to the test when we deploy to prod
=> Improve debug of the tests - Set production url to the test when we deploy to prod // ENG-564

libs/dataviews-client/src/resolve-endpoint.ts
Fixes missing tiles in datasets created in the big query editor
=> add missing dataset in query

apps/fishing-map/features/reports/reports.selectors.ts
Fixes missing vessels summary in reports for sources without data.
=> Include report values for vessels without info

apps/fishing-map/features/app/drag-dataset.hooks.ts, apps/fishing-map/features/datasets/upload/DatasetTypeSelect.tsx, apps/fishing-map/features/datasets/upload/NewDatasetField.tsx, apps/fishing-map/features/datasets/upload/NewPointsDataset.tsx, apps/fishing-map/features/datasets/upload/NewPolygonDataset.tsx, apps/fishing-map/features/datasets/upload/NewTrackDataset.tsx, apps/fishing-map/features/datasets/upload/TimeFieldsGroup.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/shared/LayerPanel.module.css, apps/fishing-map/public/locales/source/translations.json, libs/api-types/src/datasets.ts, libs/ui-components/src/button/Button.module.css, libs/ui-components/src/button/Button.tsx, libs/ui-components/src/choice/Choice.module.css, libs/ui-components/src/choice/Choice.tsx, libs/ui-components/src/multi-select/MultiSelect.tsx, libs/ui-components/src/select/Select.module.css, libs/ui-components/src/select/Select.tsx
Additional stuff
- Make "areas on the map" block collapsable (to avoid an unnecessary long scroll that can hinder uploaded datasets section visibility)
- Tweak Time filter selection to make clearer the distinction between selecting a filter type and a dataset field
=> tasks by 1️⃣ 🚗

apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/datasets/upload/NewDataset.tsx, apps/fishing-map/features/datasets/upload/datasets-upload.utils.ts, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/timebar/timebar.selectors.ts, libs/api-types/src/datasets.ts, libs/data-transforms/src/coordinates/coordinates.ts, libs/data-transforms/src/schema/schema.ts
Expand timebar ranges based on datasets uploaded `startDate` and `endDate`
=> Fishing map/datasets timebar ranges

apps/fishing-map/features/reports/environment/ReportEnvironment.module.css, apps/fishing-map/features/reports/environment/ReportEnvironment.tsx, apps/fishing-map/features/workspace/environmental/environmental.hooks.ts
=> calculate and show stats of environmental heatmaps

apps/fishing-map/features/reports/reports-timeseries.hooks.ts, apps/fishing-map/features/reports/reports-timeseries.utils.ts, apps/fishing-map/features/workspace/environmental/environmental.hooks.ts
=> Fishing map/env reports fixes

apps/fishing-map/features/app/drag-dataset.hooks.ts, apps/fishing-map/features/map/map-interactions.hooks.ts, apps/fishing-map/features/vessel-groups/VesselGroupModal.tsx, apps/fishing-map/features/vessel-groups/vessel-groups.slice.ts, apps/fishing-map/features/workspace/user/UserLayerPanel.tsx, apps/fishing-map/public/locales/source/translations.json, libs/pbf-decoders/decoders/4wings-tile.js, libs/pbf-decoders/decoders/vessels.js
=> Fishing map/vessel groups review

apps/fishing-map/features/map/controls/MapSearch.tsx, apps/fishing-map/features/map/controls/MiniGlobeInfo.tsx, apps/fishing-map/features/search/advanced/SearchAdvanced.tsx, apps/fishing-map/features/sidebar/Sidebar.tsx, apps/fishing-map/features/workspace/context-areas/ContextAreaLayerPanel.tsx, apps/fishing-map/features/workspace/context-areas/context.utils.ts, apps/fishing-map/features/workspace/shared/NewWorkspaceModal.tsx, apps/fishing-map/features/workspaces-list/WorkspaceWizard.tsx, apps/fishing-map/next.config.js, apps/fishing-map/pages/index.tsx, libs/ocean-areas/src/ocean-areas.ts
[preview](https://fishing-map-fishing-map-reduce-initial-bundle-jzzp2ui3wq-uc.a.run.app/)
=> Fishing map/reduce initial bundle

apps/fishing-map/features/map/map.hooks.ts, libs/layer-composer/src/generators/heatmap/heatmap-static.ts, libs/layer-composer/src/generators/types.ts
=> add value filter to static heatmaps

apps/fishing-map/features/dataviews/dataviews.slice.ts, apps/fishing-map/features/workspace/environmental/EnvironmentalLayerPanel.tsx
Fixes missing tracks in workspaces
=> Fishing map/fix missing dataviews

apps/fishing-map/features/map/annotations/Annotations.tsx
https://github.com/GlobalFishingWatch/frontend/assets/6906348/00ad5725-e432-4ea6-b159-21f6493334cb
=> Avoid annotation dialog to be triggered by annotation click

apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityEnvironment.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/download/download.selectors.ts, apps/fishing-map/features/download/downloadActivity.slice.ts, apps/fishing-map/features/reports/Report.tsx, apps/fishing-map/public/locales/source/translations.json
Show feedback for users when trying to download an area too complex
=> Fishing map/geometries too large

apps/fishing-map/features/workspace/common/LayerFilters.tsx, libs/dataviews-client/src/url-workspace/url-workspace.ts
fixes https://globalfishingwatch.atlassian.net/browse/MAP-1314
=> fix legacy multiple vessel groups

apps/fishing-map/features/map/map.hooks.ts, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts, libs/dataviews-client/src/merge-dataviews.ts, libs/deck-layer-composer/src/resolvers/fourwings.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapTileLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsLayer.ts, libs/deck-layers/src/layers/fourwings/fourwings.config.ts, libs/deck-layers/src/layers/fourwings/fourwings.types.ts, libs/deck-layers/src/layers/fourwings/fourwings.utils.ts, libs/deck-layers/src/utils/colorRamps.ts, libs/deck-layers/src/utils/colors.ts, libs/layer-composer/src/generators/types.ts
=> Deck migration/fourwings improvements

apps/fishing-map/features/datasets/upload/NewDataset.tsx, apps/fishing-map/features/datasets/upload/datasets-upload.utils.ts, apps/fishing-map/features/modals/modals.slice.ts, apps/fishing-map/features/workspace/user/UserLayerPanel.tsx, libs/data-transforms/src/schema/schema.ts, libs/dataviews-client/src/resolve-dataviews.ts
=> Fishing map/fix datasets filtering

apps/fishing-map/features/dataviews/selectors/dataviews.selectors.ts, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts, libs/data-transforms/src/features/filter-features-by-bounds.ts, libs/deck-layer-composer/src/resolvers/dataviews.ts, libs/deck-layer-composer/src/resolvers/fourwings.ts, libs/deck-layer-composer/src/resolvers/index.ts, libs/deck-layers/src/layers/context/ContextLayer.ts, libs/deck-layers/src/layers/context/EEZLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapStaticLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapTileLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsLayer.ts, libs/deck-layers/src/layers/fourwings/FourwingsPositionsTileLayer.ts, libs/deck-layers/src/layers/fourwings/fourwings.config.ts, libs/deck-layers/src/layers/fourwings/fourwings.types.ts, libs/deck-layers/src/layers/fourwings/fourwings.utils.ts, libs/deck-layers/src/utils/loaders.ts, libs/deck-loaders/src/fourwings/lib/types.ts
Supports static heatmap layers like bathimetry
Pending:
=> deck heatmap static layer

apps/fishing-map/features/datasets/datasets.mock.ts, apps/fishing-map/features/datasets/datasets.utils.ts, apps/fishing-map/features/dataviews/selectors/dataviews.instances.selectors.ts, apps/fishing-map/features/map/map-bounds.hooks.ts, apps/fishing-map/features/resources/resources.utils.ts, apps/fishing-map/features/search/basic/SearchBasicResult.tsx, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/timebar/TimebarSettings.tsx, apps/fishing-map/features/timebar/timebar-vessel.hooks.ts, apps/fishing-map/features/timebar/timebar.selectors.ts, apps/fishing-map/features/workspace/common/LayerSchemaFilter.tsx, apps/fishing-map/features/workspace/shared/LayerPanel.module.css, apps/fishing-map/features/workspace/vessels/VesselLayerPanel.tsx, apps/vessel-history/features/dataviews/dataviews.selectors.ts, libs/api-types/src/dataviews.ts, libs/api-types/src/tracks.ts, libs/data-transforms/src/segments/segments-to-geojson.ts, libs/dataviews-client/src/resources/get-resources.ts, libs/deck-layer-composer/src/resolvers/dataviews.ts, libs/deck-layer-composer/src/resolvers/index.ts, libs/deck-layer-composer/src/resolvers/vessels.ts, libs/deck-layers/src/layers/fourwings/FourwingsHeatmapLayer.ts, libs/deck-layers/src/layers/vessel/VesselLayer.ts, libs/deck-layers/src/layers/vessel/VesselTrackLayer.ts, libs/deck-layers/src/layers/vessel/vessel.config.ts, libs/deck-layers/src/layers/vessel/vessel.types.ts, libs/deck-loaders/src/vessels/lib/parse-tracks.ts, libs/deck-loaders/src/vessels/lib/types.ts, libs/ui-components/src/slider/Slider.tsx
implements https://github.com/GlobalFishingWatch/frontend/pull/2456 in deckgl
https://github.com/GlobalFishingWatch/frontend/assets/10500650/715125da-0ac6-47d4-b3d1-acb28668778b
=> vessel track filters

apps/fishing-map/features/reports/NewReportModal.tsx, apps/fishing-map/features/sidebar/SidebarHeader.module.css, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/features/workspace/Workspace.module.css, apps/fishing-map/features/workspace/WorkspaceError.tsx, apps/fishing-map/features/workspace/save/WorkspaceCreateModal.tsx, apps/fishing-map/features/workspace/save/WorkspaceEdit.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/features/workspaces-list/WorkspacesList.module.css, apps/fishing-map/features/workspaces-list/WorkspacesList.tsx, apps/fishing-map/features/workspaces-list/workspaces-list.slice.ts, apps/fishing-map/public/locales/source/translations.json, libs/api-types/src/reports.ts
Pending on API to support this changes
=> support edit access in owner workspaces

apps/fishing-map/features/dataviews/selectors/dataviews.instances.selectors.ts, apps/fishing-map/features/resources/resources.selectors.thinning.ts, libs/api-client/src/utils/thinning.ts, libs/api-types/src/dataviews.ts, libs/deck-layer-composer/src/resolvers/vessels.ts, libs/deck-layers/src/layers/vessel/VesselLayer.ts, libs/deck-layers/src/layers/vessel/VesselTrackLayer.ts, libs/deck-layers/src/layers/vessel/vessel.config.ts
See [new config](https://github.com/GlobalFishingWatch/frontend/pull/2691/files#diff-a24b8096a66427274aa0eeee3ca9b725e9e97c475af509b7cb3948a2a20f2a70R19)
=> apply tracks thinning based in zoom levels

apps/fishing-map/features/reports/reports-timeseries.utils.ts, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/timebar/TimebarActivityGraph.hooks.ts, apps/fishing-map/features/timebar/timebar.selectors.ts, apps/fishing-map/features/timebar/timebar.utils.ts, libs/deck-layer-composer/src/resolvers/fourwings.ts, libs/deck-layers/src/layers/fourwings/fourwings.config.ts, libs/deck-layers/src/layers/fourwings/positions/FourwingsPositionsTileLayer.ts, libs/deck-layers/src/layers/fourwings/positions/fourwings-positions.types.ts
=> Deck migration/positions timebar

libs/data-transforms/src/list-to-track-segments/check-record-validity.ts, libs/data-transforms/src/list-to-track-segments/list-to-track-segments.ts, libs/data-transforms/src/points/points-to-geojson.ts, libs/data-transforms/src/schema/schema.ts
Include https://github.com/GlobalFishingWatch/frontend/pull/2677 in tracks too
=> fix tracks csv generation

apps/image-labeler/src/features/project/Project.module.css, apps/image-labeler/src/features/project/Project.tsx, apps/image-labeler/src/features/project/Task.module.css, apps/image-labeler/src/features/project/Task.tsx, apps/image-labeler/src/features/project/TaskImage.module.css, apps/image-labeler/src/features/project/TaskImage.tsx, apps/image-labeler/src/features/projects-list/ProjectForm.tsx, apps/image-labeler/src/features/projects-list/ProjectsList.tsx, apps/image-labeler/src/types/index.ts
=> Image labeler/feedback

apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityEnvironment.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/reports/vessels/ReportVesselsTableFooter.tsx, apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/search/SearchActions.tsx, apps/fishing-map/features/search/SearchDownload.tsx, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/vessel/activity/VesselActivityDownload.tsx, apps/fishing-map/features/vessel/identity/DataTerminology.tsx, apps/fishing-map/features/vessel/identity/VesselIdentitySelector.tsx
This PR creates some missing GA events and updates some labelling.
Check [this issue](https://globalfishingwatch.atlassian.net/browse/MAP-1325) for full context.
=> google analytics

apps/fishing-map/features/app/App.tsx, apps/fishing-map/features/timebar/timebar-vessel.hooks.ts, apps/fishing-map/features/vessel/vessel-events.hooks.ts, apps/fishing-map/features/vessel/vessel.slice.ts, apps/fishing-map/features/workspace/WorkspaceError.tsx, apps/fishing-map/features/workspace/workspace.selectors.ts, libs/deck-layers/src/layers/vessel/VesselEventsLayer.ts, libs/deck-layers/src/layers/vessel/VesselLayer.ts, libs/deck-layers/src/layers/vessel/VesselTrackLayer.ts, libs/deck-layers/src/layers/vessel/vessel.utils.ts
=> Fishing map/deck hotfixes

apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/download/DownloadActivityByVessel.tsx, apps/fishing-map/features/download/DownloadActivityEnvironment.tsx, apps/fishing-map/features/download/DownloadActivityGridded.tsx, apps/fishing-map/features/download/download.utils.ts, apps/fishing-map/features/reports/environment/ReportEnvironment.tsx, apps/fishing-map/features/search/advanced/SearchAdvanced.tsx, apps/fishing-map/features/search/basic/SearchBasic.module.css, apps/fishing-map/features/search/basic/SearchBasic.tsx, apps/fishing-map/features/search/basic/SearchError.tsx, apps/fishing-map/features/search/search.selectors.ts, apps/fishing-map/features/user/selectors/user.groups.selectors.ts, apps/fishing-map/features/user/selectors/user.permissions.selectors.ts, apps/fishing-map/features/user/user.config.ts, apps/fishing-map/features/user/user.slice.ts, apps/fishing-map/features/vessel/insights/InsightGaps.tsx, apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx, apps/fishing-map/features/workspace/common/LayerSchemaFilter.tsx, apps/fishing-map/features/workspace/workspace.slice.ts, apps/fishing-map/pages/styles.css, apps/fishing-map/public/locales/en/translations.json, libs/api-types/src/datasets.ts
Fixes the following bugs:
https://globalfishingwatch.atlassian.net/browse/MAP-1316
https://globalfishingwatch.atlassian.net/browse/MAP-1338
https://globalfishingwatch.atlassian.net/browse/MAP-1396
https://globalfishingwatch.atlassian.net/browse/VV-592
https://globalfishingwatch.atlassian.net/browse/VV-593
https://globalfishingwatch.atlassian.net/browse/VV-600
=> Fishing-map/bugs-review

apps/fishing-map/features/areas/areas.slice.ts, apps/fishing-map/features/datasets/upload/datasets-upload.utils.ts, libs/data-transforms/src/dissolve/dissolve.ts
Fixes app crash when a geometry is uploaded as `GeometryCollection`
=> Fishing map/fix area report

apps/fishing-map/features/user/user.config.ts
https://globalfishingwatch.atlassian.net/browse/MAP-1422
=> MAP-1422 Fixed private search dataset by group mapping

apps/fishing-map/features/workspace/save/WorkspaceCreateModal.tsx, apps/fishing-map/features/workspace/save/workspace-save.utils.ts, apps/fishing-map/public/locales/source/translations.json, libs/deck-layers/src/layers/vessel/VesselLayer.ts
=> Fishing map/workspace share hotfix

apps/fishing-map/features/reports/activity/reports-activity-timeseries.hooks.ts, apps/fishing-map/features/reports/activity/vessels/ReportVesselsTableFooter.tsx, apps/fishing-map/features/reports/areas/AreaReport.tsx, apps/fishing-map/features/reports/areas/environment/ReportEnvironment.tsx, apps/fishing-map/features/vessel-groups/VesselGroupAddButton.tsx, apps/fishing-map/features/vessel-groups/vessel-groups-modal.slice.ts, apps/fishing-map/features/vessel-groups/vessel-groups.hooks.ts, apps/fishing-map/features/vessel-groups/vessel-groups.utils.ts, apps/fishing-map/features/workspace/vessel-groups/VesselGroupsLayerPanel.tsx, libs/deck-layers/src/layers/fourwings/heatmap/FourwingsHeatmapTileLayer.ts
=> add vessels to group from report

apps/fishing-map/routes/routes.selectors.ts, libs/dataviews-client/src/url-workspace/url-workspace.ts, libs/deck-layers/src/layers/vessel/vessel.utils.ts, libs/deck-loaders/src/fourwings/helpers/time.ts
[Test url](http://localhost:3003/fishing-activity/default-public/vessel/a1a59b1d5-567c-bdc4-512a-a3a35bd2a319?start=2012-01-01T00%3A00%3A00.000Z&end=2024-12-31T00%3A00%3A00.000Z&longitude=-79.6455989217622&latitude=9.083076393072675&zoom=8.368648380846167&vesselDatasetId=public-global-vessel-identity%253Av3.0&vesselIdentitySource=selfReportedInfo&vesselSelfReportedId=a1a59b1d5-567c-bdc4-512a-a3a35bd2a319&timebarVisualisation=vessel&visibleEvents[0]=loitering&visibleEvents[1]=encounter&visibleEvents[2]=port_visit&vesselSection=areas&dvIn[0][id]=context-layer-rfmo&dvIn[0][cfg][vis]=false&dvIn[0][dvId]=tuna-rfmo-areas&dvIn[1][id]=context-layer-fao-areas&dvIn[1][cfg][vis]=false&dvIn[1][dvId]=fao-areas&dvIn[2][id]=context-layer-mpa&dvIn[2][cfg][vis]=false&dvIn[2][dvId]=mpa&dvIn[3][id]=context-l …
=> wip fix wrong dates format

apps/fishing-map/features/vessel/VesselLink.tsx, libs/dataviews-client/src/resolve-dataviews.ts
Fixes https://github.com/GlobalFishingWatch/frontend/commit/d53b07a2bcf1cdb005b872c51052c281137214a2
=> fix missing data on previously deleted vessel instance profile

apps/fishing-map-e2e/src/e2e/fishing-activity/vms.cy.ts, apps/fishing-map-e2e/src/e2e/login.cy.ts, apps/fishing-map-e2e/src/e2e/map/analysis.cy.ts, apps/fishing-map-e2e/src/e2e/map/eez-download.cy.ts, apps/fishing-map-e2e/src/e2e/map/interact-with-vessel.cy.ts, apps/fishing-map-e2e/src/e2e/vessel-viewer/direct-access.cy.ts, apps/fishing-map-e2e/src/e2e/vessel-viewer/map-access.cy.ts, apps/fishing-map-e2e/src/e2e/vessel-viewer/search-vessel.cy.ts, apps/fishing-map-e2e/src/support/app.po.ts, apps/fishing-map-e2e/src/support/commands.ts, apps/fishing-map/cloudbuild.yaml, apps/fishing-map/features/reports/shared/activity/ReportActivity.tsx, apps/fishing-map/features/search/Search.tsx, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/features/workspace/activity/ActivitySection.tsx, libs/ui-components/src/spinner/Spinner.tsx
Restore e2e test and run them after deploy again
=> Fishing-map-e2e/fix-tests

apps/fishing-map/pages/_document.tsx
Testing https://app.meticulous.ai/
=> add meticulous script

libs/deck-layers/src/layers/fourwings/positions/FourwingsPositionsTileLayer.ts, libs/deck-layers/src/layers/vessel/LabelLayer.ts, libs/deck-layers/src/layers/vessel/VesselLayer.ts
=> deck-layers/labels

apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/dataviews/dataviews.utils.ts, apps/fishing-map/features/dataviews/selectors/dataviews.resolvers.selectors.ts, apps/fishing-map/features/reports/shared/vessels/report-vessels.hooks.ts, apps/fishing-map/features/search/SearchActions.tsx, apps/fishing-map/features/vessel/VesselPin.tsx, apps/fishing-map/features/vessel/vessel.slice.ts
Load vessel events depending on the info dataset to support private events by VMS
=> select vessel dataview template based on datasets

apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightFlagChange.tsx, apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightVesselEvents.tsx, apps/fishing-map/features/vessel/identity/VesselIdentityCombinedSourceField.tsx, apps/fishing-map/features/vessel/insights/InsightGapsDetails.tsx, apps/fishing-map/queries/vessel-events-api.ts
A couple of minor fixes for vessel group report:
- [Flag changes](https://globalfishingwatch.atlassian.net/browse/MAP-1432)
- [Events order](https://globalfishingwatch.atlassian.net/browse/VV-659)
=> Fishing map/report fixes

apps/fishing-map/features/datasets/upload/NewPointsDataset.tsx, apps/fishing-map/features/datasets/upload/NewPolygonDataset.tsx, apps/fishing-map/features/datasets/upload/NewTrackDataset.tsx, apps/fishing-map/features/datasets/upload/datasets-upload.utils.ts, apps/fishing-map/public/locales/source/translations.json
=> better dataset name upload validation

apps/fishing-map/features/app/App.module.css, apps/fishing-map/features/map/controls/MapControlScreenshot.tsx, apps/fishing-map/features/map/map-bounds.hooks.ts, apps/fishing-map/features/timebar/Timebar.tsx, apps/fishing-map/features/timebar/timebar-vessel.hooks.ts, apps/fishing-map/features/timebar/timebar.config.ts, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, libs/timebar/src/charts/tracks-events.module.css, libs/timebar/src/charts/tracks-events.tsx, libs/timebar/src/components/interval-selector.module.css, libs/timebar/src/components/interval-selector.tsx, libs/timebar/src/components/playback.module.css, libs/timebar/src/constants.ts, libs/timebar/src/timebar.module.css, libs/timebar/src/timebar.tsx
=> Fishing map/resizable timebar

apps/data-download-portal/src/components/markdown/markdown.tsx, apps/data-download-portal/src/components/topBar/topBar.module.css, libs/ui-components/src/base.css
[Bold, list and images not recognized in the new UI](https://globalfishingwatch.atlassian.net/browse/DOWNLOAD-98)
=> fix display images and bold h2 in dataset readme

apps/fishing-map/data/dataviews.ts, apps/fishing-map/data/default-workspaces/workspace.development.ts, apps/fishing-map/data/default-workspaces/workspace.production.ts, apps/fishing-map/data/layer-library/layers-activity.ts, apps/fishing-map/data/workspaces.ts, apps/fishing-map/features/layer-library/LayerLibraryItem.tsx, apps/fishing-map/features/reports/report-vessel-group/vessel-group-report.dataviews.ts, apps/fishing-map/features/reports/shared/vessels/ReportVesselsTableFooter.tsx, apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightCoverage.tsx, apps/fishing-map/features/reports/tabs/vessel-group-insights/VGRInsightGaps.tsx, apps/fishing-map/features/search/advanced/SearchAdvancedResults.tsx, apps/fishing-map/features/search/basic/SearchBasicResult.module.css, apps/fishing-map/features/search/basic/SearchBasicResult.tsx, apps/fishing-map/features/search/search.config.ts, apps/fishing-map/features/sidebar/SidebarHeader.tsx, apps/fishing-map/features/vessel/activity/event/ActivityDate.tsx, apps/fishing-map/features/vessel/activity/event/event.bounds.ts, apps/fishing-map/features/vessel/identity/VesselIdentity.tsx, apps/fishing-map/features/workspace/activity/activity.utils.ts, apps/fishing-map/features/workspace/legacy-activity-category.hook.ts, apps/fishing-map/features/workspace/shared/LayerFilters.module.css, apps/fishing-map/features/workspace/shared/LayerSchemaFilter.tsx, apps/fishing-map/public/locales/source/translations.json, libs/ui-components/src/color-bar/color-bar-options.ts
=> Fishing map/usability sprint jun 2025 jc

apps/fishing-map/features/vessel/vesselCorrection/VesselCorrectionModal.tsx, apps/fishing-map/pages/api/corrections.ts, apps/fishing-map/public/locales/en/translations.json, apps/fishing-map/public/locales/source/translations.json, apps/fishing-map/utils/info.ts
This pull request introduces changes to improve the handling of vessel identity corrections, streamline data processing, and enhance translation consistency. Key updates include adding alphabetical sorting for dropdown options, refining identity source handling, and updating translations to align with new terminology.
* [`apps/fishing-map/features/vessel/vesselCorrection/VesselCorrectionModal.tsx`](diffhunk://#diff-2b9af73ff4f9cb7f6e5efdfff36589c7e204d5ff70667b321ad77a4d27ded6fcL241-R250): Added alphabetical sorting for dropdown options using the new `sortOptionsAlphabetically` function for fields like `geartypes`, `shiptypes`, and `flag`.
* [`apps/fishing-map/pages/api/corrections.ts`](diffhunk://#diff-dc294083ae86dc42cea19a8ebfb2d4976c42f3dc11b3cf3246b02b38e339d939R5-R56): Refined …
=> Vessel info tool

package.json, yarn.lock
https://github.com/nrwl/nx/issues/32031
=> fix stylus not found

.husky/pre-push, apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx, apps/fishing-map/i18next-parser.config.js, package.json
=> i18n improvemments

apps/api-portal/components/header/header.tsx, apps/api-portal/pages/_app.tsx, apps/fishing-map/pages/api/corrections.ts, libs/ui-components/src/header/Header.tsx
[logout on api-portal](https://globalfishingwatch.atlassian.net/browse/API-1395?actionerId=5f08843810846200158cdd62&sourceType=assign)
add ssvid/mmsi in master spreadsheet
=> General fixes

apps/fishing-map/features/bigquery/BigQueryModal.tsx, apps/fishing-map/features/bigquery/TurningTidesModal.tsx, apps/fishing-map/features/bigquery/bigquery.hooks.ts, apps/fishing-map/features/bigquery/bigquery.slice.ts, apps/fishing-map/features/bigquery/turning-tides.config.ts, apps/fishing-map/features/i18n/i18n.types.d.ts, apps/fishing-map/features/modals/Modals.tsx, apps/fishing-map/features/track-correction/track-correction.config.ts, apps/fishing-map/features/workspace/activity/ActivityLayerPanel.tsx, apps/fishing-map/features/workspace/activity/TurningTidesFilters.tsx, apps/fishing-map/features/workspace/activity/TurningTidesTags.tsx, apps/fishing-map/public/locales/source/translations.json
Support creating custom Turning Tides datasets in a new modal with:
- Larger TTL
- Included related vessel Datasets
- Fixed interaction
Also includes the vessel filter for those datasets:
=> Fishing map/turning tides improvements

apps/fishing-map/features/timebar/timebar-vessel.hooks.ts, libs/timebar/src/charts/tracks.tsx
Spacing between user uploaded data with distinct line ids
=> Fishing map/fix track user data
